	tilepal 0, GRAY, WATER, WATER, GRAY, GRAY, RED, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, RED, RED, RED, BROWN
	tilepal 0, ROOF, WATER, WATER, WATER, WATER, RED, BROWN, BROWN
	tilepal 0, BROWN, BROWN, ROOF, WATER, RED, RED, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, WATER, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, WATER, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, WATER, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, WATER, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, GRAY, WATER, WATER, GRAY, GRAY, RED, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, RED, RED, RED, BROWN

rept 8
	db $ff
endr

	tilepal 1, ROOF, WATER, WATER, WATER, WATER, RED, BROWN, BROWN
	tilepal 1, BROWN, BROWN, ROOF, WATER, RED, RED, GRAY, GRAY
	tilepal 1, BROWN, BROWN, BROWN, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, RED, ROOF, ROOF, ROOF
	tilepal 1, ROOF, GRAY, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
