	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 01
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 02
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 03
	tilecoll WALL, WALL, WALL, FLOOR ; 04
	tilecoll WALL, WALL, FLOOR, FLOOR ; 05
	tilecoll WALL, WALL, FLOOR, WALL ; 06
	tilecoll WALL, WALL, WALL, WALL ; 07
	tilecoll WALL, FLOOR, WALL, FLOOR ; 08
	tilecoll FLOOR, FLOOR, HOLE, FLOOR ; 09
	tilecoll FLOOR, WALL, FLOOR, WALL ; 0a
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 0b
	tilecoll WALL, FLOOR, WALL, WALL ; 0c
	tilecoll FLOOR, FLOOR, WALL, WALL ; 0d
	tilecoll FLOOR, WALL, WALL, WALL ; 0e
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 0f
	tilecoll WALL, FLOOR, WALL, FLOOR ; 10
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 11
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 12
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 13
	tilecoll WALL, WALL, WALL, WALL ; 14
	tilecoll WALL, WALL, FLOOR, FLOOR ; 15
	tilecoll LADDER, LADDER, FLOOR, FLOOR ; 16
	tilecoll WALL, WALL, WALL, WALL ; 17
	tilecoll FLOOR, FLOOR, WALL, WALL ; 18
	tilecoll FLOOR, FLOOR, WALL, WALL ; 19
	tilecoll FLOOR, WALL, FLOOR, WALL ; 1a
	tilecoll WALL, FLOOR, WALL, WALL ; 1b
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 1c
	tilecoll WALL, FLOOR, WALL, FLOOR ; 1d
	tilecoll FLOOR, WALL, FLOOR, WALL ; 1e
	tilecoll WALL, WALL, WALL, WALL ; 1f
	tilecoll WALL, FLOOR, WALL, FLOOR ; 20
	tilecoll WALL, WALL, FLOOR, FLOOR ; 21
	tilecoll WALL, WALL, FLOOR, FLOOR ; 22
	tilecoll WALL, WALL, FLOOR, FLOOR ; 23
	tilecoll WALL, WALL, WALL, WALL ; 24
	tilecoll FLOOR, WALL, FLOOR, WALL ; 25
	tilecoll WALL, FLOOR, WALL, FLOOR ; 26
	tilecoll WALL, WALL, WALL, WALL ; 27
	tilecoll FLOOR, FLOOR, FLOOR, LADDER ; 28
	tilecoll FLOOR, FLOOR, FLOOR, LADDER ; 29
	tilecoll WALL, WALL, WALL, WALL ; 2a
	tilecoll WALL, WALL, WALL, WALL ; 2b
	tilecoll WALL, WALL, WALL, WALL ; 2c
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 2d
	tilecoll ICE, ICE, ICE, FLOOR ; 2e
	tilecoll ICE, ICE, FLOOR, ICE ; 2f
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 30
	tilecoll FLOOR, ICE, ICE, ICE ; 31
	tilecoll ICE, FLOOR, ICE, ICE ; 32
	tilecoll WALL, WALL, FLOOR, FLOOR ; 33
	tilecoll WALL, WALL, FLOOR, FLOOR ; 34
	tilecoll ICE, WALL, ICE, WALL ; 35
	tilecoll WALL, ICE, WALL, ICE ; 36
	tilecoll WALL, WALL, WALL, WALL ; 37
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 38
	tilecoll ICE, ICE, ICE, ICE ; 39
	tilecoll WALL, FLOOR, FLOOR, WALL ; 3a
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 3b
	tilecoll DOOR, DOOR, FLOOR, FLOOR ; 3c
	tilecoll WALL, FLOOR, WALL, FLOOR ; 3d
	tilecoll WALL, WALL, WALL, WALL ; 3e
	tilecoll WALL, WALL, WALL, WALL ; 3f
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 40
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 41
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 42
	tilecoll WALL, FLOOR, WALL, FLOOR ; 43
	tilecoll WALL, WALL, FLOOR, FLOOR ; 44
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 45
	tilecoll WALL, WALL, WALL, WALL ; 46
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 47
	tilecoll FLOOR, WALL, FLOOR, WALL ; 48
	tilecoll WALL, FLOOR, WALL, FLOOR ; 49
	tilecoll WALL, WALL, FLOOR, WALL ; 4a
	tilecoll WALL, WALL, WALL, FLOOR ; 4b
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 4c
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 4d
	tilecoll WALL, WALL, WALL, WALL ; 4e
	tilecoll WALL, WALL, WALL, WALL ; 4f
	tilecoll WALL, WALL, WALL, WALL ; 50
	tilecoll WALL, WALL, WALL, WALL ; 51
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 52
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 53
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 54
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 55
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 56
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 57
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 58
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 59
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 5a
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 5b
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 5c
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 5d
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 5e
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 5f
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 60
	tilecoll WALL, WALL, WALL, WALL ; 61
	tilecoll WALL, WALL, WALL, WALL ; 62
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 63
	tilecoll WALL, WALL, WALL, WALL ; 64
	tilecoll WALL, WALL, WALL, WALL ; 65
	tilecoll WALL, WALL, WALL, WALL ; 66
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 67
