	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll WALL, WALL, WALL, WALL ; 01
	tilecoll WALL, STAIRCASE, FLOOR, FLOOR ; 02
	tilecoll WALL, WALL, TV, BOOKSHELF ; 03
	tilecoll WALL, WALL, FLOOR, FLOOR ; 04
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 05
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 06
	tilecoll WALL, WALL, FLOOR, FLOOR ; 07
	tilecoll WALL, WALL, FLOOR, FLOOR ; 08
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 09
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0a
	tilecoll WALL, WALL, FLOOR, FLOOR ; 0b
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0c
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0d
	tilecoll WALL, WALL, FLOOR, FLOOR ; 0e
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0f
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 10
	tilecoll WALL, WALL, FLOOR, FLOOR ; 11
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 12
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 13
	tilecoll WALL, WALL, FLOOR, FLOOR ; 14
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 15
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 16
	tilecoll WALL, WALL, FLOOR, FLOOR ; 17
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 18
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 19
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 1a
	tilecoll WALL, FLOOR, WALL, FLOOR ; 1b
	tilecoll WALL, FLOOR, WALL, FLOOR ; 1c
	tilecoll WALL, FLOOR, WALL, FLOOR ; 1d
	tilecoll WALL, FLOOR, WALL, FLOOR ; 1e
	tilecoll TOWN_MAP, STAIRCASE, FLOOR, FLOOR ; 1f
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 20
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 21
	tilecoll FLOOR, WALL, FLOOR, WALL ; 22
	tilecoll WALL, STAIRCASE, FLOOR, FLOOR ; 23
	tilecoll WALL, STAIRCASE, FLOOR, FLOOR ; 24
	tilecoll WALL, STAIRCASE, FLOOR, FLOOR ; 25
