	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN
	tilepal 0, GREEN, BROWN, BROWN, GREEN, GREEN, RED, GRAY, GRAY
	tilepal 0, GRAY, BROWN, BROWN, TEXT, TEXT, BROWN, BROWN, BROWN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, WATER, WATER, YELLOW, TEXT
	tilepal 0, TEXT, BROWN, BROWN, TEXT, TEXT, BROWN, BROWN, BROWN
