	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, TEXT, TEXT, TEXT
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, TEXT, TEXT, TEXT
	tilepal 0, GREEN, BROWN, BROWN, GREEN, GREEN, RED, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 0, GREEN, GREEN, GREEN, GREEN, WATER, WATER, TEXT, TEXT
	tilepal 0, TEXT, BROWN, BROWN, TEXT, TEXT, TEXT, TEXT, TEXT