	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll WALL, WALL, WALL, WALL ; 01
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 02
	tilecoll TALL_GRASS, TALL_GRASS, TALL_GRASS, TALL_GRASS ; 03
	tilecoll WALL, TOP_WALL, WALL, FLOOR ; 04
	tilecoll TOP_WALL, TOP_WALL, FLOOR, FLOOR ; 05
	tilecoll TOP_WALL, WALL, FLOOR, WALL ; 06
	tilecoll FLOOR, FLOOR, FLOOR, LADDER ; 07
	tilecoll WALL, FLOOR, WALL, FLOOR ; 08
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 09
	tilecoll FLOOR, WALL, FLOOR, WALL ; 0a
	tilecoll FLOOR, FLOOR, FLOOR, LADDER ; 0b
	tilecoll WALL, FLOOR, WALL, WALL ; 0c
	tilecoll FLOOR, FLOOR, WALL, WALL ; 0d
	tilecoll FLOOR, WALL, WALL, WALL ; 0e
	tilecoll WATER, WATER, WATER, WATER ; 0f
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 10
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 11
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 12
	tilecoll FLOOR, BOTTOM_WALL, WALL, CAVE ; 13
	tilecoll TOP_WALL, TOP_WALL, FLOOR, LADDER ; 14
	tilecoll TOP_WALL, TOP_WALL, FLOOR, LADDER ; 15
	tilecoll WALL, FLOOR, WALL, WARP_CARPET_DOWN ; 16
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 17
	tilecoll WALL, WALL, WALL, FLOOR ; 18
	tilecoll WALL, WALL, FLOOR, FLOOR ; 19
	tilecoll WALL, WALL, FLOOR, WALL ; 1a
	tilecoll FLOOR, FLOOR, FLOOR, LADDER ; 1b
	tilecoll WALL, FLOOR, WALL, FLOOR ; 1c
	tilecoll WALL, WALL, WALL, WALL ; 1d
	tilecoll FLOOR, WALL, FLOOR, WALL ; 1e
	tilecoll FLOOR, FLOOR, FLOOR, LADDER ; 1f
	tilecoll WALL, FLOOR, WALL, WALL ; 20
	tilecoll FLOOR, FLOOR, WALL, WALL ; 21
	tilecoll FLOOR, WALL, WALL, WALL ; 22
	tilecoll TOP_WALL, WALL, FLOOR, FLOOR ; 23
	tilecoll FLOOR, FLOOR, FLOOR, WARP_CARPET_DOWN ; 24
	tilecoll WATER, WATER, WATER, WATER ; 25
	tilecoll WATER, WATER, WATER, WATER ; 26
	tilecoll WATER, WATER, WATER, WATER ; 27
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 28
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 29
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 2a
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 2b
	tilecoll WATERFALL, WATERFALL, WATERFALL, WATERFALL ; 2c
	tilecoll WALL, WALL, WALL, WALL ; 2d
	tilecoll WALL, WALL, WALL, WALL ; 2e
	tilecoll WALL, WALL, WALL, WALL ; 2f
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 30
	tilecoll WALL, WALL, WALL, WALL ; 31
	tilecoll WATER, WATER, WATER, WATER ; 32
	tilecoll WATER, WATER, WATER, WATER ; 33
	tilecoll WALL, WALL, WALL, WALL ; 34
	tilecoll FLOOR, WALL, FLOOR, WALL ; 35
	tilecoll FLOOR, WALL, FLOOR, WALL ; 36
	tilecoll WALL, WALL, WALL, CAVE ; 37
	tilecoll WALL, LEDGE_DOWN_LEFT, WALL, WALL ; 38
	tilecoll LEDGE_DOWN, LEDGE_DOWN, WALL, WALL ; 39
	tilecoll LEDGE_DOWN_RIGHT, WALL, WALL, WALL ; 3a
	tilecoll WALL, LEDGE_LEFT, WALL, LEDGE_LEFT ; 3b
	tilecoll LEDGE_RIGHT, WALL, LEDGE_RIGHT, WALL ; 3c
	tilecoll WATER, WATER, WATER, WATER ; 3d
	tilecoll WATER, WATER, WATER, WATER ; 3e
	tilecoll FLOOR, FLOOR, HOLE, FLOOR ; 3f
	tilecoll WALL, WALL, WALL, FLOOR ; 40
	tilecoll WALL, WALL, FLOOR, FLOOR ; 41
	tilecoll WALL, WALL, FLOOR, WALL ; 42
	tilecoll WALL, WALL, WALL, WALL ; 43
	tilecoll WALL, FLOOR, WALL, FLOOR ; 44
	tilecoll WALL, WALL, FLOOR, LADDER ; 45
	tilecoll FLOOR, WALL, FLOOR, WALL ; 46
	tilecoll WALL, WALL, WALL, WALL ; 47
	tilecoll WALL, FLOOR, WALL, WALL ; 48
	tilecoll FLOOR, FLOOR, WALL, WALL ; 49
	tilecoll FLOOR, WALL, WALL, WALL ; 4a
	tilecoll WALL, WALL, FLOOR, FLOOR ; 4b
	tilecoll WALL, WALL, FLOOR, LADDER ; 4c
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 4d
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 4e
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 4f
	tilecoll TOP_WALL, WALL, FLOOR, WALL ; 50
	tilecoll WALL, TOP_WALL, WALL, FLOOR ; 51
	tilecoll WALL, FLOOR, WALL, FLOOR ; 52
	tilecoll WALL, FLOOR, WALL, WALL ; 53
	tilecoll WALL, WALL, WALL, WALL ; 54
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 55
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 56
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 57
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 58
	tilecoll WALL, WALL, WALL, WALL ; 59
	tilecoll WALL, WALL, WALL, WALL ; 5a
	tilecoll WALL, WALL, WALL, WALL ; 5b
	tilecoll WALL, WALL, WALL, WALL ; 5c
	tilecoll FLOOR, WALL, FLOOR, WALL ; 5d
	tilecoll WALL, WALL, FLOOR, WALL ; 5e
	tilecoll WALL, WALL, FLOOR, FLOOR ; 5f
	tilecoll WALL, WALL, WALL, WALL ; 60
	tilecoll FLOOR, WALL, FLOOR, WARP_CARPET_DOWN ; 61
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 62
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 63
	tilecoll WALL, TOP_WALL, WALL, FLOOR ; 64
	tilecoll TOP_WALL, TOP_WALL, FLOOR, FLOOR ; 65
	tilecoll TOP_WALL, WALL, FLOOR, WALL ; 66
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 67
	tilecoll WALL, FLOOR, WALL, FLOOR ; 68
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 69
	tilecoll FLOOR, WALL, FLOOR, WALL ; 6a
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 6b
	tilecoll WALL, FLOOR, WALL, WALL ; 6c
	tilecoll FLOOR, FLOOR, WALL, WALL ; 6d
	tilecoll FLOOR, WALL, WALL, WALL ; 6e
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 6f
	tilecoll WALL, WALL, WALL, FLOOR ; 70
	tilecoll WALL, WALL, FLOOR, FLOOR ; 71
	tilecoll WALL, WALL, FLOOR, WALL ; 72
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 73
	tilecoll WALL, FLOOR, WALL, FLOOR ; 74
	tilecoll WALL, WALL, WALL, WALL ; 75
	tilecoll FLOOR, WALL, FLOOR, WALL ; 76
	tilecoll FLOOR, FLOOR, FLOOR, LADDER ; 77
	tilecoll WALL, FLOOR, WALL, WALL ; 78
	tilecoll FLOOR, FLOOR, WALL, WALL ; 79
	tilecoll FLOOR, WALL, WALL, WALL ; 7a
	tilecoll FLOOR, FLOOR, FLOOR, LADDER ; 7b
	tilecoll TOP_WALL, WALL, FLOOR, FLOOR ; 7c
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 7d
	tilecoll FLOOR, BOTTOM_WALL, WALL, CAVE ; 7e
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 7f
	tilecoll LEDGE_DOWN, LEDGE_DOWN, WALL, WALL ; 80
	tilecoll FLOOR, FLOOR, FLOOR, WARP_CARPET_DOWN ; 81
	tilecoll LEFT_WALL, RIGHT_WALL, LEFT_WALL, RIGHT_WALL ; 82
	tilecoll WALL, WALL, WALL, WALL ; 83
	tilecoll FLOOR, FLOOR, LADDER, FLOOR ; 84
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 85
	tilecoll FLOOR, FLOOR, LEFT_WALL, RIGHT_WALL ; 86
	tilecoll LEFT_WALL, RIGHT_WALL, FLOOR, FLOOR ; 87
	tilecoll WALL, TOP_WALL, WALL, FLOOR ; 88
	tilecoll TOP_WALL, WALL, FLOOR, WALL ; 89
	tilecoll FLOOR, FLOOR, LADDER, FLOOR ; 8a
	tilecoll FLOOR, FLOOR, WALL, ROCK_CLIMB ; 8b
	tilecoll WALL, FLOOR, WALL, FLOOR ; 8c
	tilecoll LEFT_WALL, RIGHT_WALL, FLOOR, WARP_CARPET_DOWN ; 8d
	tilecoll WATER, WATER, WATER, WATER ; 8e
	tilecoll WATER, WATER, WATER, WATER ; 8f
	tilecoll WATER, WATER, WATER, WATER ; 90
	tilecoll FLOOR, FLOOR, FLOOR, WARP_CARPET_DOWN ; 91
	tilecoll WATER, WATER, WATER, WATER ; 92
	tilecoll WATER, WATER, WATER, WATER ; 93
	tilecoll WALL, WALL, WALL, WALL ; 94
	tilecoll WALL, WALL, WALL, WALL ; 95
	tilecoll WALL, WALL, WALL, WALL ; 96
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 97
	tilecoll FLOOR, FLOOR, WALL, WALL ; 98
	tilecoll WALL, WALL, TOP_WALL, WALL ; 99
	tilecoll WALL, WALL, WALL, WALL ; 9a
	tilecoll WALL, WALL, FLOOR, WALL ; 9b
	tilecoll WALL, WALL, FLOOR, FLOOR ; 9c
	tilecoll FLOOR, WALL, FLOOR, WALL ; 9d
	tilecoll FLOOR, WALL, FLOOR, WALL ; 9e
	tilecoll WALL, FLOOR, WALL, FLOOR ; 9f
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; a0
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; a1
	tilecoll DIVE_DOWN, DIVE_DOWN, DIVE_DOWN, DIVE_DOWN ; a2
	tilecoll WALL, WALL, WALL, FLOOR ; a3
	tilecoll WALL, WALL, FLOOR, FLOOR ; a4
	tilecoll WALL, FLOOR, WALL, FLOOR ; a5
	tilecoll WALL, WALL, FLOOR, FLOOR ; a6
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; a7
	tilecoll WALL, FLOOR, WALL, WALL ; a8
	tilecoll FLOOR, FLOOR, WALL, WALL ; a9
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; aa
	tilecoll FLOOR, FLOOR, WALL, WALL ; ab
	tilecoll WALL, WALL, WALL, WALL ; ac
	tilecoll WALL, WALL, WALL, WALL ; ad
	tilecoll WALL, WALL, WALL, WALL ; ae
	tilecoll FLOOR, FLOOR, ROCK_CLIMB, WALL ; af
	tilecoll WALL, WALL, WALL, WALL ; b0
	tilecoll WALL, WALL, WALL, WALL ; b1
	tilecoll WALL, WALL, FLOOR, FLOOR ; b2
	tilecoll WALL, WALL, FLOOR, FLOOR ; b3
	tilecoll ROCK_CLIMB, WALL, ROCK_CLIMB, WALL ; b4
	tilecoll WALL, WALL, WALL, WALL ; b5
	tilecoll WALL, WALL, WALL, WALL ; b6
	tilecoll WALL, WALL, FLOOR, WALL ; b7
	tilecoll ROCK_CLIMB, WALL, FLOOR, FLOOR ; b8
	tilecoll WALL, WALL, WALL, WALL ; b9
	tilecoll WALL, WALL, WALL, WALL ; ba
	tilecoll WALL, WALL, WALL, WALL ; bb
	tilecoll FLOOR, WALL, WALL, WALL ; bc
	tilecoll WALL, WALL, WALL, WALL ; bd
	tilecoll WALL, WALL, WALL, WALL ; be
	tilecoll WALL, WALL, FLOOR, FLOOR ; bf
	tilecoll WALL, WALL, WALL, WALL ; c0
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; c1
	tilecoll WALL, WALL, FLOOR, WALL ; c2
	tilecoll WALL, WALL, WALL, WALL ; c3
	tilecoll WALL, WALL, WALL, WALL ; c4
	tilecoll WALL, WALL, FLOOR, WALL ; c5
	tilecoll TOP_WALL, WALL, FLOOR, WALL ; c6
	tilecoll WALL, TOP_WALL, WALL, FLOOR ; c7
	tilecoll WALL, WALL, WALL, FLOOR ; c8
	tilecoll WALL, FLOOR, WALL, FLOOR ; c9
	tilecoll TOP_WALL, WALL, FLOOR, WALL ; ca
	tilecoll WALL, TOP_WALL, WALL, FLOOR ; cb
	tilecoll WATER, WATER, WATER, WATER ; cc
	tilecoll WALL, WALL, WALL, WALL ; cd
