	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 01
	tilecoll DIVE_UP, DIVE_UP, DIVE_UP, DIVE_UP ; 02
	tilecoll TALL_GRASS, TALL_GRASS, TALL_GRASS, TALL_GRASS ; 03
	tilecoll WALL, TOP_WALL, WALL, FLOOR ; 04
	tilecoll TOP_WALL, TOP_WALL, FLOOR, FLOOR ; 05
	tilecoll TOP_WALL, WALL, FLOOR, WALL ; 06
	tilecoll WALL, WALL, WALL, WALL ; 07
	tilecoll WALL, FLOOR, WALL, FLOOR ; 08
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 09
	tilecoll FLOOR, WALL, FLOOR, WALL ; 0a
	tilecoll WALL, TOP_WALL, WALL, FLOOR ; 0b
	tilecoll WALL, FLOOR, WALL, WALL ; 0c
	tilecoll FLOOR, FLOOR, WALL, WALL ; 0d
	tilecoll FLOOR, WALL, WALL, WALL ; 0e
	tilecoll TOP_WALL, WALL, FLOOR, WALL ; 0f
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 10
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 11
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 12
	tilecoll FLOOR, BOTTOM_WALL, WALL, CAVE ; 13
	tilecoll FLOOR, DIVE_UP, DIVE_UP, DIVE_UP ; 14
	tilecoll DIVE_UP, FLOOR, DIVE_UP, DIVE_UP ; 15
	tilecoll DIVE_UP, DIVE_UP, FLOOR, DIVE_UP ; 16
	tilecoll DIVE_UP, DIVE_UP, DIVE_UP, FLOOR ; 17
	tilecoll WALL, WALL, WALL, FLOOR ; 18
	tilecoll WALL, WALL, FLOOR, FLOOR ; 19
	tilecoll WALL, WALL, FLOOR, WALL ; 1a
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 1b
	tilecoll WALL, FLOOR, WALL, FLOOR ; 1c
	tilecoll WALL, WALL, WALL, WALL ; 1d
	tilecoll FLOOR, WALL, FLOOR, WALL ; 1e
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 1f
	tilecoll WALL, FLOOR, WALL, WALL ; 20
	tilecoll FLOOR, FLOOR, WALL, WALL ; 21
	tilecoll FLOOR, WALL, WALL, WALL ; 22
	tilecoll TOP_WALL, TOP_WALL, FLOOR, FLOOR ; 23
	tilecoll FLOOR, FLOOR, FLOOR, WARP_CARPET_DOWN ; 24
	tilecoll WALL, WALL, WALL, WALL ; 25
	tilecoll WALL, WALL, WALL, WALL ; 26
	tilecoll WALL, WALL, WALL, WALL ; 27
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 28
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 29
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 2a
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 2b
	tilecoll FLOOR, WALL, FLOOR, WALL ; 2c
	tilecoll WALL, WALL, FLOOR, FLOOR ; 2d
	tilecoll DOOR, WALL, FLOOR, FLOOR ; 2e
	tilecoll WALL, WALL, FLOOR, FLOOR ; 2f
	tilecoll WALL, WALL, FLOOR, FLOOR ; 30
	tilecoll WALL, WALL, WALL, FLOOR ; 31
	tilecoll WALL, WALL, FLOOR, FLOOR ; 32
	tilecoll WALL, FLOOR, FLOOR, WALL ; 33
	tilecoll FLOOR, FLOOR, WALL, WALL ; 34
	tilecoll FLOOR, LADDER, FLOOR, FLOOR ; 35
	tilecoll FLOOR, LADDER, FLOOR, FLOOR ; 36
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 37
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 38
	tilecoll WALL, WALL, WALL, WALL ; 39
	tilecoll WALL, FLOOR, WALL, FLOOR ; 3a
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 3b
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 3c
	tilecoll FLOOR, WALL, FLOOR, WALL ; 3d
	tilecoll WALL, FLOOR, WALL, FLOOR ; 3e
	tilecoll WALL, WALL, WALL, WALL ; 3f
	tilecoll WALL, FLOOR, WALL, FLOOR ; 40
	tilecoll FLOOR, WALL, FLOOR, WALL ; 41
	tilecoll WALL, WALL, WALL, WALL ; 42
	tilecoll WALL, WALL, WALL, WALL ; 43
	tilecoll WALL, WALL, WALL, WALL ; 44
	tilecoll WALL, WALL, WALL, WALL ; 45
	tilecoll WALL, WALL, WALL, WALL ; 46
	tilecoll WALL, WALL, WALL, WALL ; 47
	tilecoll WALL, WALL, STAIRCASE, WALL ; 48
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 49
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 4a
	tilecoll WALL, WALL, WALL, WALL ; 4b
	tilecoll WALL, WALL, WALL, WALL ; 4c
	tilecoll WALL, WALL, WALL, WALL ; 4d
	tilecoll WALL, WALL, FLOOR, FLOOR ; 4e
	tilecoll WALL, WALL, WALL, WALL ; 4f
	tilecoll FLOOR, FLOOR, WALL, WALL ; 50
	tilecoll FLOOR, FLOOR, WALL, WALL ; 51
	tilecoll WALL, WALL, WALL, WALL ; 52
	tilecoll WALL, WALL, WALL, WALL ; 53
	tilecoll WALL, WALL, WALL, WALL ; 54
	tilecoll WALL, WALL, WALL, WALL ; 55
	tilecoll WALL, WALL, WALL, WALL ; 56
	tilecoll WALL, WALL, WALL, WALL ; 57
	tilecoll DIVE_UP, DIVE_UP, DIVE_UP, DIVE_UP ; 58
