	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll WALL, WALL, WALL, WALL ; 00
