	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll WALL, WALL, FLOOR, WALL ; 01
	tilecoll WALL, WALL, WALL, WALL ; 02
	tilecoll WALL, WALL, WALL, WALL ; 03
	tilecoll WALL, FLOOR, WALL, FLOOR ; 04
	tilecoll FLOOR, WALL, FLOOR, WALL ; 05
	tilecoll WALL, WALL, WALL, WALL ; 06
	tilecoll WALL, WALL, WALL, WALL ; 07
	tilecoll WALL, FLOOR, WALL, FLOOR ; 08
	tilecoll FLOOR, WALL, FLOOR, WALL ; 09
	tilecoll WALL, WALL, WALL, WALL ; 0a
	tilecoll WALL, WALL, WALL, WALL ; 0b
	tilecoll WALL, WALL, WALL, WALL ; 0c
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0d
	tilecoll WALL, WALL, WALL, WALL ; 0e
	tilecoll WALL, WALL, WALL, WALL ; 0f
	tilecoll WALL, WALL, WALL, WALL ; 10
	tilecoll FLOOR, WALL, FLOOR, WALL ; 11
	tilecoll FLOOR, WALL, FLOOR, WALL ; 12
	tilecoll FLOOR, WALL, FLOOR, WALL ; 13
	tilecoll WALL, WALL, WALL, WALL ; 14
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 15
	tilecoll WALL, WALL, WALL, WALL ; 16
	tilecoll WALL, WALL, WALL, WALL ; 17
	tilecoll WALL, WALL, WALL, WALL ; 18
	tilecoll WALL, WALL, WALL, WALL ; 19
