	tilepal 0, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN, WATER, WATER
	tilepal 0, WATER, WATER, WATER, WATER, GRAY, GRAY, GRAY, GRAY
	tilepal 0, YELLOW, YELLOW, GRAY, GRAY, GREEN, GREEN, WATER, WATER
	tilepal 0, WATER, WATER, WATER, WATER, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, TEXT, TEXT, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, TEXT, TEXT, TEXT, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, TEXT, TEXT, TEXT, TEXT, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 0, WATER, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 0, WATER, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, WATER, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 0, TEXT, TEXT, GRAY, GRAY, GRAY, GRAY