	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 01
	tilecoll FLOOR, FLOOR, WALL, WALL ; 02
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 03
	tilecoll WALL, WALL, WALL, WALL ; 04
	tilecoll WALL, WALL, WALL, WALL ; 05
	tilecoll WALL, WALL, WALL, WALL ; 06
	tilecoll WALL, WALL, WALL, WALL ; 07
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 08
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 09
	tilecoll FLOOR, FLOOR, WALL, WALL ; 0a
	tilecoll WALL, WALL, WALL, WALL ; 0b
	tilecoll WALL, WALL, WALL, WALL ; 0c
	tilecoll WALL, WALL, WALL, WALL ; 0d
	tilecoll WALL, FLOOR, WALL, FLOOR ; 0e
	tilecoll WALL, WALL, WALL, WALL ; 0f
	tilecoll WALL, WALL, WALL, WALL ; 10
	tilecoll WALL, WALL, WALL, WALL ; 11
	tilecoll WALL, WALL, DOOR, DOOR ; 12
	tilecoll WALL, WALL, WALL, WALL ; 13
	tilecoll WALL, WALL, WALL, WALL ; 14
	tilecoll WALL, WALL, WALL, WALL ; 15
	tilecoll WALL, WALL, WALL, WALL ; 16
	tilecoll WALL, WALL, WALL, WALL ; 17
	tilecoll WALL, WALL, WALL, WALL ; 18
	tilecoll WALL, WALL, WALL, WALL ; 19
	tilecoll WALL, WALL, WALL, WALL ; 1a
	tilecoll FLOOR, FLOOR, WARP_CARPET_DOWN, WARP_CARPET_DOWN ; 1b
	tilecoll WALL, FLOOR, WALL, WALL ; 1c
	tilecoll WALL, WALL, WALL, WALL ; 1d
	tilecoll WALL, FLOOR, WALL, WALL ; 1e
	tilecoll FLOOR, WALL, WALL, WALL ; 1f
	tilecoll WALL, WALL, WALL, WALL ; 20
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 21
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 22
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 23
	tilecoll WALL, WALL, WALL, WALL ; 24
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 25
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 26
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 27
	tilecoll WALL, WALL, WALL, FLOOR ; 28
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 29
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 2a
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 2b
	tilecoll WALL, WALL, WALL, WALL ; 2c
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 2d
	tilecoll WALL, WALL, WALL, WALL ; 2e
	tilecoll WALL, WALL, DOOR, DOOR ; 2f
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 30
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 31
	tilecoll WALL, WALL, WALL, WALL ; 32
	tilecoll WALL, WALL, WALL, WALL ; 33
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 34
	tilecoll WALL, WALL, WALL, WALL ; 35
	tilecoll WALL, WALL, WALL, WALL ; 36
	tilecoll WALL, WALL, WALL, WALL ; 37
	tilecoll FLOOR, FLOOR, WALL, WALL ; 38
	tilecoll FLOOR, WALL, WALL, WALL ; 39
	tilecoll FLOOR, WALL, WALL, WALL ; 3a
	tilecoll FLOOR, WALL, WALL, WALL ; 3b
	tilecoll WALL, WALL, WALL, WALL ; 3c
	tilecoll WALL, WALL, FLOOR, WALL ; 3d
	tilecoll WALL, WALL, WALL, WALL ; 3e
	tilecoll WALL, WALL, WALL, WALL ; 3f
	tilecoll WALL, WALL, WALL, WALL ; 40
	tilecoll WALL, WALL, WALL, WALL ; 41
	tilecoll WALL, WALL, WALL, DOOR ; 42
	tilecoll WALL, WALL, WALL, WALL ; 43
	tilecoll FLOOR, WALL, FLOOR, FLOOR ; 44
	tilecoll WALL, WALL, WALL, WALL ; 45
	tilecoll WALL, WALL, WALL, FLOOR ; 46
	tilecoll WALL, FLOOR, WALL, FLOOR ; 47
	tilecoll FLOOR, WALL, FLOOR, WALL ; 48
	tilecoll WALL, FLOOR, WALL, WALL ; 49
	tilecoll WALL, WALL, FLOOR, FLOOR ; 4a
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 4b
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 4c
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 4d
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 4e
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 4f
	tilecoll WALL, WALL, WALL, WALL ; 50
	tilecoll WALL, WALL, WALL, WALL ; 51
	tilecoll FLOOR, WALL, WALL, WALL ; 52
	tilecoll FLOOR, WALL, WALL, WALL ; 53
	tilecoll WALL, WALL, WALL, DOOR ; 54
	tilecoll WALL, WALL, WALL, WALL ; 55
	tilecoll WALL, FLOOR, WALL, WALL ; 56
	tilecoll WALL, FLOOR, FLOOR, FLOOR ; 57
	tilecoll FLOOR, WALL, FLOOR, WALL ; 58
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 59
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 5a
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 5b
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 5c
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 5d
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 5e
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 5f
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 60
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 61
	tilecoll TOP_WALL, TOP_WALL, FLOOR, FLOOR ; 62
	tilecoll WALL, WALL, WALL, FLOOR ; 63
	tilecoll WALL, WALL, WALL, WALL ; 64
	tilecoll WALL, WALL, WALL, WALL ; 65
	tilecoll WALL, WALL, FLOOR, WALL ; 66
	tilecoll WALL, FLOOR, WALL, FLOOR ; 67
	tilecoll WALL, WALL, WALL, WALL ; 68
	tilecoll WALL, WALL, WALL, DOOR ; 69
	tilecoll WALL, WALL, WALL, WALL ; 6a
	tilecoll FLOOR, WALL, FLOOR, WALL ; 6b
	tilecoll FLOOR, FLOOR, WALL, WALL ; 6c
	tilecoll WALL, WALL, WALL, WALL ; 6d
	tilecoll WALL, WALL, DOOR, DOOR ; 6e
	tilecoll WALL, WALL, WALL, WALL ; 6f
	tilecoll WALL, FLOOR, WALL, FLOOR ; 70
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 71
	tilecoll WALL, WALL, WALL, WALL ; 72
	tilecoll WALL, WALL, WALL, WALL ; 73
	tilecoll WALL, WALL, WALL, WALL ; 74
	tilecoll WALL, WALL, WALL, WALL ; 75
	tilecoll WALL, WALL, WALL, WALL ; 76
