	tilecoll WALL, WALL, WALL, WALL ; 00
	tilecoll WALL, FLOOR, WALL, FLOOR ; 01
	tilecoll FLOOR, WALL, FLOOR, WALL ; 02
	tilecoll WALL, WALL, WALL, WALL ; 03
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 04
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 05
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 06
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 07
	tilecoll FLOOR, FLOOR, WALL, FLOOR ; 08
	tilecoll FLOOR, FLOOR, FLOOR, WALL ; 09
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 0a
	tilecoll WALL, WALL, WALL, FLOOR ; 0b
	tilecoll FLOOR, FLOOR, WALL, WALL ; 0c
	tilecoll FLOOR, FLOOR, WALL, WALL ; 0d
	tilecoll WALL, WALL, WALL, WALL ; 0e
	tilecoll WALL, WALL, FLOOR, WALL ; 0f
	tilecoll WALL, WALL, WALL, WALL ; 10
	tilecoll WALL, WALL, WALL, WALL ; 11
	tilecoll WALL, FLOOR, WALL, WALL ; 12
	tilecoll FLOOR, WALL, WALL, WALL ; 13
	tilecoll WALL, WALL, WALL, WALL ; 14
	tilecoll WALL, WALL, WALL, FLOOR ; 15
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 16
	tilecoll WALL, WALL, WALL, WALL ; 17
	tilecoll WALL, WALL, WALL, WALL ; 18
	tilecoll WALL, WALL, WALL, WALL ; 19
	tilecoll WALL, WALL, WALL, WALL ; 1a
	tilecoll WALL, WALL, WALL, WALL ; 1b
	tilecoll WALL, WALL, WALL, WALL ; 1c
	tilecoll WALL, WALL, WALL, WALL ; 1d
	tilecoll WALL, WALL, WALL, WALL ; 1e
	tilecoll WALL, WALL, WALL, WALL ; 1f
	tilecoll WALL, WALL, WALL, WALL ; 20
	tilecoll WALL, WALL, WALL, WALL ; 21
	tilecoll WALL, FLOOR, WALL, FLOOR ; 22
	tilecoll WALL, WALL, WALL, WALL ; 23
	tilecoll WALL, WALL, WALL, WALL ; 24
	tilecoll WALL, WALL, WALL, WALL ; 25
	tilecoll WALL, WALL, WALL, WALL ; 26
	tilecoll WALL, WALL, WALL, WALL ; 27
	tilecoll WALL, WALL, WALL, WALL ; 28
	tilecoll WALL, WALL, WALL, WALL ; 29
	tilecoll WALL, FLOOR, WALL, FLOOR ; 2a
	tilecoll WALL, WALL, WALL, WALL ; 2b
	tilecoll DIVE_DOWN, DIVE_DOWN, DIVE_DOWN, DIVE_DOWN ; 2c
	tilecoll DIVE_DOWN, DIVE_DOWN, DIVE_DOWN, DIVE_DOWN ; 2d
	tilecoll WALL, WALL, WALL, WALL ; 2e
	tilecoll FLOOR, WARP_CARPET_RIGHT, FLOOR, WARP_CARPET_RIGHT ; 2f
	tilecoll BUOY, BUOY, BUOY, WATER ; 30
	tilecoll BUOY, BUOY, WATER, WATER ; 31
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 32
	tilecoll LADDER, LADDER, LADDER, LADDER ; 33
	tilecoll BUOY, WATER, BUOY, WATER ; 34
	tilecoll WATER, WATER, WATER, WATER ; 35
	tilecoll DIVE_DOWN, DIVE_DOWN, DIVE_DOWN, DIVE_DOWN ; 36
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 37
	tilecoll FLOOR, WARP_CARPET_RIGHT, FLOOR, WARP_CARPET_RIGHT ; 38
	tilecoll WALL, WALL, WALL, WALL ; 39
	tilecoll FLOOR, FLOOR, FLOOR, FLOOR ; 3a
	tilecoll DIVE_DOWN, DIVE_DOWN, DIVE_DOWN, DIVE_DOWN ; 3b
	tilecoll WALL, WALL, WALL, WALL ; 3c
	tilecoll DIVE_DOWN, DIVE_DOWN, DIVE_DOWN, DIVE_DOWN ; 3d
	tilecoll WALL, WALL, WALL, WALL ; 3e
	tilecoll WALL, WALL, WALL, WALL ; 3f
