	const_def

	const ENGINE_PLAYER_IS_FEMALE
	const ENGINE_DST
	const ENGINE_STRENGTH_ACTIVE
	const ENGINE_ALWAYS_ON_BIKE
	const ENGINE_DOWNHILL
	const ENGINE_POKEDEX
	const ENGINE_POKERUS
	const ENGINE_EXP_ALL
	const ENGINE_CREDITS_SKIP
	const ENGINE_BUG_CONTEST_ON
	const ENGINE_BUG_CONTEST_TIMER
	const ENGINE_CORAL_EYE_BADGE
	const ENGINE_SEA_RUBY_BADGE
	const ENGINE_SPIKE_SHELL_BADGE
	const ENGINE_JADE_STAR_BADGE
	const ENGINE_FLYPOINT_KRISS_HOUSE
	const ENGINE_FLYPOINT_VALENCIA
	const ENGINE_FLYPOINT_TANGELO
	const ENGINE_FLYPOINT_MIKAN
	const ENGINE_FLYPOINT_MANDARIN_NORTH
	const ENGINE_FLYPOINT_SUNBURST
	const ENGINE_FLYPOINT_KINNOW
	const ENGINE_FLYPOINT_NAVEL
	const ENGINE_FLYPOINT_MORO
	const ENGINE_FLYPOINT_MURCOTT
	const ENGINE_FLYPOINT_TROVITOPOLIS
	const ENGINE_FLYPOINT_TROVITA
	const ENGINE_FLYPOINT_ASCORBIA
	const ENGINE_FLYPOINT_KUMQUAT
	const ENGINE_FLYPOINT_PUMMELO
	const ENGINE_FLYPOINT_HAMLIN
	const ENGINE_FLYPOINT_SHAMOUTI
	const ENGINE_FLYPOINT_VERMILION
	const ENGINE_DAYCARE_MAN_HAS_EGG
	const ENGINE_DAYCARE_MAN_HAS_MON
	const ENGINE_DAYCARE_LADY_HAS_MON
	const ENGINE_DAILY_BUG_CONTEST
	const ENGINE_BARGAINED_TODAY
	const ENGINE_TEA_IN_BLUES_HOUSE
	const ENGINE_GOT_HAIRCUT
	const ENGINE_GOLDENROD_DEPT_STORE_SALE_IS_ON
	const ENGINE_LUCKY_NUMBER_SHOW
	const ENGINE_KRIS_IN_CABLE_CLUB
	const ENGINE_YANMA_SWARM

NUM_ENGINE_FLAGS EQU const_value
