
	const_def

; These first eight flags are reset upon reloading the map.
	const EVENT_TEMPORARY_1
	const EVENT_TEMPORARY_2
	const EVENT_TEMPORARY_3
	const EVENT_TEMPORARY_4
	const EVENT_TEMPORARY_5
	const EVENT_TEMPORARY_6
	const EVENT_TEMPORARY_7
	const EVENT_TEMPORARY_8

; Story events
	const EVENT_INITIALIZED_EVENTS
	const EVENT_LISTENED_TO_INITIAL_RADIO
	const EVENT_TOWN_MAP_OBTAINED
	const EVENT_GOT_A_POKEMON_FROM_IVY
	const EVENT_GOT_BULBASAUR_FROM_IVY
	const EVENT_GOT_CHARMANDER_FROM_IVY
	const EVENT_GOT_SQUIRTLE_FROM_IVY
	const EVENT_GOT_GS_BALL_FROM_TRACEY
	const EVENT_GAVE_MYSTERY_EGG_TO_ELM
	const EVENT_GOT_TM05_ROAR
	const EVENT_GOT_OLD_ROD
	const EVENT_GOT_TM32_BUBBLEBEAM
	const EVENT_GOT_SHARP_BEAK
	const EVENT_EXPLODING_TRAP_1
	const EVENT_EXPLODING_TRAP_2
	const EVENT_EXPLODING_TRAP_3
	const EVENT_EXPLODING_TRAP_4
	const EVENT_EXPLODING_TRAP_5
	const EVENT_EXPLODING_TRAP_6
	const EVENT_EXPLODING_TRAP_7
	const EVENT_EXPLODING_TRAP_8
	const EVENT_EXPLODING_TRAP_9

; Not yet used
	const EVENT_WELCOMED_TO_POKECOM_CENTER
	const EVENT_GOLDENROD_SALE_OFF
	const EVENT_GOLDENROD_SALE_ON
	const EVENT_WAREHOUSE_ENTRANCE_GRAMPS
	const EVENT_WAREHOUSE_ENTRANCE_GRANNY
	const EVENT_WAREHOUSE_ENTRANCE_OLDER_HAIRCUT_BROTHER
	const EVENT_WAREHOUSE_ENTRANCE_YOUNGER_HAIRCUT_BROTHER
	const EVENT_WAREHOUSE_LAYOUT_1
	const EVENT_WAREHOUSE_LAYOUT_2
	const EVENT_WAREHOUSE_LAYOUT_3
	const EVENT_WAREHOUSE_BLOCKED_OFF

; Switch puzzles
	const EVENT_SWITCH_1
	const EVENT_SWITCH_2
	const EVENT_SWITCH_3
	const EVENT_SWITCH_4
	const EVENT_SWITCH_5
	const EVENT_SWITCH_6
	const EVENT_SWITCH_7
	const EVENT_SWITCH_8
	const EVENT_SWITCH_9
	const EVENT_SWITCH_10
	const EVENT_SWITCH_11
	const EVENT_SWITCH_12
	const EVENT_SWITCH_13
	const EVENT_SWITCH_14
	const EVENT_EMERGENCY_SWITCH

; Boulder puzzles
	const EVENT_BOULDER_IN_ICE_PATH_1
	const EVENT_BOULDER_IN_ICE_PATH_1A
	const EVENT_BOULDER_IN_ICE_PATH_2
	const EVENT_BOULDER_IN_ICE_PATH_2A
	const EVENT_BOULDER_IN_ICE_PATH_3
	const EVENT_BOULDER_IN_ICE_PATH_3A
	const EVENT_BOULDER_IN_ICE_PATH_4
	const EVENT_BOULDER_IN_ICE_PATH_4A

; Bug-Catching Contest
	const EVENT_ROUTE_35_NATIONAL_PARK_GATE_OFFICER_CONTEST_DAY
	const EVENT_ROUTE_35_NATIONAL_PARK_GATE_OFFICER_NOT_CONTEST_DAY
	const EVENT_ROUTE_36_NATIONAL_PARK_GATE_OFFICER_CONTEST_DAY
	const EVENT_ROUTE_36_NATIONAL_PARK_GATE_OFFICER_NOT_CONTEST_DAY
	const EVENT_LEFT_MONS_WITH_CONTEST_OFFICER
	const EVENT_CONTEST_OFFICER_HAS_BERRY
	const EVENT_CONTEST_OFFICER_HAS_EVERSTONE
	const EVENT_CONTEST_OFFICER_HAS_GOLD_BERRY
	const EVENT_CONTEST_OFFICER_HAS_SUN_STONE
	const EVENT_WARPED_FROM_ROUTE_35_NATIONAL_PARK_GATE
	const EVENT_BUG_CATCHING_CONTESTANT_1A
	const EVENT_BUG_CATCHING_CONTESTANT_1B
	const EVENT_BUG_CATCHING_CONTESTANT_2A
	const EVENT_BUG_CATCHING_CONTESTANT_2B
	const EVENT_BUG_CATCHING_CONTESTANT_3A
	const EVENT_BUG_CATCHING_CONTESTANT_3B
	const EVENT_BUG_CATCHING_CONTESTANT_4A
	const EVENT_BUG_CATCHING_CONTESTANT_4B
	const EVENT_BUG_CATCHING_CONTESTANT_5A
	const EVENT_BUG_CATCHING_CONTESTANT_5B
	const EVENT_BUG_CATCHING_CONTESTANT_6A
	const EVENT_BUG_CATCHING_CONTESTANT_6B
	const EVENT_BUG_CATCHING_CONTESTANT_7A
	const EVENT_BUG_CATCHING_CONTESTANT_7B
	const EVENT_BUG_CATCHING_CONTESTANT_8A
	const EVENT_BUG_CATCHING_CONTESTANT_8B
	const EVENT_BUG_CATCHING_CONTESTANT_9A
	const EVENT_BUG_CATCHING_CONTESTANT_9B
	const EVENT_BUG_CATCHING_CONTESTANT_10A
	const EVENT_BUG_CATCHING_CONTESTANT_10B

; Trainer flags
	const EVENT_BEAT_ATHLETE_HIDEKI
	const EVENT_BEAT_ATHLETE_KAITO
	const EVENT_BEAT_BIRD_KEEPER_ABE
	const EVENT_BEAT_BIRD_KEEPER_PETER
	const EVENT_BEAT_BIRD_KEEPER_ROD
	const EVENT_BEAT_BROCK
	const EVENT_BEAT_BUG_CATCHER_ALEX
	const EVENT_BEAT_BUG_CATCHER_DON
	const EVENT_BEAT_BUG_CATCHER_MUSHI
	const EVENT_BEAT_BUG_CATCHER_WADE
	const EVENT_BEAT_BUG_CATCHER_WAYNE
	const EVENT_BEAT_CAMPER_ROLAND
	const EVENT_BEAT_ELITE_FOUR
	const EVENT_BEAT_FALKNER
	const EVENT_BEAT_FISHER_HENRY
	const EVENT_BEAT_FISHER_ISAO
	const EVENT_BEAT_FISHER_JUSTIN
	const EVENT_BEAT_FISHER_RALPH
	const EVENT_BEAT_HIKER_ANTHONY
	const EVENT_BEAT_HIKER_TEPPEI
	const EVENT_BEAT_PICNICKER_LIZ
	const EVENT_BEAT_POKEMANIAC_SHAWN
	const EVENT_BEAT_ROCKET_EXECUTIVEM_1
	const EVENT_BEAT_SIGHTSEERM_MICHIO
	const EVENT_BEAT_SWIMMERF_MAYUMI
	const EVENT_BEAT_SWIMMERF_PAULA
	const EVENT_BEAT_SWIMMERF_SAKAKO
	const EVENT_BEAT_SWIMMERF_UMIKO
	const EVENT_BEAT_SWIMMERF_YAEKO
	const EVENT_BEAT_SWIMMERM_ARNOLD
	const EVENT_BEAT_SWIMMERM_ARTURO
	const EVENT_BEAT_SWIMMERM_BRAND
	const EVENT_BEAT_SWIMMERM_KOSUKE
	const EVENT_BEAT_SWIMMERM_LUCAS
	const EVENT_BEAT_SWIMMERM_NAOYA
	const EVENT_BEAT_SWIMMERM_RANDY
	const EVENT_BEAT_YOUNGSTER_ALBERT
	const EVENT_BEAT_YOUNGSTER_GORDON
	const EVENT_BEAT_YOUNGSTER_JOEY
	const EVENT_BEAT_YOUNGSTER_MIKEY
	const EVENT_BEAT_YOUNGSTER_NESS

; Hidden items
	const EVENT_ILEX_FOREST_HIDDEN_ETHER
	const EVENT_ILEX_FOREST_HIDDEN_FULL_HEAL
	const EVENT_ILEX_FOREST_HIDDEN_SUPER_POTION
	const EVENT_OLIVINE_PORT_HIDDEN_PROTEIN
	const EVENT_ROUTE_30_HIDDEN_POTION
	const EVENT_ROUTE_32_HIDDEN_GREAT_BALL
	const EVENT_ROUTE_32_HIDDEN_SUPER_POTION
	const EVENT_ROUTE_55_HIDDEN_SOFT_SAND
	const EVENT_SUNBURST_HIDDEN_IRON
	const EVENT_SUNBURST_HIDDEN_MOONSTONE
	const EVENT_UNDERGROUND_HIDDEN_FULL_RESTORE
	const EVENT_UNDERGROUND_HIDDEN_X_SPECIAL
	const EVENT_VIOLET_CITY_HIDDEN_HYPER_POTION
	const EVENT_MANDARIN_NORTH_SUPER_POTION
	const EVENT_PINKAN_ISLAND_LOVE_BALL
	const EVENT_PINKAN_ISLAND_PINKAN_BERRY

; Sprite visibility: When these events are cleared, the sprite becomes visible; when set, the sprite is hidden.
; The map script command macros `disappear` and `appear` set/clear these flags and immediately apply the effect on visibility.
; The map script command macros `setevent` and `clearevent` set/clear these flags, and their effects will be seen when the map is reloaded.

; Items
	const EVENT_ROUTE_29_POTION
	const EVENT_ROUTE_30_ANTIDOTE
	const EVENT_ROUTE_31_POKE_BALL
	const EVENT_ROUTE_31_POTION
	const EVENT_ROUTE_32_GREAT_BALL
	const EVENT_ROUTE_32_REPEL
	const EVENT_ROUTE_55_DIVE_ITEM
	const EVENT_ROUTE_56_HP_UP
	const EVENT_ROUTE_56_TM
	const EVENT_ROUTE_56_ULTRA_BALL
	const EVENT_SUNBURST_TM_SWIFT
	const EVENT_TANGELO_SURF
	const EVENT_ILEX_FOREST_ANTIDOTE
	const EVENT_ILEX_FOREST_ETHER
	const EVENT_ILEX_FOREST_REVIVE
	const EVENT_ILEX_FOREST_X_ATTACK
	const EVENT_CRYSTAL_SHOP_ODD_CRYSTAL
	const EVENT_PINKAN_ISLAND_REVIVE
	const EVENT_PINKAN_ISLAND_TM
	const EVENT_VIOLET_CITY_PP_UP
	const EVENT_VIOLET_CITY_RARE_CANDY
	const EVENT_MANDARIN_CUT
	const EVENT_MANDARIN_RARE_CANDY
	const EVENT_MANDARIN_TM
	const EVENT_CRYSTAL_CAVE_1F_CARBOS
	const EVENT_CRYSTAL_CAVE_1F_MYSTIC_WATER
	const EVENT_CRYSTAL_CAVE_B1_TM

; People
	const EVENT_CHIKORITA_POKEBALL_IN_IVYS_LAB
	const EVENT_CYNDAQUIL_POKEBALL_IN_IVYS_LAB
	const EVENT_TOTODILE_POKEBALL_IN_IVYS_LAB
	const EVENT_DAYCARE_MAN_IN_DAYCARE
	const EVENT_DAYCARE_MAN_OUTSIDE
	const EVENT_TEAM_ROCKET_1
	const EVENT_TANGELO_TRACEY_LEAVING
	const EVENT_TRACEY_ROUTE_56_DONE
	const EVENT_GUIDE_GENT_IN_HIS_HOUSE
	const EVENT_BROCK_1F_DONE
	const EVENT_BROCK_LEAVING
	const EVENT_CRYSTAL_ONIX_DEFEATED

NUM_EVENTS EQU const_value
