GROUP_N_A EQU -1
MAP_N_A EQU -1
GROUP_NONE EQU 0
MAP_NONE EQU 0

; map group ids
	const_def

	newgroup ; 1

	mapgroup ROUTE_53, 9, 31
	mapgroup ROUTE_54, 17, 11
	mapgroup MANDARIN_NORTH, 17, 18
	mapgroup MANDARIN_NORTH_POKECENTER, 4, 5
	mapgroup MANDARIN_NORTH_NAME_RATER, 4, 4
	mapgroup MANDARIN_NORTH_SMALL_HOUSE, 4, 4
	mapgroup MANDARIN_NORTH_LARGE_HOUSE, 4, 4
	mapgroup MANDARIN_UNDERGROUND_ENTRANCE, 4, 4
	mapgroup MANDARIN_UNDERGROUND_BF1, 7, 7
	mapgroup MANDARIN_UNDERGROUND_BF2, 12, 10
	mapgroup MANDARIN_UNDERGROUND_BF3, 12, 8
	mapgroup MANDARIN_NORTH_MART, 4, 6

	newgroup ; 2

	mapgroup TANGELO_JUNGLE, 27, 25
	mapgroup MT_NAVEL_1F, 14, 14
	mapgroup MT_NAVEL_2F, 18, 18
	mapgroup MT_NAVEL_PEAK, 10, 10
	mapgroup MT_NAVEL_ICE_ROCK, 3, 3
	mapgroup CRYSTAL_CAVE_1F, 16, 18
	mapgroup CRYSTAL_CAVE_B1, 14, 18
	mapgroup MANDARIN_DESERT, 25, 25
	mapgroup SEWER_ENTRANCE, 3, 3
	mapgroup TROVITOPOLIS_SEWER, 28, 26
	mapgroup ROUTE_60, 32, 28
	mapgroup SUNRAY_CAVE_MANDARIN_DESERT_1F, 11, 17
	mapgroup TROVITA_ISLAND, 22, 24
	mapgroup FUKUHARA_NO_4_BF1, 20, 20
	mapgroup FUKUHARA_NO_4_BF2, 20, 20
	mapgroup FUKUHARA_NO_4_BF3, 10, 10
	mapgroup VICTORY_ROAD_F1, 20, 20
	mapgroup VICTORY_ROAD_F2, 20, 26
	mapgroup VICTORY_ROAD_F3, 24, 20
	mapgroup VICTORY_ROAD_EAST, 20, 12
	mapgroup VICTORY_ROAD_MYSTERY_ROOM, 5, 5
	mapgroup VICTORY_ROAD_EXIT_ROOM, 18, 15
	mapgroup PIRATES_COVE_1F, 10, 20
	mapgroup PIRATES_COVE_2F, 10, 20
	mapgroup PIRATES_COVE_UNDERWATER, 10, 20
	

	newgroup ; 3

	mapgroup ROUTE_57, 22, 12
	mapgroup KINNOW_ISLAND_ROUTE_57_GATE, 4, 5
	mapgroup ROUTE_57_GATE_UPSTAIRS, 4, 5
	mapgroup UNNAMED_ISLAND_1, 12, 12
	mapgroup UNNAMED_ISLAND_1_POKE_CENTER, 4, 5
	mapgroup ROUTE_58, 10, 18
	mapgroup NAVEL_ISLAND, 18, 18
	mapgroup DANNYS_HOUSE, 4, 4
	mapgroup SEVEN_GRAPEFRUITS, 22, 40
	mapgroup SEVEN_GRAPEFRUITS_UNDERWATER, 20, 21
	mapgroup ROUTE_59, 18, 12
	mapgroup GRAPEFRUIT_STORE, 3, 4
	mapgroup MORO_ISLAND, 18, 18
	mapgroup MORO_ISLAND_MUSEUM, 8, 7
	mapgroup MORO_FISHING_HOUSE, 4, 4
	mapgroup MORO_SOUTH_HOUSE, 4, 4
	mapgroup MORO_HOUSE_1, 4, 4
	mapgroup MORO_HOUSE_2, 4, 4
	mapgroup MORO_POKE_CENTER, 4, 5
	mapgroup MORO_MART, 4, 6
	mapgroup CLEOPATRA_ISLAND, 20, 20
	mapgroup ROUTE_57_NORTH, 20, 12
	mapgroup ROUTE_63_EAST_WEST, 12, 40
	mapgroup ROUTE_63_NORTH_SOUTH, 35, 12

	newgroup ; 4

	mapgroup ROUTE_55, 25, 25
	mapgroup ROUTE_55_UNDERWATER, 25, 25
	mapgroup PINKAN_ISLAND, 17, 21
	mapgroup ROUTE_56_WEST, 17, 35
	mapgroup ROUTE_56_EAST, 17, 35
	mapgroup ROUTE_55_QUEST_HOUSE, 4, 4
	mapgroup ROUTE_56_POKE_CENTER, 4, 5
	mapgroup KINNOW_ISLAND, 18, 20
	mapgroup KINNOW_TRADE_HOUSE, 4, 4
	mapgroup KINNOW_LORE_HOUSE, 4, 4
	mapgroup KINNOW_CHARCOAL_HOUSE, 4, 4
	mapgroup KINNOW_POKE_CENTER, 4, 5
	mapgroup KINNOW_MART, 4, 6
	mapgroup KINNOW_CAFE, 5, 5
	mapgroup KINNOW_SKATE_SHOP, 4, 5
	mapgroup KINNOW_SHOWBOAT, 10, 11
	mapgroup KINNOW_SHOWBOAT_GATE, 4, 5
	mapgroup KINNOW_SHOWBOAT_HOUSE, 4, 4
	mapgroup KINNOW_SHOWBOAT_INSIDE, 13, 19

	newgroup ; 5

	mapgroup ROUTE_52_TANGELO_JUNGLE_GATE, 4, 5
	mapgroup ROUTE_52, 40, 11
	mapgroup MIKAN_ISLAND, 18, 17
	mapgroup MIKAN_MART, 4, 6
	mapgroup MIKAN_GYM, 9, 5
	mapgroup MIKAN_NICKNAME_SPEECH_HOUSE, 4, 4
	mapgroup MIKAN_POKECENTER_1F, 4, 5
	mapgroup MIKAN_ONIX_TRADE_HOUSE, 4, 4
	mapgroup MIKAN_ISLAND_ROUTE_53_GATE, 4, 5
	mapgroup ROUTE_53_GATE_UPSTAIRS, 4, 5
	mapgroup ROUTE_52_POKECENTER_1F, 4, 5

	newgroup ; 6

	mapgroup MORO_ROUTE_60_GATE, 4, 5
	mapgroup ROUTE_60_GATE_UPSTAIRS, 4, 5
	mapgroup WRECKED_SHIP, 12, 20
	mapgroup WRECKED_SHIP_UNDERWATER, 12, 18
	mapgroup WRECKED_SHIP_UNSUNK, 12, 18
	mapgroup ROUTE_61, 30, 28
	mapgroup MURCOTT_ISLAND, 16, 23
	mapgroup DAYCARE, 4, 6
	mapgroup MURCOTT_HOUSE_1, 4, 4
	mapgroup MURCOTT_HOUSE_2, 4, 4
	mapgroup MURCOTT_HOUSE_3, 4, 4
	mapgroup MURCOTT_POKE_CENTER, 4, 5
	mapgroup MURCOTT_POKE_MART, 4, 6
	mapgroup UNNAMED_ISLAND_2, 20, 17
	mapgroup FISHING_CONTEST, 20, 12
	mapgroup ROUTE_62, 20, 37
	mapgroup ROUTE_62_MANDARIN_DESERT_GATE, 4, 5

	newgroup ; 7

	mapgroup PALLET_TOWN, 16, 17
	mapgroup REDS_HOUSE_1F, 4, 4
	mapgroup REDS_HOUSE_2F, 4, 4
	mapgroup BLUES_HOUSE, 4, 4
	mapgroup OAKS_LAB, 6, 5
	mapgroup VERMILION_CITY, 20, 24
	mapgroup SAFARI_ZONE, 20, 45
	mapgroup FUCHSIA_CITY, 20, 22
	mapgroup ROUTE_15, 6, 22
	mapgroup ROUTE_14, 27, 10
	mapgroup ROUTE_13, 9, 30
	mapgroup ROUTE_12, 26, 12
	mapgroup ROUTE_11, 11, 22
	mapgroup CYBER_SPACE, 10, 10
	mapgroup CINNABAR_ISLAND, 20, 26

	newgroup ; 8

	mapgroup VALENCIA_PORT, 12, 12
	mapgroup TANGELO_PORT, 12, 12
	mapgroup TROVITOPOLIS, 24, 36
	mapgroup TROVITOPOLIS_DEPT_STORE_1F, 4, 8
	mapgroup TROVITOPOLIS_DEPT_STORE_2F, 4,  8 ; 12
	mapgroup TROVITOPOLIS_DEPT_STORE_3F, 4,  8 ; 13
	mapgroup TROVITOPOLIS_DEPT_STORE_4F, 4,  8 ; 14
	mapgroup TROVITOPOLIS_DEPT_STORE_5F, 4,  8 ; 15
	mapgroup TROVITOPOLIS_DEPT_STORE_6F, 4, 8
	mapgroup TROVITOPOLIS_DEPT_STORE_ELEVATOR, 2,  2 ; 17
	mapgroup TROVITOPOLIS_DEPT_STORE_ROOF, 4, 6
	mapgroup TROVITOPOLIS_POKE_COMM_CENTER, 11, 11
	mapgroup TROVITOPOLIS_MR_FLASH_HOUSE, 4, 4
	mapgroup TROVITOPOLIS_MOVE_DELETER_HOUSE, 4, 4
	mapgroup TROVITOPOLIS_HOUSE_1, 4, 4
	mapgroup TROVITOPOLIS_HOUSE_2, 4, 4
	mapgroup TROVITOPOLIS_HOUSE_3, 4, 4
	mapgroup TROVITOPOLIS_HOUSE_4, 4, 4
	mapgroup TROVITOPOLIS_PORT, 12, 12
	mapgroup MAYORS_OFFICE, 5, 10
	mapgroup MAYORS_OFFICE_MEETING_ROOM, 5, 10
	mapgroup TROVITA_PORT, 12, 12
	mapgroup TROVITA_GYM, 7, 5
	mapgroup TROVITOPOLIS_PRIMA_SCHOOL, 4, 6

	newgroup ; 9

	mapgroup ASCORBIA_ISLAND, 20, 20
	mapgroup ASCORBIA_ISLAND_FAN_CLUB, 5, 10
	mapgroup ASCORBIA_ISLAND_MOVE_RELEARNER, 4, 4
	mapgroup ASCORBIA_ISLAND_HOUSE_1, 4, 4
	mapgroup ASCORBIA_ISLAND_HOUSE_2, 4, 4
	mapgroup ASCORBIA_ISLAND_ROUTE_63_GATE, 4, 5
	mapgroup ASCORBIA_ISLAND_MART, 4, 6
	mapgroup ASCORBIA_ISLAND_CENTER, 4, 5
	mapgroup ROUTE_64, 14, 20
	mapgroup ROUTE_65, 14, 22
	mapgroup BUTWAL_ISLAND_EAST, 22, 12
	mapgroup HEART_SCALE_COVE, 13, 16
	mapgroup BUTWAL_ISLAND_UNDERWATER_EAST, 12, 8
	mapgroup BUTWAL_ISLAND_UNDERWATER_WEST, 12, 10

	newgroup ; 10

	mapgroup POKECENTER_2F, 3, 6
	mapgroup TRADE_CENTER, 4, 5
	mapgroup COLOSSEUM, 4, 5

	newgroup ; 11

	mapgroup ROUTE_49, 18, 20
	mapgroup VALENCIA_ISLAND, 14, 22
	mapgroup IVYS_LAB, 6, 5
	mapgroup KRISS_HOUSE_1F, 4, 5
	mapgroup KRISS_HOUSE_2F, 3, 4
	mapgroup KRISS_NEIGHBORS_HOUSE, 4, 4
	mapgroup IVYS_HOUSE, 4, 3
	mapgroup VALENCIA_TANGELO_ROUTE_49, 27, 16

	newgroup ; 12

	mapgroup ROUTE_50, 27, 11
	mapgroup ROUTE_51, 20, 20
	mapgroup ROUTE_51_TANGELO_JUNGLE_GATE, 4, 5
	mapgroup ROUTE_51_GATE_UPSTAIRS, 4, 5
	mapgroup TANGELO_ISLAND, 15, 20
	mapgroup TANGELO_MART, 4, 6
	mapgroup TANGELO_POKECENTER_1F, 4, 5
	mapgroup TANGELO_GYM_SPEECH_HOUSE, 4, 4
	mapgroup TANGELO_EVOLUTION_SPEECH_HOUSE, 4, 4

	newgroup ; 13

	mapgroup SUNBURST_ISLAND, 24, 20
	mapgroup SUNBURST_POKECENTER, 4, 5
	mapgroup SUNBURST_SMALL_HOUSE, 4, 4
	mapgroup SUNBURST_LARGE_HOUSE, 4, 4
	mapgroup SUNBURST_SOUTH_HOUSE, 4, 4
	mapgroup SUNBURST_CRYSTAL_SHOP, 3, 4

	newgroup ; 14

	mapgroup GOLDEN_ISLAND, 16, 14
	mapgroup GOLDEN_ISLAND_HOUSE_1, 4, 4
	mapgroup GOLDEN_ISLAND_HOUSE_2, 4, 4
	mapgroup GOLDEN_ISLAND_HOUSE_3, 4, 4
	mapgroup GOLDEN_ISLAND_ELDER_HOUSE, 4, 4
	mapgroup GOLDEN_ISLAND_GATE_HOUSE, 10, 4

	newgroup ; 15
	
	mapgroup ROUTE_69_GATE, 4, 5
	mapgroup ROUTE_69_NORTH, 16, 14
	mapgroup PUMMELO_ISLAND, 25, 27
	mapgroup HALL_OF_FAME, 6, 7
	mapgroup PUMMELO_STADIUM, 10, 7
	mapgroup PUMMELO_ISLAND_HOUSE_1, 4, 4
	mapgroup PUMMELO_ISLAND_HOUSE_2, 4, 4
	mapgroup PUMMELO_ISLAND_HOUSE_3, 4, 4
	mapgroup PUMMELO_ISLAND_HOUSE_4, 4, 4
	mapgroup PUMMELO_ISLAND_HOUSE_5, 4, 4
	mapgroup PUMMELO_ISLAND_HOUSE_6, 4, 4
	mapgroup PUMMELO_CENTER, 4, 5
	mapgroup PUMMELO_MART, 4, 6	
	mapgroup PUMMELO_ROUTE_70_GATE, 4, 5
	mapgroup ROUTE_70_GATE_UPSTAIRS, 4, 5


	newgroup ; 16
	
	mapgroup KUMQUAT_ISLAND_EAST, 16, 15
	mapgroup KUMQUAT_ISLAND_WEST, 16, 15
	mapgroup BUTWAL_ISLAND_WEST, 22, 18
	mapgroup BUTWAL_ISLAND_WEST_GROTTO, 3, 3
	mapgroup ROUTE_66_EAST_WEST, 12, 24
	mapgroup ROUTE_66_NORTH_SOUTH, 18, 12
	mapgroup KUMQUAT_HOTEL_LOBBY, 5, 6
	mapgroup KUMQUAT_HOTEL_POOL, 8, 7
	mapgroup KUMQUAT_HOTEL_ELEVATOR, 2, 2
	mapgroup KUMQUAT_HOTEL_SUITES, 3, 8
	mapgroup KUMQUAT_HOTEL_BOTTOM_ROOM_2, 3, 3
	mapgroup KUMQUAT_HOTEL_BOTTOM_ROOM_3, 3, 3
	mapgroup KUMQUAT_HOTEL_TOP_ROOM_2, 3, 3
	mapgroup KUMQUAT_HOTEL_TOP_ROOM_3, 3, 3
	mapgroup KUMQUAT_HOTEL_GYM, 4, 4
	mapgroup KUMQUAT_HOUSE_1, 4, 4
	mapgroup KUMQUAT_HOUSE_2, 4, 4
	mapgroup KUMQUAT_HOUSE_3, 4, 4
	mapgroup KUMQUAT_HOUSE_4, 4, 4
	mapgroup KUMQUAT_MART, 4, 6
	mapgroup KUMQUAT_CENTER, 4, 5
	mapgroup GAME_CORNER, 6, 7
	mapgroup ROUTE_67, 15, 30
	mapgroup RIND_ISLAND, 22, 24
	mapgroup ROUTE_68, 10, 14
	mapgroup UNNAMED_ISLAND_3, 20, 20
	mapgroup ROUTE_69_SOUTH, 41, 20
	mapgroup ROUTE_67_UNDERWATER, 15, 30
	mapgroup QUACKENPOKER_LAB, 6, 5
	mapgroup UNNAMED_ISLAND_3_HOUSE, 3, 4

	newgroup ; 17

	mapgroup HAMLIN_ISLAND, 30, 20
	mapgroup HAMLIN_BRIDGE, 30, 9
	mapgroup ROUTE_70, 14, 24
	mapgroup TARROCO_ISLAND, 20, 30
	mapgroup ROUTE_71, 20, 36
	mapgroup ROUTE_71_EAST, 20, 20
	mapgroup PONCHOS_HOUSE, 3, 3
	mapgroup HAMLIN_ROUTE_71_GATE, 4, 5
	mapgroup HAMLIN_BRIDGE_GATE, 4, 5
	mapgroup ROUTE_71_UNDERWATER, 9, 23
	
	
	newgroup ; 18

	mapgroup SHAMOUTI_ISLAND, 15, 18
	mapgroup SHAMOUTI_SHRINE, 13, 12
	mapgroup SHAMOUTI_NORTH_BEACH, 16, 14
	mapgroup SHAMOUTI_BAY, 20, 30
	mapgroup LIGHTNING_ISLAND, 20, 30
	mapgroup ICE_ISLAND, 20, 28
	mapgroup FIRE_ISLAND, 24, 20
	mapgroup AIRSHIP_INTERIOR, 8, 10
	mapgroup CHIEFS_HOUSE, 4, 6
	mapgroup SHAMOUTI_MART, 4, 6
	mapgroup SHAMOUTI_CENTER, 4, 5
	mapgroup SHAMOUTI_HOUSE, 4, 4
	mapgroup SHAMOUTI_BAY_HOUSE, 4, 4
	mapgroup AIRSHIP_OUTSIDE, 32, 14
	mapgroup AIRSHIP_CUTSCENE, 12, 6
	mapgroup SHAMOUTI_CAVE, 14, 8
	mapgroup LIGHTNING_ISLAND_CAVE, 4, 10
	
; elevator floors

	const_def
	const _B4F
	const _B3F
	const _B2F
	const _B1F
	const _1F
	const _2F
	const _3F
	const _4F
	const _5F
	const _6F
	const _7F
	const _8F
	const _9F
	const _10F
	const _11F
	const _ROOF

; connection directions
	const_def
	const EAST_F
	const WEST_F
	const SOUTH_F
	const NORTH_F

	const_def
	shift_const EAST
	shift_const WEST
	shift_const SOUTH
	shift_const NORTH

; permissions
const_value = 1
	const TOWN
	const ROUTE
	const INDOOR
	const CAVE
	const PERM_5
	const GATE
	const DUNGEON

; object struct
	const_def
	const OBJECT_SPRITE ; 00
	const OBJECT_MAP_OBJECT_INDEX ; 01
	const OBJECT_SPRITE_TILE ; 02
	const OBJECT_MOVEMENTTYPE ; 03
	const OBJECT_FLAGS1 ; 04
	const OBJECT_FLAGS2 ; 05
	const OBJECT_PALETTE ; 06
	const OBJECT_DIRECTION_WALKING ; 07
	const OBJECT_FACING ; 08
	const OBJECT_STEP_TYPE ; 09
	const OBJECT_STEP_DURATION ; 0a
	const OBJECT_ACTION ; 0b
	const OBJECT_STEP_FRAME ; 0c
	const OBJECT_FACING_STEP ; 0d
	const OBJECT_NEXT_TILE ; 0e
	const OBJECT_STANDING_TILE ; 0f
	const OBJECT_NEXT_MAP_X ; 10
	const OBJECT_NEXT_MAP_Y ; 11
	const OBJECT_MAP_X ; 12
	const OBJECT_MAP_Y ; 13
	const OBJECT_INIT_X ; 14
	const OBJECT_INIT_Y ; 15
	const OBJECT_RADIUS ; 16
	const OBJECT_SPRITE_X ; 17
	const OBJECT_SPRITE_Y ; 18
	const OBJECT_SPRITE_X_OFFSET ; 19
	const OBJECT_SPRITE_Y_OFFSET ; 1a
	const OBJECT_MOVEMENT_BYTE_INDEX ; 1b
	const OBJECT_28 ; 1c
	const OBJECT_29 ; 1d
	const OBJECT_30 ; 1e
	const OBJECT_31 ; 1f
	const OBJECT_RANGE ; 20

; map object struct
	const_def
	const MAPOBJECT_OBJECT_STRUCT_ID ; 0
	const MAPOBJECT_SPRITE ; 1
	const MAPOBJECT_Y_COORD ; 2
	const MAPOBJECT_X_COORD ; 3
	const MAPOBJECT_MOVEMENT ; 4
	const MAPOBJECT_RADIUS ; 5
	const MAPOBJECT_HOUR ; 6
	const MAPOBJECT_TIMEOFDAY ; 7
	const MAPOBJECT_COLOR ; 8
	const MAPOBJECT_RANGE ; 9
	const MAPOBJECT_SCRIPT_POINTER ; a
	const MAPOBJECT_POINTER_HI ; b
	const MAPOBJECT_EVENT_FLAG ; c
	const MAPOBJECT_FLAG_HI ; d
OBJECT_LENGTH EQU const_value

MAPOBJECT_SCREEN_HEIGHT EQU 11
MAPOBJECT_SCREEN_WIDTH EQU 12

OW_DOWN EQU DOWN << 2
OW_UP EQU UP << 2
OW_LEFT EQU LEFT << 2
OW_RIGHT EQU RIGHT << 2

	const_def
	const EMOTE_SHOCK
	const EMOTE_QUESTION
	const EMOTE_HAPPY
	const EMOTE_SAD
	const EMOTE_HEART
	const EMOTE_BOLT
	const EMOTE_SLEEP
	const EMOTE_FISH
	const EMOTE_SHADOW
	const EMOTE_ROD
	const EMOTE_BOULDER_DUST
	const EMOTE_0B
	const EMOTE_PUDDLE_SPLASH
EMOTE_MEM EQU -1

	const_def
	const SIGNPOST_READ
	const SIGNPOST_UP
	const SIGNPOST_DOWN
	const SIGNPOST_RIGHT
	const SIGNPOST_LEFT
	const SIGNPOST_IFSET
	const SIGNPOST_IFNOTSET
	const SIGNPOST_ITEM
	const SIGNPOST_COPY

; I'm relocating spawn constants here, so that they can be used anywhere in the disassembly.

const_value = -1
	const SPAWN_N_A
	const SPAWN_HOME
	const SPAWN_VALENCIA
	const SPAWN_TANGELO
	const SPAWN_MIKAN
	const SPAWN_ROUTE_52
	const SPAWN_MANDARIN_NORTH
	const SPAWN_SUNBURST
	const SPAWN_ROUTE_56_WEST
	const SPAWN_KINNOW
	const SPAWN_NAVEL
	const SPAWN_MORO
	const SPAWN_MURCOTT
	const SPAWN_TROVITOPOLIS
	const SPAWN_TROVITA
	const SPAWN_ASCORBIA
	const SPAWN_KUMQUAT
	const SPAWN_PUMMELO
	const SPAWN_TARROCO
	const SPAWN_SHAMOUTI
	const SPAWN_VERMILION
NUM_SPAWNS EQU const_value

	const_def
	const PALETTE_AUTO
	const PALETTE_DAY
	const PALETTE_NITE
	const PALETTE_MORN
	const PALETTE_DARK

INVISIBLE EQU 0
FIXED_FACING EQU 2
SLIDING EQU 3
EMOTE_OBJECT EQU 7

	const_def
	const PERSONTYPE_SCRIPT
	const PERSONTYPE_ITEMBALL
	const PERSONTYPE_TRAINER
	const PERSONTYPE_3
	const PERSONTYPE_4
	const PERSONTYPE_5
	const PERSONTYPE_6

; fruit trees
const_value = 1
	const FRUITTREE_ROUTE_49
	const FRUITTREE_ROUTE_50_1
	const FRUITTREE_ROUTE_50_2
	const FRUITTREE_ROUTE_51
	const FRUITTREE_ROUTE_53
	const FRUITTREE_MIKAN_ISLAND
	const FRUITTREE_PINKAN_ISLAND_1
	const FRUITTREE_PINKAN_ISLAND_2
	const FRUITTREE_PINKAN_ISLAND_3
	const FRUITTREE_PINKAN_ISLAND_4
	const FRUITTREE_GOLDEN_ISLAND
	const FRUITTREE_MURCOTT_ISLAND
	const FRUITTREE_ASCORBIA_ISLAND
	const FRUITTREE_ROUTE_64
	const FRUITTREE_BUTWAL_WEST
	const FRUITTREE_ROUTE_66
	const FRUITTREE_RIND_ISLAND_1
	const FRUITTREE_RIND_ISLAND_2
	const FRUITTREE_PUMMELO_ISLAND_1
	const FRUITTREE_PUMMELO_ISLAND_2

NUM_FRUIT_TREES EQU const_value +- 1

CMDQUEUE_TYPE EQU 0
CMDQUEUE_ADDR EQU 1
CMDQUEUE_03 EQU 3
CMDQUEUE_04 EQU 4
CMDQUEUE_05 EQU 5
CMDQUEUE_ENTRY_SIZE EQU 6
CMDQUEUE_CAPACITY EQU 4

CMDQUEUE_STONETABLE EQU 2
