
	const_def
	const NO_MOVE      ; $00
	const SHADOW_CLAW  ; $01
	const KARATE_CHOP  ; $02
	const DOUBLESLAP   ; $03
	const COMET_PUNCH  ; $04
	const POISON_JAB   ; $05
	const PAY_DAY      ; $06
	const FIRE_PUNCH   ; $07
	const ICE_PUNCH    ; $08
	const THUNDERPUNCH ; $09
	const SCRATCH      ; $0a
	const BULLET_SEED  ; $0b
	const GUILLOTINE   ; $0c
	const DRAGON_PULSE ; $0d
	const SWORDS_DANCE ; $0e
	const CUT          ; $0f
	const GUST         ; $10
	const WING_ATTACK  ; $11
	const WHIRLWIND    ; $12
	const FLY          ; $13
	const DARK_PULSE   ; $14
	const SLAM         ; $15
	const VINE_WHIP    ; $16
	const STOMP        ; $17
	const DOUBLE_KICK  ; $18
	const ZEN_HEADBUTT ; $19
	const GIGA_IMPACT  ; $1a
	const FLASH_CANNON ; $1b
	const SAND_ATTACK  ; $1c
	const HEADBUTT     ; $1d
	const HORN_ATTACK  ; $1e
	const FURY_ATTACK  ; $1f
	const HORN_DRILL   ; $20
	const TACKLE       ; $21
	const BODY_SLAM    ; $22
	const WRAP         ; $23
	const TAKE_DOWN    ; $24
	const THRASH       ; $25
	const DOUBLE_EDGE  ; $26
	const TAIL_WHIP    ; $27
	const POISON_STING ; $28
	const TWINEEDLE    ; $29
	const PIN_MISSILE  ; $2a
	const LEER         ; $2b
	const BITE         ; $2c
	const GROWL        ; $2d
	const ROAR         ; $2e
	const SING         ; $2f
	const SUPERSONIC   ; $30
	const SONICBOOM    ; $31
	const DISABLE      ; $32
	const ACID         ; $33
	const EMBER        ; $34
	const FLAMETHROWER ; $35
	const MIST         ; $36
	const WATER_GUN    ; $37
	const HYDRO_PUMP   ; $38
	const SURF         ; $39
	const ICE_BEAM     ; $3a
	const BLIZZARD     ; $3b
	const PSYBEAM      ; $3c
	const BUBBLEBEAM   ; $3d
	const AURORA_BEAM  ; $3e
	const HYPER_BEAM   ; $3f
	const PECK         ; $40
	const DRILL_PECK   ; $41
	const SUBMISSION   ; $42
	const LOW_KICK     ; $43
	const COUNTER      ; $44
	const SEISMIC_TOSS ; $45
	const STRENGTH     ; $46
	const ABSORB       ; $47
	const PLAY_ROUGH   ; $48
	const LEECH_SEED   ; $49
	const GROWTH       ; $4a
	const RAZOR_LEAF   ; $4b
	const SOLARBEAM    ; $4c
	const POISONPOWDER ; $4d
	const STUN_SPORE   ; $4e
	const SLEEP_POWDER ; $4f
	const PETAL_DANCE  ; $50
	const STRING_SHOT  ; $51
	const DRAGON_RAGE  ; $52
	const FIRE_SPIN    ; $53
	const THUNDERSHOCK ; $54
	const THUNDERBOLT  ; $55
	const THUNDER_WAVE ; $56
	const THUNDER      ; $57
	const ROCK_THROW   ; $58
	const EARTHQUAKE   ; $59
	const FISSURE      ; $5a
	const DIG          ; $5b
	const TOXIC        ; $5c
	const CONFUSION    ; $5d
	const PSYCHIC_M    ; $5e
	const HYPNOSIS     ; $5f
	const POWER_GEM    ; $60
	const AGILITY      ; $61
	const QUICK_ATTACK ; $62
	const RAGE         ; $63
	const TELEPORT     ; $64
	const NIGHT_SHADE  ; $65
	const MIMIC        ; $66
	const SCREECH      ; $67
	const DOUBLE_TEAM  ; $68
	const RECOVER      ; $69
	const HARDEN       ; $6a
	const MINIMIZE     ; $6b
	const SMOKESCREEN  ; $6c
	const CONFUSE_RAY  ; $6d
	const WITHDRAW     ; $6e
	const DEFENSE_CURL ; $6f
	const BARRIER      ; $70
	const LIGHT_SCREEN ; $71
	const HAZE         ; $72
	const REFLECT      ; $73
	const FOCUS_ENERGY ; $74
	const ROCK_BLAST   ; $75
	const METRONOME    ; $76
	const MIRROR_MOVE  ; $77
	const SELFDESTRUCT ; $78
	const EGG_BOMB     ; $79
	const LICK         ; $7a
	const SMOG         ; $7b
	const SLUDGE       ; $7c
	const SHADOW_BONE  ; $7d
	const FIRE_BLAST   ; $7e
	const WATERFALL    ; $7f
	const CLAMP        ; $80
	const SWIFT        ; $81
	const SIGNAL_BEAM  ; $82
	const SPIKE_CANNON ; $83
	const ACCELEROCK   ; $84
	const AMNESIA      ; $85
	const DIVE         ; $86
	const SOFTBOILED   ; $87
	const HI_JUMP_KICK ; $88
	const GLARE        ; $89
	const DREAM_EATER  ; $8a
	const POISON_GAS   ; $8b
	const BARRAGE      ; $8c
	const LEECH_LIFE   ; $8d
	const SKETCH       ; $8e
	const SKY_ATTACK   ; $8f
	const TRANSFORM    ; $90
	const BUBBLE       ; $91
	const DIZZY_PUNCH  ; $92
	const SPORE        ; $93
	const FLASH        ; $94
	const MIST_BALL    ; $95
	const SPLASH       ; $96
	const ACID_ARMOR   ; $97
	const CRABHAMMER   ; $98
	const EXPLOSION    ; $99
	const FURY_SWIPES  ; $9a
	const BONEMERANG   ; $9b
	const REST         ; $9c
	const ROCK_SLIDE   ; $9d
	const HYPER_FANG   ; $9e
	const FACADE       ; $9f
	const CONVERSION   ; $a0
	const TRI_ATTACK   ; $a1
	const SUPER_FANG   ; $a2
	const SLASH        ; $a3
	const SUBSTITUTE   ; $a4
	const STRUGGLE     ; $a5
	const ROCK_CLIMB   ; $a6
	const TRIPLE_KICK  ; $a7
	const THIEF        ; $a8
	const SHELL_TRAP   ; $a9
	const LUSTER_PURGE ; $aa
	const VENOSHOCK    ; $ab
	const FLAME_WHEEL  ; $ac
	const EARTH_POWER  ; $ad
	const CURSE        ; $ae
	const FLAIL        ; $af
	const CONVERSION2  ; $b0
	const AEROBLAST    ; $b1
	const COTTON_SPORE ; $b2
	const REVERSAL     ; $b3
	const NASTY_PLOT   ; $b4
	const HAIL         ; $b5
	const PROTECT      ; $b6
	const MACH_PUNCH   ; $b7
	const SCARY_FACE   ; $b8
	const FAINT_ATTACK ; $b9
	const SWEET_KISS   ; $ba
	const BELLY_DRUM   ; $bb
	const SLUDGE_BOMB  ; $bc
	const MUD_SLAP     ; $bd
	const OCTAZOOKA    ; $be
	const SPIKES       ; $bf
	const ZAP_CANNON   ; $c0
	const FORESIGHT    ; $c1
	const DESTINY_BOND ; $c2
	const PERISH_SONG  ; $c3
	const ICY_WIND     ; $c4
	const POWERUPPUNCH ; $c5
	const BONE_RUSH    ; $c6
	const LOCK_ON      ; $c7
	const OUTRAGE      ; $c8
	const SANDSTORM    ; $c9
	const GIGA_DRAIN   ; $ca
	const ENDURE       ; $cb
	const CHARM        ; $cc
	const ROLLOUT      ; $cd
	const FALSE_SWIPE  ; $ce
	const SWAGGER      ; $cf
	const WATER_PULSE  ; $d0
	const SPARK        ; $d1
	const BUG_BITE     ; $d2
	const STEEL_WING   ; $d3
	const MEAN_LOOK    ; $d4
	const ATTRACT      ; $d5
	const SLEEP_TALK   ; $d6
	const HEAL_BELL    ; $d7
	const RETURN       ; $d8
	const ASTONISH     ; $d9
	const FRUSTRATION  ; $da
	const SAFEGUARD    ; $db
	const SPECTRATHIEF ; $dc
	const SACRED_FIRE  ; $dd
	const MAGNITUDE    ; $de
	const DYNAMICPUNCH ; $df
	const WOOD_HAMMER  ; $e0
	const DRAGONBREATH ; $e1
	const BATON_PASS   ; $e2
	const ENCORE       ; $e3
	const PURSUIT      ; $e4
	const RAPID_SPIN   ; $e5
	const SWEET_SCENT  ; $e6
	const IRON_TAIL    ; $e7
	const METAL_CLAW   ; $e8
	const VITAL_THROW  ; $e9
	const MORNING_SUN  ; $ea
	const SYNTHESIS    ; $eb
	const MOONLIGHT    ; $ec
	const VOLT_TACKLE  ; $ed
	const CROSS_CHOP   ; $ee
	const DRAGON_TAIL  ; $ef
	const RAIN_DANCE   ; $f0
	const SUNNY_DAY    ; $f1
	const CRUNCH       ; $f2
	const MIRROR_COAT  ; $f3
	const AERIAL_ACE   ; $f4
	const EXTREMESPEED ; $f5
	const ANCIENTPOWER ; $f6
	const SHADOW_BALL  ; $f7
	const FUTURE_SIGHT ; $f8
	const ROCK_SMASH   ; $f9
	const WHIRLPOOL    ; $fa
	const PSYSTRIKE    ; $fb
	const MOONBLAST    ; $fc
	const FAIRY_WIND   ; $fd
	const DAZZLINGLEAM ; $fe
	const SHADOW_SNEAK ; $ff

; Battle animations use the same constants
; as the moves up to this point.
	const ANIM_SWEET_SCENT_2     ; $100
	const ANIM_THROW_POKE_BALL   ; $101
	const ANIM_SEND_OUT_MON      ; $102
	const ANIM_RETURN_MON        ; $103
	const ANIM_CONFUSED          ; $104
	const ANIM_SLP               ; $105
	const ANIM_BRN               ; $106
	const ANIM_PSN               ; $107
	const ANIM_SAP               ; $108
	const ANIM_FRZ               ; $109
	const ANIM_PAR               ; $10a
	const ANIM_IN_LOVE           ; $10b
	const ANIM_IN_SANDSTORM      ; $10c
	const ANIM_HURT_BY_CURSE     ; $10d
	const ANIM_IN_WHIRLPOOL      ; $10e
; battle anims
	const ANIM_MISS              ; $10f
	const ANIM_ENEMY_DAMAGE      ; $110
	const ANIM_ENEMY_STAT_DOWN   ; $111
	const ANIM_PLAYER_STAT_DOWN  ; $112
	const ANIM_PLAYER_DAMAGE     ; $113
	const ANIM_WOBBLE            ; $114
	const ANIM_SHAKE             ; $115
	const ANIM_HIT_CONFUSION     ; $116
	const ANIM_IN_HAIL           ; $117
	const ANIM_STEAL_BOOSTS      ; $118

; wNumHits uses offsets from ANIM_MISS
	const_def
	const BATTLEANIM_NONE
	const BATTLEANIM_ENEMY_DAMAGE
	const BATTLEANIM_ENEMY_STAT_DOWN
	const BATTLEANIM_PLAYER_STAT_DOWN
	const BATTLEANIM_PLAYER_DAMAGE
	const BATTLEANIM_WOBBLE
	const BATTLEANIM_SHAKE
	const BATTLEANIM_HIT_CONFUSION
