	enum_start
	enum pokecenternurse
	enum difficultbookshelf
	enum picturebookshelf
	enum magazinebookshelf
	enum incenseburner
	enum merchandiseshelf
	enum townmap
	enum window
	enum tv
	enum radio
	enum trashcan
	enum strengthboulder
	enum smashrock
	enum pokecentersign
	enum martsign
	enum elevatorbutton
	enum daytotext
	enum bugcontestresultswarp
	enum bugcontestresults
	enum initializeevents
	enum gymstatue1
	enum gymstatue2
	enum receiveitem
	enum pcscript
	enum gamecornercoinvendor
	enum happinesschecknpc
