	enum_start
	enum pokecenternurse
	enum difficultbookshelf
	enum picturebookshelf
	enum magazinebookshelf
	enum teamrocketoath
	enum incenseburner
	enum merchandiseshelf
	enum townmap
	enum window
	enum tv
	enum homepage
	enum radio1
	enum radio2
	enum trashcan
	enum strengthboulder
	enum smashrock
	enum pokecentersign
	enum martsign
	enum goldenrodrockets
	enum radiotowerrockets
	enum elevatorbutton
	enum daytotext
	enum bugcontestresultswarp
	enum bugcontestresults
	enum initializeevents
	enum gymstatue1
	enum gymstatue2
	enum receiveitem
	enum receivetogepiegg
	enum pcscript
	enum gamecornercoinvendor
	enum happinesschecknpc
