	const_def
	const NORMAL
	const FIGHTING
	const FLYING
	const POISON
	const GROUND
	const ROCK
	const BUG
	const DARK
	const STEEL
	const CRYSTAL
	const FIRE
	const WATER
	const GRASS
	const ELECTRIC
	const PSYCHIC
	const ICE
	const DRAGON
	const GHOST
	const FAIRY
TYPES_END EQU const_value

if DEF(PSS)

PHYSICAL EQU %01000000
SPECIAL  EQU %10000000 ; SPECIAL > PHYSICAL
STATUS   EQU %11000000

TYPE_MASK     EQU %00011111
CATEGORY_MASK EQU %11000000

else

PHYSICAL EQU NORMAL ; first physical type
SPECIAL  EQU FIRE ; first special type
STATUS   EQU TYPES_END

TYPE_MASK     EQU %00011111
CATEGORY_MASK EQU TYPE_MASK

endc
