; Each trainer class has its own group. See trainers.asm.

TrainerGroups: ; 0x39999
	dw CissyGroup
	dw DannyGroup
	dw RudyGroup
	dw LuanaGroup
	dw DrakeGroup
	dw TraceyGroup
	dw BrockGroup
	dw MistyGroup
	dw LtSurgeGroup
	dw ErikaGroup
	dw KogaGroup
	dw SabrinaGroup
	dw BlaineGroup
	dw GiovanniGroup
	dw LoreleiGroup
	dw BrunoGroup
	dw AgathaGroup
	dw LanceGroup
	dw RedGroup
	dw BlueGroup
	dw GreenGroup
	dw YellowGroup
	dw CalGroup
	dw ButchGroup
	dw CassidyGroup
	dw CassidyButchGroup
	dw JamesGroup
	dw JessieGroup
	dw JessieJamesGroup
	dw MomGroup
	dw BillGroup
	dw ImakuniGroup
	dw LawrenceGroup
	dw ProfOakGroup
	dw ProfIvyGroup
	dw ProfAideGroup
	dw NurseGroup
	dw OfficerGroup
	dw YoungsterGroup
	dw LassGroup
	dw BeautyGroup
	dw BugCatcherGroup
	dw BugCatcherFGroup
	dw SwimmerMGroup
	dw SwimmerFGroup
	dw CamperGroup
	dw PokemaniacGroup
	dw FisherGroup
	dw HikerGroup
	dw AthleteGroup
	dw SightseerMGroup
	dw SightseerFGroup
	dw SchoolboyGroup
	dw BirdKeeperGroup
	dw CooltrainerMGroup
	dw CooltrainerFGroup
	dw GentlemanGroup
	dw TeacherGroup
	dw SailorGroup
	dw SuperNerdGroup
	dw GuitaristGroup
	dw BikerGroup
	dw FirebreatherGroup
	dw JugglerGroup
	dw BlackbeltGroup
	dw PsychicGroup
	dw PicnickerGroup
	dw SageGroup
	dw MediumGroup
	dw BoarderGroup
	dw PokefanMGroup
	dw PokefanFGroup
