PicAnimations:
BulbasaurAnimation:
IvysaurAnimation:
VenusaurAnimation:
CharmanderAnimation:
CharmeleonAnimation:
CharizardAnimation:
SquirtleAnimation:
WartortleAnimation:
BlastoiseAnimation:
CaterpieAnimation:
MetapodAnimation:
ButterfreeAnimation:
WeedleAnimation:
KakunaAnimation:
BeedrillAnimation:
PidgeyAnimation:
PidgeottoAnimation:
PidgeotAnimation:
RattataAnimation:
RaticateAnimation:
SpearowAnimation:
FearowAnimation:
EkansAnimation:
ArbokAnimation:
PikachuAnimation:
RaichuAnimation:
SandshrewAnimation:
SandslashAnimation:
NidoranFAnimation:
NidorinaAnimation:
NidoqueenAnimation:
NidoranMAnimation:
NidorinoAnimation:
NidokingAnimation:
ClefairyAnimation:
ClefableAnimation:
VulpixAnimation:
NinetalesAnimation:
JigglypuffAnimation:
WigglytuffAnimation:
ZubatAnimation:
GolbatAnimation:
OddishAnimation:
GloomAnimation:
VileplumeAnimation:
ParasAnimation:
ParasectAnimation:
VenonatAnimation:
VenomothAnimation:
DiglettAnimation:
DugtrioAnimation:
MeowthAnimation:
PersianAnimation:
PsyduckAnimation:
GolduckAnimation:
MankeyAnimation:
PrimeapeAnimation:
GrowlitheAnimation:
ArcanineAnimation:
PoliwagAnimation:
PoliwhirlAnimation:
PoliwrathAnimation:
AbraAnimation:
KadabraAnimation:
AlakazamAnimation:
MachopAnimation:
MachokeAnimation:
MachampAnimation:
BellsproutAnimation:
WeepinbellAnimation:
VictreebelAnimation:
TentacoolAnimation:
TentacruelAnimation:
GeodudeAnimation:
GravelerAnimation:
GolemAnimation:
PonytaAnimation:
RapidashAnimation:
SlowpokeAnimation:
SlowbroAnimation:
MagnemiteAnimation:
MagnetonAnimation:
FarfetchDAnimation:
DoduoAnimation:
DodrioAnimation:
SeelAnimation:
DewgongAnimation:
GrimerAnimation:
MukAnimation:
ShellderAnimation:
CloysterAnimation:
GastlyAnimation:
HaunterAnimation:
GengarAnimation:
OnixAnimation:
DrowzeeAnimation:
HypnoAnimation:
KrabbyAnimation:
KinglerAnimation:
VoltorbAnimation:
ElectrodeAnimation:
ExeggcuteAnimation:
ExeggutorAnimation:
CuboneAnimation:
MarowakAnimation:
HitmonleeAnimation:
HitmonchanAnimation:
LickitungAnimation:
KoffingAnimation:
WeezingAnimation:
RhyhornAnimation:
RhydonAnimation:
ChanseyAnimation:
TangelaAnimation:
KangaskhanAnimation:
HorseaAnimation:
SeadraAnimation:
GoldeenAnimation:
SeakingAnimation:
StaryuAnimation:
StarmieAnimation:
MrMimeAnimation:
ScytherAnimation:
JynxAnimation:
ElectabuzzAnimation:
MagmarAnimation:
PinsirAnimation:
TaurosAnimation:
MagikarpAnimation:
GyaradosAnimation:
LaprasAnimation:
DittoAnimation:
EeveeAnimation:
VaporeonAnimation:
JolteonAnimation:
FlareonAnimation:
PorygonAnimation:
OmanyteAnimation:
OmastarAnimation:
KabutoAnimation:
KabutopsAnimation:
AerodactylAnimation:
SnorlaxAnimation:
ArticunoAnimation:
ZapdosAnimation:
MoltresAnimation:
DratiniAnimation:
DragonairAnimation:
DragoniteAnimation:
MewtwoAnimation:
MewAnimation:
ChikoritaAnimation:
BayleefAnimation:
MeganiumAnimation:
CyndaquilAnimation:
QuilavaAnimation:
TyphlosionAnimation:
TotodileAnimation:
CroconawAnimation:
FeraligatrAnimation:
SentretAnimation:
FurretAnimation:
HoothootAnimation:
NoctowlAnimation:
LedybaAnimation:
LedianAnimation:
SpinarakAnimation:
AriadosAnimation:
CrobatAnimation:
ChinchouAnimation:
LanturnAnimation:
PichuAnimation:
CleffaAnimation:
IgglybuffAnimation:
TogepiAnimation:
TogeticAnimation:
NatuAnimation:
XatuAnimation:
MareepAnimation:
FlaaffyAnimation:
AmpharosAnimation:
BellossomAnimation:
MarillAnimation:
AzumarillAnimation:
SudowoodoAnimation:
PolitoedAnimation:
HoppipAnimation:
SkiploomAnimation:
JumpluffAnimation:
AipomAnimation:
SunkernAnimation:
SunfloraAnimation:
YanmaAnimation:
WooperAnimation:
QuagsireAnimation:
EspeonAnimation:
UmbreonAnimation:
MurkrowAnimation:
SlowkingAnimation:
MisdreavusAnimation:
UnownAnimation:
WobbuffetAnimation:
GirafarigAnimation:
PinecoAnimation:
ForretressAnimation:
DunsparceAnimation:
GligarAnimation:
SteelixAnimation:
SnubbullAnimation:
GranbullAnimation:
QwilfishAnimation:
ScizorAnimation:
ShuckleAnimation:
HeracrossAnimation:
SneaselAnimation:
TeddiursaAnimation:
UrsaringAnimation:
SlugmaAnimation:
MagcargoAnimation:
SwinubAnimation:
PiloswineAnimation:
CorsolaAnimation:
RemoraidAnimation:
OctilleryAnimation:
DelibirdAnimation:
MantineAnimation:
SkarmoryAnimation:
HoundourAnimation:
HoundoomAnimation:
KingdraAnimation:
PhanpyAnimation:
DonphanAnimation:
Porygon2Animation:
StantlerAnimation:
SmeargleAnimation:
TyrogueAnimation:
HitmontopAnimation:
SmoochumAnimation:
ElekidAnimation:
MagbyAnimation:
MiltankAnimation:
BlisseyAnimation:
RaikouAnimation:
EnteiAnimation:
SuicuneAnimation:
LarvitarAnimation:
PupitarAnimation:
TyranitarAnimation:
LugiaAnimation:
HoOhAnimation:
CelebiAnimation:
EggAnimation:
	endanim
