BulbasaurBitmasks:
IvysaurBitmasks:
VenusaurBitmasks:
CharmanderBitmasks:
CharmeleonBitmasks:
CharizardBitmasks:
SquirtleBitmasks:
WartortleBitmasks:
BlastoiseBitmasks:
CaterpieBitmasks:
MetapodBitmasks:
ButterfreeBitmasks:
WeedleBitmasks:
KakunaBitmasks:
BeedrillBitmasks:
PidgeyBitmasks:
PidgeottoBitmasks:
PidgeotBitmasks:
RattataBitmasks:
RaticateBitmasks:
SpearowBitmasks:
FearowBitmasks:
EkansBitmasks:
ArbokBitmasks:
PikachuBitmasks:
RaichuBitmasks:
SandshrewBitmasks:
SandslashBitmasks:
NidoranFBitmasks:
NidorinaBitmasks:
NidoqueenBitmasks:
NidoranMBitmasks:
NidorinoBitmasks:
NidokingBitmasks:
ClefairyBitmasks:
ClefableBitmasks:
VulpixBitmasks:
NinetalesBitmasks:
JigglypuffBitmasks:
WigglytuffBitmasks:
ZubatBitmasks:
GolbatBitmasks:
OddishBitmasks:
GloomBitmasks:
VileplumeBitmasks:
ParasBitmasks:
ParasectBitmasks:
VenonatBitmasks:
VenomothBitmasks:
DiglettBitmasks:
DugtrioBitmasks:
MeowthBitmasks:
PersianBitmasks:
PsyduckBitmasks:
GolduckBitmasks:
MankeyBitmasks:
PrimeapeBitmasks:
GrowlitheBitmasks:
ArcanineBitmasks:
PoliwagBitmasks:
PoliwhirlBitmasks:
PoliwrathBitmasks:
AbraBitmasks:
KadabraBitmasks:
AlakazamBitmasks:
MachopBitmasks:
MachokeBitmasks:
MachampBitmasks:
BellsproutBitmasks:
WeepinbellBitmasks:
VictreebelBitmasks:
TentacoolBitmasks:
TentacruelBitmasks:
GeodudeBitmasks:
GravelerBitmasks:
GolemBitmasks:
PonytaBitmasks:
RapidashBitmasks:
SlowpokeBitmasks:
SlowbroBitmasks:
MagnemiteBitmasks:
MagnetonBitmasks:
FarfetchDBitmasks:
DoduoBitmasks:
DodrioBitmasks:
SeelBitmasks:
DewgongBitmasks:
GrimerBitmasks:
MukBitmasks:
ShellderBitmasks:
CloysterBitmasks:
GastlyBitmasks:
HaunterBitmasks:
GengarBitmasks:
OnixBitmasks:
DrowzeeBitmasks:
HypnoBitmasks:
KrabbyBitmasks:
KinglerBitmasks:
VoltorbBitmasks:
ElectrodeBitmasks:
ExeggcuteBitmasks:
ExeggutorBitmasks:
CuboneBitmasks:
MarowakBitmasks:
HitmonleeBitmasks:
HitmonchanBitmasks:
LickitungBitmasks:
KoffingBitmasks:
WeezingBitmasks:
RhyhornBitmasks:
RhydonBitmasks:
ChanseyBitmasks:
TangelaBitmasks:
KangaskhanBitmasks:
HorseaBitmasks:
SeadraBitmasks:
GoldeenBitmasks:
SeakingBitmasks:
StaryuBitmasks:
StarmieBitmasks:
MrMimeBitmasks:
ScytherBitmasks:
JynxBitmasks:
ElectabuzzBitmasks:
MagmarBitmasks:
PinsirBitmasks:
TaurosBitmasks:
MagikarpBitmasks:
GyaradosBitmasks:
LaprasBitmasks:
DittoBitmasks:
EeveeBitmasks:
VaporeonBitmasks:
JolteonBitmasks:
FlareonBitmasks:
PorygonBitmasks:
OmanyteBitmasks:
OmastarBitmasks:
KabutoBitmasks:
KabutopsBitmasks:
AerodactylBitmasks:
SnorlaxBitmasks:
ArticunoBitmasks:
ZapdosBitmasks:
MoltresBitmasks:
DratiniBitmasks:
DragonairBitmasks:
DragoniteBitmasks:
MewtwoBitmasks:
MewBitmasks:
ChikoritaBitmasks:
BayleefBitmasks:
MeganiumBitmasks:
CyndaquilBitmasks:
QuilavaBitmasks:
TyphlosionBitmasks:
TotodileBitmasks:
CroconawBitmasks:
FeraligatrBitmasks:
SentretBitmasks:
FurretBitmasks:
HoothootBitmasks:
NoctowlBitmasks:
LedybaBitmasks:
LedianBitmasks:
SpinarakBitmasks:
AriadosBitmasks:
CrobatBitmasks:
ChinchouBitmasks:
LanturnBitmasks:
PichuBitmasks:
CleffaBitmasks:
IgglybuffBitmasks:
TogepiBitmasks:
TogeticBitmasks:
NatuBitmasks:
XatuBitmasks:
MareepBitmasks:
FlaaffyBitmasks:
AmpharosBitmasks:
BellossomBitmasks:
MarillBitmasks:
AzumarillBitmasks:
SudowoodoBitmasks:
PolitoedBitmasks:
HoppipBitmasks:
SkiploomBitmasks:
JumpluffBitmasks:
AipomBitmasks:
SunkernBitmasks:
SunfloraBitmasks:
YanmaBitmasks:
WooperBitmasks:
QuagsireBitmasks:
EspeonBitmasks:
UmbreonBitmasks:
MurkrowBitmasks:
SlowkingBitmasks:
MisdreavusBitmasks:
UnownBitmasks:
WobbuffetBitmasks:
GirafarigBitmasks:
PinecoBitmasks:
ForretressBitmasks:
DunsparceBitmasks:
GligarBitmasks:
SteelixBitmasks:
SnubbullBitmasks:
GranbullBitmasks:
QwilfishBitmasks:
ScizorBitmasks:
ShuckleBitmasks:
HeracrossBitmasks:
SneaselBitmasks:
TeddiursaBitmasks:
UrsaringBitmasks:
SlugmaBitmasks:
MagcargoBitmasks:
SwinubBitmasks:
PiloswineBitmasks:
CorsolaBitmasks:
RemoraidBitmasks:
OctilleryBitmasks:
DelibirdBitmasks:
MantineBitmasks:
SkarmoryBitmasks:
HoundourBitmasks:
HoundoomBitmasks:
KingdraBitmasks:
PhanpyBitmasks:
DonphanBitmasks:
Porygon2Bitmasks:
StantlerBitmasks:
SmeargleBitmasks:
TyrogueBitmasks:
HitmontopBitmasks:
SmoochumBitmasks:
ElekidBitmasks:
MagbyBitmasks:
MiltankBitmasks:
BlisseyBitmasks:
RaikouBitmasks:
EnteiBitmasks:
SuicuneBitmasks:
LarvitarBitmasks:
PupitarBitmasks:
TyranitarBitmasks:
LugiaBitmasks:
HoOhBitmasks:
CelebiBitmasks:
EggBitmasks:
	; nothing
