AnimationFrames:
BulbasaurFrames:
IvysaurFrames:
VenusaurFrames:
CharmanderFrames:
CharmeleonFrames:
CharizardFrames:
SquirtleFrames:
WartortleFrames:
BlastoiseFrames:
CaterpieFrames:
MetapodFrames:
ButterfreeFrames:
WeedleFrames:
KakunaFrames:
BeedrillFrames:
PidgeyFrames:
PidgeottoFrames:
PidgeotFrames:
RattataFrames:
RaticateFrames:
SpearowFrames:
FearowFrames:
EkansFrames:
ArbokFrames:
PikachuFrames:
RaichuFrames:
SandshrewFrames:
SandslashFrames:
NidoranFFrames:
NidorinaFrames:
NidoqueenFrames:
NidoranMFrames:
NidorinoFrames:
NidokingFrames:
ClefairyFrames:
ClefableFrames:
VulpixFrames:
NinetalesFrames:
JigglypuffFrames:
WigglytuffFrames:
ZubatFrames:
GolbatFrames:
OddishFrames:
GloomFrames:
VileplumeFrames:
ParasFrames:
ParasectFrames:
VenonatFrames:
VenomothFrames:
DiglettFrames:
DugtrioFrames:
MeowthFrames:
PersianFrames:
PsyduckFrames:
GolduckFrames:
MankeyFrames:
PrimeapeFrames:
GrowlitheFrames:
ArcanineFrames:
PoliwagFrames:
PoliwhirlFrames:
PoliwrathFrames:
AbraFrames:
KadabraFrames:
AlakazamFrames:
MachopFrames:
MachokeFrames:
MachampFrames:
BellsproutFrames:
WeepinbellFrames:
VictreebelFrames:
TentacoolFrames:
TentacruelFrames:
GeodudeFrames:
GravelerFrames:
GolemFrames:
PonytaFrames:
RapidashFrames:
SlowpokeFrames:
SlowbroFrames:
MagnemiteFrames:
MagnetonFrames:
FarfetchDFrames:
DoduoFrames:
DodrioFrames:
SeelFrames:
DewgongFrames:
GrimerFrames:
MukFrames:
ShellderFrames:
CloysterFrames:
GastlyFrames:
HaunterFrames:
GengarFrames:
OnixFrames:
DrowzeeFrames:
HypnoFrames:
KrabbyFrames:
KinglerFrames:
VoltorbFrames:
ElectrodeFrames:
ExeggcuteFrames:
ExeggutorFrames:
CuboneFrames:
MarowakFrames:
HitmonleeFrames:
HitmonchanFrames:
LickitungFrames:
KoffingFrames:
WeezingFrames:
RhyhornFrames:
RhydonFrames:
ChanseyFrames:
TangelaFrames:
KangaskhanFrames:
HorseaFrames:
SeadraFrames:
GoldeenFrames:
SeakingFrames:
StaryuFrames:
StarmieFrames:
MrMimeFrames:
ScytherFrames:
JynxFrames:
ElectabuzzFrames:
MagmarFrames:
PinsirFrames:
TaurosFrames:
MagikarpFrames:
GyaradosFrames:
LaprasFrames:
DittoFrames:
EeveeFrames:
VaporeonFrames:
JolteonFrames:
FlareonFrames:
PorygonFrames:
OmanyteFrames:
OmastarFrames:
KabutoFrames:
KabutopsFrames:
AerodactylFrames:
SnorlaxFrames:
ArticunoFrames:
ZapdosFrames:
MoltresFrames:
DratiniFrames:
DragonairFrames:
DragoniteFrames:
MewtwoFrames:
MewFrames:
ChikoritaFrames:
BayleefFrames:
MeganiumFrames:
CyndaquilFrames:
QuilavaFrames:
TyphlosionFrames:
TotodileFrames:
CroconawFrames:
FeraligatrFrames:
SentretFrames:
FurretFrames:
HoothootFrames:
NoctowlFrames:
LedybaFrames:
LedianFrames:
SpinarakFrames:
AriadosFrames:
CrobatFrames:
ChinchouFrames:
LanturnFrames:
PichuFrames:
CleffaFrames:
IgglybuffFrames:
TogepiFrames:
TogeticFrames:
NatuFrames:
XatuFrames:
MareepFrames:
FlaaffyFrames:
AmpharosFrames:
BellossomFrames:
MarillFrames:
AzumarillFrames:
SudowoodoFrames:
PolitoedFrames:
HoppipFrames:
SkiploomFrames:
JumpluffFrames:
AipomFrames:
SunkernFrames:
SunfloraFrames:
YanmaFrames:
WooperFrames:
QuagsireFrames:
EspeonFrames:
UmbreonFrames:
MurkrowFrames:
SlowkingFrames:
MisdreavusFrames:
UnownFrames:
WobbuffetFrames:
GirafarigFrames:
PinecoFrames:
ForretressFrames:
DunsparceFrames:
GligarFrames:
SteelixFrames:
SnubbullFrames:
GranbullFrames:
QwilfishFrames:
ScizorFrames:
ShuckleFrames:
HeracrossFrames:
SneaselFrames:
TeddiursaFrames:
UrsaringFrames:
SlugmaFrames:
MagcargoFrames:
SwinubFrames:
PiloswineFrames:
CorsolaFrames:
RemoraidFrames:
OctilleryFrames:
DelibirdFrames:
MantineFrames:
SkarmoryFrames:
HoundourFrames:
HoundoomFrames:
KingdraFrames:
PhanpyFrames:
DonphanFrames:
Porygon2Frames:
StantlerFrames:
SmeargleFrames:
TyrogueFrames:
HitmontopFrames:
SmoochumFrames:
ElekidFrames:
MagbyFrames:
MiltankFrames:
BlisseyFrames:
RaikouFrames:
EnteiFrames:
SuicuneFrames:
LarvitarFrames:
PupitarFrames:
TyranitarFrames:
LugiaFrames:
HoOhFrames:
CelebiFrames:
EggFrames:
	; nothing
