
	dba MagikarpFrontpic
	dba MagikarpBackpic
	dba MagikarpSkellyFrontpic
	dba MagikarpSkellyBackpic
	dba MagikarpCalico1Frontpic
	dba MagikarpCalico1Backpic
	dba MagikarpCalico2Frontpic
	dba MagikarpCalico2Backpic
	dba MagikarpCalico3Frontpic
	dba MagikarpCalico3Backpic
	dba MagikarpTwotoneFrontpic
	dba MagikarpTwotoneBackpic
	dba MagikarpOrcaFrontpic
	dba MagikarpOrcaBackpic
	dba MagikarpDapplesFrontpic
	dba MagikarpDapplesBackpic
	dba MagikarpTigerFrontpic
	dba MagikarpTigerBackpic
	dba MagikarpZebraFrontpic
	dba MagikarpZebraBackpic
	dba MagikarpStripeFrontpic
	dba MagikarpStripeBackpic
	dba MagikarpForeheadFrontpic
	dba MagikarpForeheadBackpic
	dba MagikarpMaskFrontpic
	dba MagikarpMaskBackpic
	dba MagikarpBubblesFrontpic
	dba MagikarpBubblesBackpic
