PicPointers::
	add_pics Bulbasaur
	add_pics Ivysaur
	add_pics Venusaur
	add_pics Charmander
	add_pics Charmeleon
	add_pics Charizard
	add_pics Squirtle ; unused; see SquirtlePicPointers
	add_pics Wartortle
	add_pics Blastoise
	add_pics Caterpie
	add_pics Metapod
	add_pics Butterfree
	add_pics Weedle
	add_pics Kakuna
	add_pics Beedrill
	add_pics Pidgey
	add_pics Pidgeotto
	add_pics Pidgeot
	add_pics Rattata
	add_pics Raticate
	add_pics Spearow
	add_pics Fearow
	add_pics Ekans
	add_pics Arbok
	add_pics Pikachu
	add_pics Raichu
	add_pics Sandshrew
	add_pics Sandslash
	add_pics NidoranF
	add_pics Nidorina
	add_pics Nidoqueen
	add_pics NidoranM
	add_pics Nidorino
	add_pics Nidoking
	add_pics Clefairy
	add_pics Clefable
	add_pics Vulpix
	add_pics Ninetales
	add_pics Jigglypuff
	add_pics Wigglytuff
	add_pics Zubat
	add_pics Golbat
	add_pics Oddish
	add_pics Gloom
	add_pics Vileplume
	add_pics Paras
	add_pics Parasect
	add_pics Venonat
	add_pics Venomoth
	add_pics Diglett
	add_pics Dugtrio
	add_pics Meowth ; unused; see MeowthPicPointers
	add_pics Persian
	add_pics Psyduck
	add_pics Golduck
	add_pics Mankey
	add_pics Primeape
	add_pics Growlithe
	add_pics Arcanine
	add_pics Poliwag
	add_pics Poliwhirl
	add_pics Poliwrath
	add_pics Abra
	add_pics Kadabra
	add_pics Alakazam
	add_pics Machop
	add_pics Machoke
	add_pics Machamp
	add_pics Bellsprout
	add_pics Weepinbell
	add_pics Victreebel
	add_pics Tentacool
	add_pics Tentacruel
	add_pics Geodude
	add_pics Graveler
	add_pics Golem
	add_pics Ponyta
	add_pics Rapidash
	add_pics Slowpoke
	add_pics Slowbro
	add_pics Magnemite
	add_pics Magneton
	add_pics FarfetchD
	add_pics Doduo
	add_pics Dodrio
	add_pics Seel
	add_pics Dewgong
	add_pics Grimer
	add_pics Muk
	add_pics Shellder
	add_pics Cloyster
	add_pics Gastly
	add_pics Haunter
	add_pics Gengar
	add_pics Onix ; unused; see OnixPicPointers
	add_pics Drowzee
	add_pics Hypno
	add_pics Krabby
	add_pics Kingler
	add_pics Voltorb
	add_pics Electrode
	add_pics Exeggcute
	add_pics Exeggutor
	add_pics Cubone
	add_pics Marowak
	add_pics Hitmonlee
	add_pics Hitmonchan
	add_pics Lickitung
	add_pics Koffing
	add_pics Weezing
	add_pics Rhyhorn
	add_pics Rhydon
	add_pics Chansey
	add_pics Tangela
	add_pics Kangaskhan
	add_pics Horsea
	add_pics Seadra
	add_pics Goldeen
	add_pics Seaking
	add_pics Staryu
	add_pics Starmie
	add_pics MrMime
	add_pics Scyther
	add_pics Jynx
	add_pics Electabuzz
	add_pics Magmar
	add_pics Pinsir
	add_pics Tauros
	add_pics Magikarp ; unused; see MagikarpPicPointers
	add_pics Gyarados
	add_pics Lapras
	add_pics Ditto
	add_pics Eevee
	add_pics Vaporeon
	add_pics Jolteon
	add_pics Flareon
	add_pics Porygon
	add_pics Omanyte
	add_pics Omastar
	add_pics Kabuto
	add_pics Kabutops
	add_pics Aerodactyl
	add_pics Snorlax
	add_pics Articuno
	add_pics Zapdos
	add_pics Moltres
	add_pics Dratini
	add_pics Dragonair
	add_pics Dragonite
	add_pics Mewtwo
	add_pics Mew
	add_pics Tropius
	add_pics Kecleon
	add_pics Chatot
	add_pics Pikipek
	add_pics Trumbeak
	add_pics Toucannon
	add_pics Munchlax
	add_pics Rockruff
	add_pics LycanrocMidday ; unused; see LycanrocPicPointers
	add_pics Wingull
	add_pics Pelipper
	add_pics Chingling
	add_pics Chimecho
	add_pics Ledyba
	add_pics Ledian
	add_pics Spinarak
	add_pics Ariados
	add_pics Crobat
	add_pics Chinchou
	add_pics Lanturn
	add_pics Pichu
	add_pics Cleffa
	add_pics Igglybuff
	add_pics Togepi
	add_pics Togetic
	add_pics Natu
	add_pics Xatu
	add_pics Mareep
	add_pics Flaaffy
	add_pics Ampharos
	add_pics Bellossom
	add_pics Marill
	add_pics Azumarill
	add_pics Sudowoodo
	add_pics Politoed
	add_pics Hoppip
	add_pics Skiploom
	add_pics Jumpluff
	add_pics Aipom
	add_pics Sunkern
	add_pics Sunflora
	add_pics Yanma
	add_pics Wooper
	add_pics Quagsire
	add_pics Espeon
	add_pics Umbreon
	add_pics Murkrow
	add_pics Slowking
	add_pics Misdreavus
	add_pics SpindaA ; unused; see SpindaPicPointers
	add_pics Wobbuffet
	add_pics Girafarig
	add_pics Pineco
	add_pics Forretress
	add_pics Dunsparce
	add_pics Gligar
	add_pics Steelix
	add_pics Snubbull
	add_pics Granbull
	add_pics Qwilfish
	add_pics Scizor
	add_pics Shuckle
	add_pics Heracross
	add_pics Sneasel
	add_pics Teddiursa
	add_pics Ursaring
	add_pics Slugma
	add_pics Magcargo
	add_pics Swinub
	add_pics Piloswine
	add_pics Corsola
	add_pics Remoraid
	add_pics Octillery
	add_pics Mantyke
	add_pics Mantine
	add_pics Skarmory
	add_pics Houndour
	add_pics Houndoom
	add_pics Kingdra
	add_pics Phanpy
	add_pics Donphan
	add_pics Porygon2
	add_pics Stantler
	add_pics Smeargle
	add_pics Tyrogue
	add_pics Hitmontop
	add_pics Smoochum
	add_pics Elekid
	add_pics Magby
	add_pics Miltank
	add_pics Blissey
	add_pics Raikou
	add_pics Entei
	add_pics Suicune
	add_pics Larvitar
	add_pics Pupitar
	add_pics Tyranitar
	add_pics Lugia
	add_pics HoOh
	add_pics Celebi
	add_pics Latias
	add_pics Latios
	; no EggBackpic
	dba EggPic
	dbw -1, -1
	; unused
	dbw -1, -1
	dbw -1, -1
