SpindaAnimations:
SpindaAAnimation:
SpindaBAnimation:
SpindaCAnimation:
SpindaDAnimation:
SpindaEAnimation:
SpindaFAnimation:
SpindaGAnimation:
SpindaHAnimation:
SpindaIAnimation:
SpindaJAnimation:
SpindaKAnimation:
SpindaLAnimation:
SpindaMAnimation:
SpindaNAnimation:
SpindaOAnimation:
SpindaPAnimation:
SpindaQAnimation:
SpindaRAnimation:
SpindaSAnimation:
SpindaTAnimation:
SpindaUAnimation:
SpindaVAnimation:
SpindaWAnimation:
SpindaXAnimation:
SpindaYAnimation:
SpindaZAnimation:
	endanim
