SpindaFramesPointers:
	dw SpindaAFrames
	dw SpindaBFrames
	dw SpindaCFrames
	dw SpindaDFrames
	dw SpindaEFrames
	dw SpindaFFrames
	dw SpindaGFrames
	dw SpindaHFrames
	dw SpindaIFrames
	dw SpindaJFrames
	dw SpindaKFrames
	dw SpindaLFrames
	dw SpindaMFrames
	dw SpindaNFrames
	dw SpindaOFrames
	dw SpindaPFrames
	dw SpindaQFrames
	dw SpindaRFrames
	dw SpindaSFrames
	dw SpindaTFrames
	dw SpindaUFrames
	dw SpindaVFrames
	dw SpindaWFrames
	dw SpindaXFrames
	dw SpindaYFrames
	dw SpindaZFrames
