
	add_pics SpindaA
	add_pics SpindaB
	add_pics SpindaC
	add_pics SpindaD
	add_pics SpindaE
	add_pics SpindaF
	add_pics SpindaG
	add_pics SpindaH
	add_pics SpindaI
	add_pics SpindaJ
	add_pics SpindaK
	add_pics SpindaL
	add_pics SpindaM
	add_pics SpindaN
	add_pics SpindaO
	add_pics SpindaP
	add_pics SpindaQ
	add_pics SpindaR
	add_pics SpindaS
	add_pics SpindaT
	add_pics SpindaU
	add_pics SpindaV
	add_pics SpindaW
	add_pics SpindaX
	add_pics SpindaY
	add_pics SpindaZ
