SpindaABitmasks:
SpindaBBitmasks:
SpindaCBitmasks:
SpindaDBitmasks:
SpindaEBitmasks:
SpindaFBitmasks:
SpindaGBitmasks:
SpindaHBitmasks:
SpindaIBitmasks:
SpindaJBitmasks:
SpindaKBitmasks:
SpindaLBitmasks:
SpindaMBitmasks:
SpindaNBitmasks:
SpindaOBitmasks:
SpindaPBitmasks:
SpindaQBitmasks:
SpindaRBitmasks:
SpindaSBitmasks:
SpindaTBitmasks:
SpindaUBitmasks:
SpindaVBitmasks:
SpindaWBitmasks:
SpindaXBitmasks:
SpindaYBitmasks:
SpindaZBitmasks:
	; nothing
