SpindaBitmasksPointers:
	dw SpindaABitmasks
	dw SpindaBBitmasks
	dw SpindaCBitmasks
	dw SpindaDBitmasks
	dw SpindaEBitmasks
	dw SpindaFBitmasks
	dw SpindaGBitmasks
	dw SpindaHBitmasks
	dw SpindaIBitmasks
	dw SpindaJBitmasks
	dw SpindaKBitmasks
	dw SpindaLBitmasks
	dw SpindaMBitmasks
	dw SpindaNBitmasks
	dw SpindaOBitmasks
	dw SpindaPBitmasks
	dw SpindaQBitmasks
	dw SpindaRBitmasks
	dw SpindaSBitmasks
	dw SpindaTBitmasks
	dw SpindaUBitmasks
	dw SpindaVBitmasks
	dw SpindaWBitmasks
	dw SpindaXBitmasks
	dw SpindaYBitmasks
	dw SpindaZBitmasks
