SpindaAnimationPointers:
	dw SpindaAAnimation
	dw SpindaBAnimation
	dw SpindaCAnimation
	dw SpindaDAnimation
	dw SpindaEAnimation
	dw SpindaFAnimation
	dw SpindaGAnimation
	dw SpindaHAnimation
	dw SpindaIAnimation
	dw SpindaJAnimation
	dw SpindaKAnimation
	dw SpindaLAnimation
	dw SpindaMAnimation
	dw SpindaNAnimation
	dw SpindaOAnimation
	dw SpindaPAnimation
	dw SpindaQAnimation
	dw SpindaRAnimation
	dw SpindaSAnimation
	dw SpindaTAnimation
	dw SpindaUAnimation
	dw SpindaVAnimation
	dw SpindaWAnimation
	dw SpindaXAnimation
	dw SpindaYAnimation
	dw SpindaZAnimation
