
	dbba SPINDA,    SpindaPicPointers
	dbba ONIX,      OnixPicPointers
	dbba STEELIX,   SteelixPicPointers
	dbba EXEGGUTOR, ExeggutorPicPointers
	dbba GRIMER,    GrimerPicPointers
	dbba MUK,       MukPicPointers
	dbba PERSIAN,   PersianPicPointers
	dbba VULPIX,    VulpixPicPointers
	dbba NINETALES, NinetalesPicPointers
	dbba SANDSHREW, SandshrewPicPointers
	dbba SANDSLASH, SandslashPicPointers
	dbba RATTATA,   RattataPicPointers
	dbba RATICATE,  RaticatePicPointers
	dbba DIGLETT,   DiglettPicPointers
	dbba DUGTRIO,   DugtrioPicPointers
	dbba GEODUDE,   GeodudePicPointers
	dbba GRAVELER,  GravelerPicPointers
	dbba GOLEM,     GolemPicPointers
	dbba RAICHU,    RaichuPicPointers
	dbba MAROWAK,   MarowakPicPointers
	dbba MEOWTH,    MeowthPicPointers
	dbba POLIWRATH, PoliwrathPicPointers
	dbba LYCANROC,  LycanrocPicPointers
	dbba SQUIRTLE,  SquirtlePicPointers
	dbba MAGIKARP,  MagikarpPicPointers
	dbba WARTORTLE, WartortlePicPointers
	dbba BLASTOISE, BlastoisePicPointers
	dbba -1,        PicPointers
