	db "MASTER BALL@"
	db "ULTRA BALL@"
	db "BRIGHTPOWDER@"
	db "GREAT BALL@"
	db "# BALL@"
	db "TOWN MAP@"
	db "SKATEBOARD@"
	db "MOON STONE@"
	db "ANTIDOTE@"
	db "BURN HEAL@"
	db "ICE HEAL@"
	db "AWAKENING@"
	db "PARLYZ HEAL@"
	db "FULL RESTORE@"
	db "MAX POTION@"
	db "HYPER POTION@"
	db "SUPER POTION@"
	db "POTION@"
	db "ESCAPE ROPE@"
	db "REPEL@"
	db "MAX ELIXER@"
	db "FIRE STONE@"
	db "THUNDERSTONE@"
	db "WATER STONE@"
	db "PINKAN BERRY@"
	db "HP UP@"
	db "PROTEIN@"
	db "IRON@"
	db "CARBOS@"
	db "LUCKY PUNCH@"
	db "CALCIUM@"
	db "RARE CANDY@"
	db "X ACCURACY@"
	db "LEAF STONE@"
	db "METAL POWDER@"
	db "NUGGET@"
	db "# DOLL@"
	db "FULL HEAL@"
	db "REVIVE@"
	db "MAX REVIVE@"
	db "GUARD SPEC.@"
	db "SUPER REPEL@"
	db "MAX REPEL@"
	db "DIRE HIT@"
	db "MASTER ROD@"
	db "FRESH WATER@"
	db "SODA POP@"
	db "LEMONADE@"
	db "X ATTACK@"
	db "X DEFEND@"
	db "X SPEED@"
	db "X SPCL ATK@"
	db "COIN CASE@"
	db "ITEMFINDER@"
	db "# FLUTE@"
	db "EXP.ALL@"
	db "OLD ROD@"
	db "GOOD ROD@"
	db "SUPER ROD@"
	db "PP UP@"
	db "PP MAX@"
	db "ETHER@"
	db "MAX ETHER@"
	db "ELIXER@"
	db "PINK CURE@"
	db "HEART SCALE@"
	db "QUICK CLAW@"
	db "PECHA BERRY@"
	db "SOFT SAND@"
	db "SHARP BEAK@"
	db "CHERI BERRY@"
	db "ASPEAR BERRY@"
	db "RAWST BERRY@"
	db "POISON BARB@"
	db "KING'S ROCK@"
	db "PERSIM BERRY@"
	db "CHESTO BERRY@"
	db "TINYMUSHROOM@"
	db "BIG MUSHROOM@"
	db "SILVERPOWDER@"
	db "AMULET COIN@"
	db "CLEANSE TAG@"
	db "MYSTIC WATER@"
	db "TWISTEDSPOON@"
	db "BLACKBELT@"
	db "BLACKGLASSES@"
	db "PINK BOW@"
	db "STICK@"
	db "SMOKE BALL@"
	db "NEVERMELTICE@"
	db "MAGNET@"
	db "LUM BERRY@"
	db "PEARL@"
	db "BIG PEARL@"
	db "EVERSTONE@"
	db "SPELL TAG@"
	db "GRAPEFRUIT@"
	db "GS BALL@"
	db "MIRACLE SEED@"
	db "THICK CLUB@"
	db "FOCUS BAND@"
	db "ENERGYPOWDER@"
	db "ENERGY ROOT@"
	db "HEAL POWDER@"
	db "REVIVAL HERB@"
	db "HARD STONE@"
	db "LUCKY EGG@"
	db "STARDUST@"
	db "STAR PIECE@"
	db "CHARCOAL@"
	db "BERRY JUICE@"
	db "SCOPE LENS@"
	db "METAL COAT@"
	db "DRAGON FANG@"
	db "LEFTOVERS@"
	db "LEPPA BERRY@"
	db "DRAGON SCALE@"
	db "HEAVY BALL@"
	db "LEVEL BALL@"
	db "LURE BALL@"
	db "FAST BALL@"
	db "LIGHT BALL@"
	db "FRIEND BALL@"
	db "MOON BALL@"
	db "LOVE BALL@"
	db "SUN STONE@"
	db "POLKADOT BOW@"
	db "UP-GRADE@"
	db "ORAN BERRY@"
	db "SITRUS BERRY@"
	db "SQUIRTBOTTLE@"
	db "CONTEST BALL@"
	db "IMAKUNI?CARD@"
	db "SACRED ASH@"
	db "SILVER WING@"
	db "RAINBOW WING@"
	db "SHINY STONE@"
	db "LINK CABLE@"
	db "MORO TROPHY@"
	db "DUBIOUS DISC@"
	db "SHINY CHARM@"
	db "SOUL DEW@"
	db "DIVE BALL@"
	db "HEAL BALL@"
	db "DUSK BALL@"
	db "FLOWER MAIL@"
	db "SURF MAIL@"
	db "LITEBLUEMAIL@"
	db "PORTRAITMAIL@"
	db "LOVELY MAIL@"
	db "EON MAIL@"
	db "MORPH MAIL@"
	db "BLUESKY MAIL@"
	db "MUSIC MAIL@"
	db "MIRAGE MAIL@"
	db "X SPCL DEF@"
	db "ICE STONE@"
	db "QUICK POWDER@"
	db "MAGMARIZER@"
	db "ELECTIRIZER@"
	db "PROTECTOR@"
	db "SALVEYO WEED@"
	db "CAT STATUE@"
	db "SHELL BOX@"
	db "ELECTRIC ORB@"
	db "FIRE ORB@"
	db "ICE ORB@"
	db "KANTO STONE@"
	db "TM01@"
	db "TM02@"
	db "TM03@"
	db "TM04@"
	db "TM05@"
	db "TM06@"
	db "TM07@"
	db "TM08@"
	db "TM09@"
	db "TM10@"
	db "TM11@"
	db "TM12@"
	db "TM13@"
	db "TM14@"
	db "TM15@"
	db "TM16@"
	db "TM17@"
	db "TM18@"
	db "TM19@"
	db "TM20@"
	db "TM21@"
	db "TM22@"
	db "TM23@"
	db "TM24@"
	db "TM25@"
	db "TM26@"
	db "TM27@"
	db "TM28@"
	db "TM29@"
	db "TM30@"
	db "TM31@"
	db "TM32@"
	db "TM33@"
	db "TM34@"
	db "TM35@"
	db "TM36@"
	db "TM37@"
	db "TM38@"
	db "TM39@"
	db "TM40@"
	db "TM41@"
	db "TM42@"
	db "TM43@"
	db "TM44@"
	db "TM45@"
	db "TM46@"
	db "TM47@"
	db "TM48@"
	db "TM49@"
	db "TM50@"
	db "HM01@"
	db "HM02@"
	db "HM03@"
	db "HM04@"
	db "HM05@"
	db "HM06@"
	db "HM07@"
