; Auto-generated by dedgen.py

SECTION "DED 1", ROMX

DragalgeDEDData:: INCBIN "audio/ded/dragalge.ded"
SylveonDEDData:: INCBIN "audio/ded/sylveon.ded"

SECTION "DED 2", ROMX

TogekissDEDData:: INCBIN "audio/ded/togekiss.ded"
PorygonZDEDData:: INCBIN "audio/ded/porygon_z.ded"

SECTION "DED 3", ROMX

ElectivireDEDData:: INCBIN "audio/ded/electivire.ded"
MarshadowDEDData:: INCBIN "audio/ded/marshadow.ded"

SECTION "DED 4", ROMX

SalazzleDEDData:: INCBIN "audio/ded/salazzle.ded"
PalossandDEDData:: INCBIN "audio/ded/palossand.ded"

SECTION "DED 5", ROMX

GlaceonDEDData:: INCBIN "audio/ded/glaceon.ded"
MagnezoneDEDData:: INCBIN "audio/ded/magnezone.ded"

SECTION "DED 6", ROMX

ToucannonDEDData:: INCBIN "audio/ded/toucannon.ded"
LumineonDEDData:: INCBIN "audio/ded/lumineon.ded"

SECTION "DED 7", ROMX

WailordDEDData:: INCBIN "audio/ded/wailord.ded"
ToxapexDEDData:: INCBIN "audio/ded/toxapex.ded"

SECTION "DED 8", ROMX

LycanrocMidnightDEDData:: INCBIN "audio/ded/lycanroc_midnight.ded"
SandygastDEDData:: INCBIN "audio/ded/sandygast.ded"
ChimechoDEDData:: INCBIN "audio/ded/chimecho.ded"

SECTION "DED 9", ROMX

TropiusDEDData:: INCBIN "audio/ded/tropius.ded"
ChinglingDEDData:: INCBIN "audio/ded/chingling.ded"
SkrelpDEDData:: INCBIN "audio/ded/skrelp.ded"

SECTION "DED 10", ROMX

RhyperiorDEDData:: INCBIN "audio/ded/rhyperior.ded"
FlygonDEDData:: INCBIN "audio/ded/flygon.ded"
LatiosDEDData:: INCBIN "audio/ded/latios.ded"

SECTION "DED 11", ROMX

RibombeeDEDData:: INCBIN "audio/ded/ribombee.ded"
FinneonDEDData:: INCBIN "audio/ded/finneon.ded"
RelicanthDEDData:: INCBIN "audio/ded/relicanth.ded"

SECTION "DED 12", ROMX

WailmerDEDData:: INCBIN "audio/ded/wailmer.ded"
MagmortarDEDData:: INCBIN "audio/ded/magmortar.ded"
LeafeonDEDData:: INCBIN "audio/ded/leafeon.ded"

SECTION "DED 13", ROMX

TurtonatorDEDData:: INCBIN "audio/ded/turtonator.ded"
LickilickyDEDData:: INCBIN "audio/ded/lickilicky.ded"
TrumbeakDEDData:: INCBIN "audio/ded/trumbeak.ded"

SECTION "DED 14", ROMX

StunfiskDEDData:: INCBIN "audio/ded/stunfisk.ded"
SharpedoDEDData:: INCBIN "audio/ded/sharpedo.ded"
TangrowthDEDData:: INCBIN "audio/ded/tangrowth.ded"

SECTION "DED 15", ROMX

MimikyuDEDData:: INCBIN "audio/ded/mimikyu.ded"
LycanrocDuskDEDData:: INCBIN "audio/ded/lycanroc_dusk.ded"
SalanditDEDData:: INCBIN "audio/ded/salandit.ded"
CarvanhaDEDData:: INCBIN "audio/ded/carvanha.ded"

SECTION "DED 16", ROMX

MareanieDEDData:: INCBIN "audio/ded/mareanie.ded"
VibravaDEDData:: INCBIN "audio/ded/vibrava.ded"
LycanrocMiddayDEDData:: INCBIN "audio/ded/lycanroc_midday.ded"
MimeJrDEDData:: INCBIN "audio/ded/mime__jr.ded"

SECTION "DED 17", ROMX

SpindaDEDData:: INCBIN "audio/ded/spinda.ded"
ChatotDEDData:: INCBIN "audio/ded/chatot.ded"
HappinyDEDData:: INCBIN "audio/ded/happiny.ded"
WingullDEDData:: INCBIN "audio/ded/wingull.ded"
LatiasDEDData:: INCBIN "audio/ded/latias.ded"

SECTION "DED 18", ROMX

CutieflyDEDData:: INCBIN "audio/ded/cutiefly.ded"
MantykeDEDData:: INCBIN "audio/ded/mantyke.ded"
AzurillDEDData:: INCBIN "audio/ded/azurill.ded"
MunchlaxDEDData:: INCBIN "audio/ded/munchlax.ded"
PelipperDEDData:: INCBIN "audio/ded/pelipper.ded"
KecleonDEDData:: INCBIN "audio/ded/kecleon.ded"

SECTION "DED 19", ROMX

RockruffDEDData:: INCBIN "audio/ded/rockruff.ded"
TrapinchDEDData:: INCBIN "audio/ded/trapinch.ded"
PikipekDEDData:: INCBIN "audio/ded/pikipek.ded"
