; Auto-generated by dedgen.py

SECTION "DED 1", ROMX

DragalgeDEDData:: INCBIN "audio/ded/dragalge.ded"
Lycanroc_midnightDEDData:: INCBIN "audio/ded/lycanroc_midnight.ded"

SECTION "DED 2", ROMX

SalazzleDEDData:: INCBIN "audio/ded/salazzle.ded"
RibombeeDEDData:: INCBIN "audio/ded/ribombee.ded"

SECTION "DED 3", ROMX

ToucannonDEDData:: INCBIN "audio/ded/toucannon.ded"
ElectivireDEDData:: INCBIN "audio/ded/electivire.ded"

SECTION "DED 4", ROMX

MarshadowDEDData:: INCBIN "audio/ded/marshadow.ded"
SylveonDEDData:: INCBIN "audio/ded/sylveon.ded"

SECTION "DED 5", ROMX

MagnezoneDEDData:: INCBIN "audio/ded/magnezone.ded"
LumineonDEDData:: INCBIN "audio/ded/lumineon.ded"

SECTION "DED 6", ROMX

GlaceonDEDData:: INCBIN "audio/ded/glaceon.ded"
PalossandDEDData:: INCBIN "audio/ded/palossand.ded"

SECTION "DED 7", ROMX

WailordDEDData:: INCBIN "audio/ded/wailord.ded"
ToxapexDEDData:: INCBIN "audio/ded/toxapex.ded"

SECTION "DED 8", ROMX

SandygastDEDData:: INCBIN "audio/ded/sandygast.ded"
TogekissDEDData:: INCBIN "audio/ded/togekiss.ded"
KecleonDEDData:: INCBIN "audio/ded/kecleon.ded"

SECTION "DED 9", ROMX

TropiusDEDData:: INCBIN "audio/ded/tropius.ded"
PorygonZDEDData:: INCBIN "audio/ded/porygon_z.ded"
MantykeDEDData:: INCBIN "audio/ded/mantyke.ded"

SECTION "DED 10", ROMX

StunfiskDEDData:: INCBIN "audio/ded/stunfisk.ded"
FlygonDEDData:: INCBIN "audio/ded/flygon.ded"
SkrelpDEDData:: INCBIN "audio/ded/skrelp.ded"

SECTION "DED 11", ROMX

ChinglingDEDData:: INCBIN "audio/ded/chingling.ded"
LickilickyDEDData:: INCBIN "audio/ded/lickilicky.ded"
MareanieDEDData:: INCBIN "audio/ded/mareanie.ded"

SECTION "DED 12", ROMX

MagmortarDEDData:: INCBIN "audio/ded/magmortar.ded"
TurtonatorDEDData:: INCBIN "audio/ded/turtonator.ded"
MimikyuDEDData:: INCBIN "audio/ded/mimikyu.ded"

SECTION "DED 13", ROMX

TrumbeakDEDData:: INCBIN "audio/ded/trumbeak.ded"
WailmerDEDData:: INCBIN "audio/ded/wailmer.ded"
FinneonDEDData:: INCBIN "audio/ded/finneon.ded"

SECTION "DED 14", ROMX

RhyperiorDEDData:: INCBIN "audio/ded/rhyperior.ded"
SharpedoDEDData:: INCBIN "audio/ded/sharpedo.ded"
LatiosDEDData:: INCBIN "audio/ded/latios.ded"
MunchlaxDEDData:: INCBIN "audio/ded/munchlax.ded"

SECTION "DED 15", ROMX

LeafeonDEDData:: INCBIN "audio/ded/leafeon.ded"
SalanditDEDData:: INCBIN "audio/ded/salandit.ded"
LycanrocDuskDEDData:: INCBIN "audio/ded/lycanroc_dusk.ded"
LatiasDEDData:: INCBIN "audio/ded/latias.ded"

SECTION "DED 16", ROMX

TangrowthDEDData:: INCBIN "audio/ded/tangrowth.ded"
RelicanthDEDData:: INCBIN "audio/ded/relicanth.ded"
LycanrocMiddayDEDData:: INCBIN "audio/ded/lycanroc_midday.ded"
CutieflyDEDData:: INCBIN "audio/ded/cutiefly.ded"

SECTION "DED 17", ROMX

ChatotDEDData:: INCBIN "audio/ded/chatot.ded"
VibravaDEDData:: INCBIN "audio/ded/vibrava.ded"
MimeJrDEDData:: INCBIN "audio/ded/mime__jr.ded"
SpindaDEDData:: INCBIN "audio/ded/spinda.ded"
WingullDEDData:: INCBIN "audio/ded/wingull.ded"

SECTION "DED 18", ROMX

PelipperDEDData:: INCBIN "audio/ded/pelipper.ded"
AzurillDEDData:: INCBIN "audio/ded/azurill.ded"
PikipekDEDData:: INCBIN "audio/ded/pikipek.ded"
ChimechoDEDData:: INCBIN "audio/ded/chimecho.ded"
HappinyDEDData:: INCBIN "audio/ded/happiny.ded"
CarvanhaDEDData:: INCBIN "audio/ded/carvanha.ded"

SECTION "DED 19", ROMX

RockruffDEDData:: INCBIN "audio/ded/rockruff.ded"
TrapinchDEDData:: INCBIN "audio/ded/trapinch.ded"
