; Auto-generated by dedgen.py

SECTION "DED 1", ROMX, BANK[DED_1]

DragalgeDEDData:: INCBIN "audio/ded/dragalge.ded"
SylveonDEDData:: INCBIN "audio/ded/sylveon.ded"

SECTION "DED 2", ROMX, BANK[DED_2]

TogekissDEDData:: INCBIN "audio/ded/togekiss.ded"
Porygon_zDEDData:: INCBIN "audio/ded/porygon_z.ded"

SECTION "DED 3", ROMX, BANK[DED_3]

ElectivireDEDData:: INCBIN "audio/ded/electivire.ded"
MarshadowDEDData:: INCBIN "audio/ded/marshadow.ded"

SECTION "DED 4", ROMX, BANK[DED_4]

SalazzleDEDData:: INCBIN "audio/ded/salazzle.ded"
PalossandDEDData:: INCBIN "audio/ded/palossand.ded"

SECTION "DED 5", ROMX, BANK[DED_5]

GlaceonDEDData:: INCBIN "audio/ded/glaceon.ded"
MagnezoneDEDData:: INCBIN "audio/ded/magnezone.ded"

SECTION "DED 6", ROMX, BANK[DED_6]

ToucannonDEDData:: INCBIN "audio/ded/toucannon.ded"
LumineonDEDData:: INCBIN "audio/ded/lumineon.ded"

SECTION "DED 7", ROMX, BANK[DED_7]

WailordDEDData:: INCBIN "audio/ded/wailord.ded"
ToxapexDEDData:: INCBIN "audio/ded/toxapex.ded"

SECTION "DED 8", ROMX, BANK[DED_8]

Lycanroc_midnightDEDData:: INCBIN "audio/ded/lycanroc_midnight.ded"
SandygastDEDData:: INCBIN "audio/ded/sandygast.ded"
ChimechoDEDData:: INCBIN "audio/ded/chimecho.ded"

SECTION "DED 9", ROMX, BANK[DED_9]

TropiusDEDData:: INCBIN "audio/ded/tropius.ded"
ChinglingDEDData:: INCBIN "audio/ded/chingling.ded"
SkrelpDEDData:: INCBIN "audio/ded/skrelp.ded"

SECTION "DED 10", ROMX, BANK[DED_10]

RhyperiorDEDData:: INCBIN "audio/ded/rhyperior.ded"
FlygonDEDData:: INCBIN "audio/ded/flygon.ded"
LatiosDEDData:: INCBIN "audio/ded/latios.ded"

SECTION "DED 11", ROMX, BANK[DED_11]

RibombeeDEDData:: INCBIN "audio/ded/ribombee.ded"
FinneonDEDData:: INCBIN "audio/ded/finneon.ded"
RelicanthDEDData:: INCBIN "audio/ded/relicanth.ded"

SECTION "DED 12", ROMX, BANK[DED_12]

WailmerDEDData:: INCBIN "audio/ded/wailmer.ded"
MagmortarDEDData:: INCBIN "audio/ded/magmortar.ded"
LeafeonDEDData:: INCBIN "audio/ded/leafeon.ded"

SECTION "DED 13", ROMX, BANK[DED_13]

TurtonatorDEDData:: INCBIN "audio/ded/turtonator.ded"
LickilickyDEDData:: INCBIN "audio/ded/lickilicky.ded"
TrumbeakDEDData:: INCBIN "audio/ded/trumbeak.ded"

SECTION "DED 14", ROMX, BANK[DED_14]

StunfiskDEDData:: INCBIN "audio/ded/stunfisk.ded"
SharpedoDEDData:: INCBIN "audio/ded/sharpedo.ded"
TangrowthDEDData:: INCBIN "audio/ded/tangrowth.ded"

SECTION "DED 15", ROMX, BANK[DED_15]

MimikyuDEDData:: INCBIN "audio/ded/mimikyu.ded"
Lycanroc_duskDEDData:: INCBIN "audio/ded/lycanroc_dusk.ded"
SalanditDEDData:: INCBIN "audio/ded/salandit.ded"
CarvanhaDEDData:: INCBIN "audio/ded/carvanha.ded"

SECTION "DED 16", ROMX, BANK[DED_16]

MareanieDEDData:: INCBIN "audio/ded/mareanie.ded"
VibravaDEDData:: INCBIN "audio/ded/vibrava.ded"
Lycanroc_middayDEDData:: INCBIN "audio/ded/lycanroc_midday.ded"
Mime__jrDEDData:: INCBIN "audio/ded/mime__jr.ded"

SECTION "DED 17", ROMX, BANK[DED_17]

SpindaDEDData:: INCBIN "audio/ded/spinda.ded"
ChatotDEDData:: INCBIN "audio/ded/chatot.ded"
HappinyDEDData:: INCBIN "audio/ded/happiny.ded"
WingullDEDData:: INCBIN "audio/ded/wingull.ded"
LatiasDEDData:: INCBIN "audio/ded/latias.ded"

SECTION "DED 18", ROMX, BANK[DED_18]

CutieflyDEDData:: INCBIN "audio/ded/cutiefly.ded"
MantykeDEDData:: INCBIN "audio/ded/mantyke.ded"
AzurillDEDData:: INCBIN "audio/ded/azurill.ded"
MunchlaxDEDData:: INCBIN "audio/ded/munchlax.ded"
PelipperDEDData:: INCBIN "audio/ded/pelipper.ded"
KecleonDEDData:: INCBIN "audio/ded/kecleon.ded"

SECTION "DED 19", ROMX, BANK[DED_19]

RockruffDEDData:: INCBIN "audio/ded/rockruff.ded"
TrapinchDEDData:: INCBIN "audio/ded/trapinch.ded"
PikipekDEDData:: INCBIN "audio/ded/pikipek.ded"
