MapGroupPointers::
; pointers to the first map header of each map group
	dw MapGroup1
	dw MapGroup2
	dw MapGroup3
	dw MapGroup4
	dw MapGroup5
	dw MapGroup6
	dw MapGroup7
	dw MapGroup8
	dw MapGroup9
	dw MapGroup10
	dw MapGroup11
	dw MapGroup12
	dw MapGroup13
	dw MapGroup14


MapGroup1:
	map_header Route53, TILESET_JOHTO_1, ROUTE, ROUTE_53, MUSIC_ROUTE_29, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route54, TILESET_JOHTO_1, ROUTE, ROUTE_54, MUSIC_ROUTE_29, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header MandarinNorth, TILESET_JOHTO_1, TOWN, MANDARIN_NORTH, MUSIC_CIANWOOD_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header MandarinNorthPokeCenter, TILESET_POKECENTER, INDOOR, MANDARIN_NORTH, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MandarinNorthNameRater, TILESET_HOUSE_1, INDOOR, MANDARIN_NORTH, MUSIC_CIANWOOD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MandarinNorthSmallHouse, TILESET_HOUSE_1, INDOOR, MANDARIN_NORTH, MUSIC_CIANWOOD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MandarinNorthLargeHouse, TILESET_HOUSE_1, INDOOR, MANDARIN_NORTH, MUSIC_CIANWOOD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MandarinUnderground, TILESET_UNDERGROUND, DUNGEON, MANDARIN_NORTH, MUSIC_ROCKET_OVERTURE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MandarinNorthMart, TILESET_MART, INDOOR, MANDARIN_NORTH, MUSIC_CIANWOOD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE

MapGroup2:
	map_header TangeloJungle, TILESET_ILEX_FOREST, CAVE, TANGELO_JUNGLE, MUSIC_UNION_CAVE, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header MtNavel1F, TILESET_CAVE, CAVE, MT_NAVEL, MUSIC_VICTORY_ROAD, 0, PALETTE_NITE, FISHGROUP_NONE
	map_header MtNavel2F, TILESET_ICE_PATH, CAVE, MT_NAVEL, MUSIC_VICTORY_ROAD, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header MtNavelPeak, TILESET_ICE_PATH, CAVE, MT_NAVEL, MUSIC_VICTORY_ROAD, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header MtNavelIceRock, TILESET_ICE_PATH, CAVE, MT_NAVEL, MUSIC_VICTORY_ROAD, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CrystalCave1F, TILESET_CAVE, DUNGEON, CRYSTAL_CAVE, MUSIC_CAVE_OF_ORIGIN, 0, PALETTE_MORN, FISHGROUP_POND
	map_header CrystalCaveB1, TILESET_CAVE, DUNGEON, CRYSTAL_CAVE, MUSIC_CAVE_OF_ORIGIN, 0, PALETTE_MORN, FISHGROUP_POND
	map_header MandarinDesert, TILESET_DESERT, DUNGEON, MANDARIN_DESERT, MUSIC_RUINS_OF_ALPH_RADIO, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header SewerEntrance, TILESET_GYM_1, INDOOR, TROVITOPOLIS, MUSIC_UNION_CAVE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TrovitopolisSewer, TILESET_SEWER, DUNGEON, TROVITOPOLIS, MUSIC_UNION_CAVE, 0, PALETTE_NITE, FISHGROUP_SEWER
	map_header GoldenIsland, TILESET_GOLDEN_ISLAND, ROUTE, GOLDEN_ISLAND, MUSIC_POKEMON_MARCH, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route60, TILESET_JOHTO_1, ROUTE, ROUTE_60, MUSIC_ROUTE_29, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header SunrayCaveMandarinDesert1F, TILESET_CAVE, DUNGEON, MANDARIN_DESERT, MUSIC_RUINS_OF_ALPH_RADIO, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TrovitaIsland, TILESET_JOHTO_1, TOWN, TROVITA_ISLAND, MUSIC_CIANWOOD_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header FukuharaNo4BF1, TILESET_CAVE, DUNGEON, FUKUHARA_4, MUSIC_DARK_CAVE, 0, PALETTE_DARK, FISHGROUP_POND
	map_header FukuharaNo4BF2, TILESET_CAVE, DUNGEON, FUKUHARA_4, MUSIC_DARK_CAVE, 0, PALETTE_DARK, FISHGROUP_POND
	map_header FukuharaNo4BF3, TILESET_CAVE, DUNGEON, FUKUHARA_4, MUSIC_DARK_CAVE, 0, PALETTE_DARK, FISHGROUP_POND

MapGroup3:
	map_header Route57, TILESET_JOHTO_1, ROUTE, ROUTE_57, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header KinnowIslandRoute57Gate, TILESET_GATE, GATE, ROUTE_57, MUSIC_ROUTE_36, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route57GateUpstairs, TILESET_GATE, GATE, ROUTE_57, MUSIC_ROUTE_36, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header UnnamedIsland1, TILESET_JOHTO_1, ROUTE, UNNAMED_ISLAND_1, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header UnnamedIsland1PokeCenter, TILESET_POKECENTER, INDOOR, UNNAMED_ISLAND_1, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route58, TILESET_JOHTO_1, ROUTE, ROUTE_58, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header NavelIsland, TILESET_JOHTO_1, ROUTE, NAVEL_ISLAND, MUSIC_VICTORY_ROAD, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header SevenGrapefruits, TILESET_JOHTO_1, ROUTE, GRAPEFRUIT, MUSIC_MOBILE_ADAPTER, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header SevenGrapefruitsUnderwater, TILESET_UNDERWATER, ROUTE, GRAPEFRUIT, MUSIC_NONE, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header Route59, TILESET_JOHTO_1, ROUTE, ROUTE_59, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header GrapefruitStore, TILESET_MART, INDOOR, GRAPEFRUIT, MUSIC_MOBILE_ADAPTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MoroIsland, TILESET_JOHTO_1, TOWN, MORO_ISLAND, MUSIC_SOOTOPOLIS_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header MoroIslandMuseum, TILESET_MUSEUM, INDOOR, MORO_ISLAND, MUSIC_BATTLE_TOWER_LOBBY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MoroFishingHouse, TILESET_HOUSE_1, INDOOR, MORO_ISLAND, MUSIC_SOOTOPOLIS_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MoroSouthHouse, TILESET_HOUSE_1, INDOOR, MORO_ISLAND, MUSIC_SOOTOPOLIS_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MoroHouse1, TILESET_HOUSE_1, INDOOR, MORO_ISLAND, MUSIC_SOOTOPOLIS_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MoroHouse2, TILESET_HOUSE_1, INDOOR, MORO_ISLAND, MUSIC_SOOTOPOLIS_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MoroPokeCenter, TILESET_POKECENTER, INDOOR, MORO_ISLAND, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MoroMart, TILESET_MART, INDOOR, MORO_ISLAND, MUSIC_SOOTOPOLIS_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CleopatraIsland, TILESET_JOHTO_1, ROUTE, CLEOPATRA_ISLAND, MUSIC_ROUTE_26, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route57North, TILESET_JOHTO_1, ROUTE, ROUTE_57, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route63EastWest, TILESET_JOHTO_1, ROUTE, ROUTE_63, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route63NorthSouth, TILESET_JOHTO_1, ROUTE, ROUTE_63, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_SHORE

MapGroup4:
	map_header Route55, TILESET_JOHTO_1, ROUTE, ROUTE_55, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route55Underwater, TILESET_UNDERWATER, ROUTE, ROUTE_55, MUSIC_NONE, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header PinkanIsland, TILESET_JOHTO_1, ROUTE, PINKAN_ISLAND, MUSIC_MOBILE_ADAPTER, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route56West, TILESET_JOHTO_1, ROUTE, ROUTE_56, MUSIC_ROUTE_12, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route56East, TILESET_JOHTO_1, ROUTE, ROUTE_56, MUSIC_ROUTE_12, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route55QuestHouse, TILESET_KURT_HOUSE, INDOOR, ROUTE_55, MUSIC_ROUTE_36, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route56PokeCenter, TILESET_POKECENTER, INDOOR, ROUTE_56, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header KinnowIsland, TILESET_JOHTO_1, TOWN, KINNOW_ISLAND, MUSIC_GOLDENROD_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header KinnowTradeHouse, TILESET_HOUSE_1, INDOOR, KINNOW_ISLAND, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header KinnowLoreHouse, TILESET_HOUSE_1, INDOOR, KINNOW_ISLAND, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header KinnowCharcoalHouse, TILESET_KURT_HOUSE, INDOOR, KINNOW_ISLAND, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header KinnowPokeCenter, TILESET_POKECENTER, INDOOR, KINNOW_ISLAND, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header KinnowMart, TILESET_MART, INDOOR, KINNOW_ISLAND, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header KinnowCafe, TILESET_GAME_CORNER, INDOOR, KINNOW_ISLAND, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header KinnowSkateShop, TILESET_OLIVINE_GYM, INDOOR, KINNOW_ISLAND, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE

MapGroup5:
	map_header Route52TangeloJungleGate, TILESET_GATE, GATE, ROUTE_52, MUSIC_ROUTE_36, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route52, TILESET_JOHTO_1, ROUTE, ROUTE_52, MUSIC_ROUTE_30, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header MikanIsland, TILESET_JOHTO_1, TOWN, MIKAN_ISLAND, MUSIC_SOOTOPOLIS_CITY, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header MikanMart, TILESET_MART, INDOOR, MIKAN_ISLAND, MUSIC_SOOTOPOLIS_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MikanGym, TILESET_PORT, INDOOR, MIKAN_ISLAND, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header MikanNicknameSpeechHouse, TILESET_KURT_HOUSE, INDOOR, MIKAN_ISLAND, MUSIC_SOOTOPOLIS_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MikanPokeCenter1F, TILESET_POKECENTER, INDOOR, MIKAN_ISLAND, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MikanOnixTradeHouse, TILESET_KURT_HOUSE, INDOOR, MIKAN_ISLAND, MUSIC_SOOTOPOLIS_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MikanIslandRoute53Gate, TILESET_GATE, GATE, ROUTE_53, MUSIC_ROUTE_29, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route53GateUpstairs, TILESET_GATE, GATE, ROUTE_53, MUSIC_ROUTE_29, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route52PokeCenter1F, TILESET_POKECENTER, INDOOR, ROUTE_52, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE

MapGroup6:
	map_header MoroRoute60Gate, TILESET_GATE, GATE, ROUTE_60, MUSIC_ROUTE_29, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route60GateUpstairs, TILESET_GATE, GATE, ROUTE_60, MUSIC_ROUTE_29, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header WreckedShip, TILESET_UNDERWATER, ROUTE, WRECKED_SHIP, MUSIC_NONE, 0, PALETTE_NITE, FISHGROUP_SHORE
	map_header WreckedShipUnderwater, TILESET_UNDERWATER, DUNGEON, WRECKED_SHIP, MUSIC_NONE, 0, PALETTE_NITE, FISHGROUP_SHORE
	map_header WreckedShipUnsunk, TILESET_LIGHTHOUSE, DUNGEON, WRECKED_SHIP, MUSIC_NONE, 0, PALETTE_NITE, FISHGROUP_SHORE
	map_header GoldenIslandHouse1, TILESET_KURT_HOUSE, INDOOR, GOLDEN_ISLAND, MUSIC_POKEMON_MARCH, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenIslandHouse2, TILESET_KURT_HOUSE, INDOOR, GOLDEN_ISLAND, MUSIC_POKEMON_MARCH, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenIslandHouse3, TILESET_KURT_HOUSE, INDOOR, GOLDEN_ISLAND, MUSIC_POKEMON_MARCH, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenIslandElderHouse, TILESET_KURT_HOUSE, INDOOR, GOLDEN_ISLAND, MUSIC_BURNED_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenIslandGateHouse, TILESET_KURT_HOUSE, GATE, GOLDEN_ISLAND, MUSIC_POKEMON_MARCH, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route61, TILESET_JOHTO_1, ROUTE, ROUTE_61, MUSIC_ROUTE_37, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header MurcottIsland, TILESET_JOHTO_1, TOWN, MURCOTT_ISLAND, MUSIC_HOENN_DEWFORD_TOWN, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header DayCare, TILESET_HOUSE_1, INDOOR, MURCOTT_ISLAND, MUSIC_HOENN_DEWFORD_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MurcottHouse1, TILESET_HOUSE_1, INDOOR, MURCOTT_ISLAND, MUSIC_HOENN_DEWFORD_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MurcottHouse2, TILESET_HOUSE_1, INDOOR, MURCOTT_ISLAND, MUSIC_HOENN_DEWFORD_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MurcottHouse3, TILESET_HOUSE_1, INDOOR, MURCOTT_ISLAND, MUSIC_HOENN_DEWFORD_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MurcottPokeCenter, TILESET_POKECENTER, INDOOR, MURCOTT_ISLAND, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MurcottPokeMart, TILESET_MART, INDOOR, MURCOTT_ISLAND, MUSIC_HOENN_DEWFORD_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header UnnamedIsland2, TILESET_JOHTO_1, ROUTE, UNNAMED_ISLAND_2, MUSIC_ROUTE_37, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header FishingContest, TILESET_JOHTO_1, ROUTE, UNNAMED_ISLAND_2, MUSIC_ROUTE_37, 0, PALETTE_AUTO, FISHGROUP_CONTEST
	map_header Route62, TILESET_JOHTO_1, ROUTE, ROUTE_62, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header Route62MandarinDesertGate, TILESET_GATE, GATE, ROUTE_62, MUSIC_ROUTE_36, 0, PALETTE_DAY, FISHGROUP_SHORE


MapGroup7:
	map_header PalletTown, TILESET_KANTO, TOWN, PALLET_TOWN, MUSIC_PALLET_TOWN, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header RedsHouse1F, TILESET_KRISS_HOUSE, INDOOR, PALLET_TOWN, MUSIC_PALLET_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header RedsHouse2F, TILESET_KRISS_HOUSE, INDOOR, PALLET_TOWN, MUSIC_PALLET_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header BluesHouse, TILESET_HOUSE_1, INDOOR, PALLET_TOWN, MUSIC_PALLET_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header OaksLab, TILESET_LAB, INDOOR, PALLET_TOWN, MUSIC_POKEMON_TALK, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header VermilionCity, TILESET_KANTO, TOWN, VERMILION_CITY, MUSIC_VERMILION_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE

MapGroup8:
	map_header ValenciaPort, TILESET_PORT, ROUTE, ROUTE_49, MUSIC_EVER_GRANDE_CITY, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header TangeloPort, TILESET_PORT, ROUTE, TANGELO_ISLAND, MUSIC_HOENN_DEWFORD_TOWN, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header Trovitopolis, TILESET_JOHTO_1, TOWN, TROVITOPOLIS, MUSIC_GOLDENROD_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header TrovitopolisDeptStore1F, TILESET_MART, INDOOR, TROVITOPOLIS, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TrovitopolisDeptStore2F, TILESET_MART, INDOOR, TROVITOPOLIS, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TrovitopolisDeptStore3F, TILESET_MART, INDOOR, TROVITOPOLIS, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TrovitopolisDeptStore4F, TILESET_MART, INDOOR, TROVITOPOLIS, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TrovitopolisDeptStore5F, TILESET_MART, INDOOR, TROVITOPOLIS, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TrovitopolisDeptStore6F, TILESET_MART, INDOOR, TROVITOPOLIS, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TrovitopolisDeptStoreElevator, TILESET_MART, INDOOR, TROVITOPOLIS, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TrovitopolisDeptStoreRoof, TILESET_MART, INDOOR, TROVITOPOLIS, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TrovitopolisPokeCommCenter, TILESET_POKECOM_CENTER, INDOOR, TROVITOPOLIS, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TrovitopolisMrFlashHouse, TILESET_HOUSE_1, INDOOR, TROVITOPOLIS, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TrovitopolisMoveDeleterHouse, TILESET_HOUSE_1, INDOOR, TROVITOPOLIS, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TrovitopolisHouse1, TILESET_HOUSE_1, INDOOR, TROVITOPOLIS, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TrovitopolisHouse2, TILESET_HOUSE_1, INDOOR, TROVITOPOLIS, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TrovitopolisHouse3, TILESET_HOUSE_1, INDOOR, TROVITOPOLIS, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TrovitopolisHouse4, TILESET_HOUSE_1, INDOOR, TROVITOPOLIS, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TrovitopolisPort, TILESET_PORT, ROUTE, TROVITOPOLIS, MUSIC_GOLDENROD_CITY, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header MayorsOffice, TILESET_POWER_PLANT, INDOOR, TROVITOPOLIS, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MayorsOfficeMeetingRoom, TILESET_POWER_PLANT, INDOOR, TROVITOPOLIS, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TrovitaPort, TILESET_PORT, ROUTE, TROVITA_ISLAND, MUSIC_CIANWOOD_CITY, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header TrovitaGym, TILESET_GYM_1, INDOOR, TROVITA_ISLAND, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header TrovitopolisPrimaSchool, TILESET_LAB, INDOOR, TROVITOPOLIS, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE

MapGroup9:
	map_header AscorbiaIsland, TILESET_JOHTO_1, TOWN, ASCORBIA_ISLAND, MUSIC_AZALEA_TOWN, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header AscorbiaIslandFanClub, TILESET_POWER_PLANT, INDOOR, ASCORBIA_ISLAND, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header AscorbiaIslandMoveRelearner, TILESET_HOUSE_1, INDOOR, ASCORBIA_ISLAND, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header AscorbiaIslandHouse1, TILESET_HOUSE_1, INDOOR, ASCORBIA_ISLAND, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header AscorbiaIslandHouse2, TILESET_HOUSE_1, INDOOR, ASCORBIA_ISLAND, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header AscorbiaIslandRoute63Gate, TILESET_GATE, GATE, ROUTE_63, MUSIC_ROUTE_36, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header AscorbiaIslandMart, TILESET_MART, INDOOR, ASCORBIA_ISLAND, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header AscorbiaIslandCenter, TILESET_POKECENTER, INDOOR, ASCORBIA_ISLAND, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE

MapGroup10:
	map_header PokeCenter2F, TILESET_POKECOM_CENTER, INDOOR, SPECIAL_MAP, MUSIC_POKEMON_CENTER, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header TradeCenter, TILESET_GATE, INDOOR, SPECIAL_MAP, MUSIC_CHERRYGROVE_CITY, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header Colosseum, TILESET_GATE, INDOOR, SPECIAL_MAP, MUSIC_CHERRYGROVE_CITY, 1, PALETTE_DAY, FISHGROUP_SHORE

MapGroup11:
	map_header Route49, TILESET_JOHTO_1, ROUTE, ROUTE_49, MUSIC_ROUTE_1, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header ValenciaIsland, TILESET_JOHTO_1, TOWN, VALENCIA_ISLAND, MUSIC_EVER_GRANDE_CITY, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header IvysLab, TILESET_LAB, INDOOR, VALENCIA_ISLAND, MUSIC_PROF_ELM, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header KrissHouse1F, TILESET_KRISS_HOUSE, INDOOR, VALENCIA_ISLAND, MUSIC_EVER_GRANDE_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header KrissHouse2F, TILESET_KRISS_HOUSE_2F, INDOOR, VALENCIA_ISLAND, MUSIC_EVER_GRANDE_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header KrissNeighborsHouse, TILESET_HOUSE_1, INDOOR, VALENCIA_ISLAND, MUSIC_EVER_GRANDE_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header IvysHouse, TILESET_KRISS_HOUSE, INDOOR, VALENCIA_ISLAND, MUSIC_EVER_GRANDE_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header ValenciaTangeloRoute49, TILESET_JOHTO_1, ROUTE, ROUTE_49, MUSIC_ROUTE_1, 0, PALETTE_AUTO, FISHGROUP_SHORE

MapGroup12:
	map_header Route50, TILESET_JOHTO_1, ROUTE, ROUTE_50, MUSIC_ROUTE_30, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route51, TILESET_JOHTO_1, ROUTE, ROUTE_51, MUSIC_ROUTE_30, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route51TangeloJungleGate, TILESET_GATE, GATE, ROUTE_51, MUSIC_ROUTE_30, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route51GateUpstairs, TILESET_GATE, GATE, ROUTE_51, MUSIC_ROUTE_30, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TangeloIsland, TILESET_JOHTO_1, TOWN, TANGELO_ISLAND, MUSIC_HOENN_DEWFORD_TOWN, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header TangeloMart, TILESET_MART, INDOOR, TANGELO_ISLAND, MUSIC_HOENN_DEWFORD_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TangeloPokeCenter1F, TILESET_POKECENTER, INDOOR, TANGELO_ISLAND, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TangeloGymSpeechHouse, TILESET_HOUSE_1, INDOOR, TANGELO_ISLAND, MUSIC_HOENN_DEWFORD_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TangeloEvolutionSpeechHouse, TILESET_HOUSE_1, INDOOR, TANGELO_ISLAND, MUSIC_HOENN_DEWFORD_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE

MapGroup13:
	map_header SunburstIsland, TILESET_JOHTO_1, TOWN, SUNBURST_ISLAND, MUSIC_SLATEPORT_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header SunburstPokeCenter, TILESET_POKECENTER, INDOOR, SUNBURST_ISLAND, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header SunburstSmallHouse, TILESET_HOUSE_1, INDOOR, SUNBURST_ISLAND, MUSIC_SLATEPORT_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header SunburstLargeHouse, TILESET_HOUSE_1, INDOOR, SUNBURST_ISLAND, MUSIC_SLATEPORT_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header SunburstSouthHouse, TILESET_HOUSE_1, INDOOR, SUNBURST_ISLAND, MUSIC_SLATEPORT_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header SunburstCrystalShop, TILESET_MART, INDOOR, SUNBURST_ISLAND, MUSIC_SLATEPORT_CITY, 0, PALETTE_NITE, FISHGROUP_SHORE
	
MapGroup14:
	map_header PummeloIsland, TILESET_JOHTO_1, TOWN, PUMMELO_ISLAND, MUSIC_LILYCOVE_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header HallOfFame, TILESET_ICE_PATH, INDOOR, PUMMELO_ISLAND, MUSIC_LILYCOVE_CITY, 1, PALETTE_DAY, FISHGROUP_SHORE