	dw NormalHit
	dw DoSleep
	dw PoisonHit
	dw LeechHit
	dw BurnHit
	dw FreezeHit
	dw ParalyzeHit
	dw Explosion
	dw DreamEater
	dw MirrorMove
	dw AttackUp
	dw DefenseUp
	dw SpeedUp
	dw SpecialAttackUp
	dw SpecialDefenseUp
	dw AccuracyUp
	dw EvasionUp
	dw NormalHit
	dw AttackDown
	dw DefenseDown
	dw SpeedDown
	dw SpecialAttackDown
	dw SpecialDefenseDown
	dw AccuracyDown
	dw EvasionDown
	dw Haze
	dw Rampage
	dw Whirlwind
	dw MultiHit
	dw Conversion
	dw FlinchHit
	dw Heal
	dw DoPoison
	dw PayDay
	dw Screen
	dw TriAttack
	dw OHKOHit
	dw StaticDamage
	dw StaticDamage
	dw Trap
	dw MultiHit
	dw NormalHit
	dw Mist
	dw CriticalUp
	dw RecoilHit
	dw DoConfuse
	dw AttackUp2
	dw DefenseUp2
	dw SpeedUp2
	dw SpecialAttackUp2
	dw SpecialDefenseUp2
	dw AccuracyUp2
	dw EvasionUp2
	dw Transform
	dw AttackDown2
	dw DefenseDown2
	dw SpeedDown2
	dw SpecialAttackDown2
	dw SpecialDefenseDown2
	dw AccuracyDown2
	dw EvasionDown2
	dw Screen
	dw DoPoison
	dw DoParalyze
	dw AttackDownHit
	dw DefenseDownHit
	dw SpeedDownHit
	dw SpecialAttackDownHit
	dw SpecialDefenseDownHit
	dw AccuracyDownHit
	dw EvasionDownHit
	dw SkyAttack
	dw ConfuseHit
	dw PoisonMultiHit
	dw Substitute
	dw HyperBeam
	dw Rage
	dw Mimic
	dw Metronome
	dw LeechSeed
	dw Splash
	dw Disable
	dw StaticDamage
	dw Counter
	dw Encore
	dw Facade
	dw Conversion2
	dw LockOn
	dw Sketch
	dw DefrostOpponent
	dw SleepTalk
	dw DestinyBond
	dw Reversal
	dw FalseSwipe
	dw HealBell
	dw NormalHit
	dw TripleKick
	dw Thief
	dw MeanLook
	dw FlameWheel
	dw Curse
	dw Protect
	dw Spikes
	dw Foresight
	dw PerishSong
	dw Sandstorm
	dw Endure
	dw Rollout
	dw Swagger
	dw Attract
	dw Return
	dw Frustration
	dw Safeguard
	dw SacredFire
	dw Magnitude
	dw BatonPass
	dw Pursuit
	dw RapidSpin
	dw MorningSun
	dw Synthesis
	dw Moonlight
	dw VoltTackle
	dw RainDance
	dw SunnyDay
	dw DefenseUpHit
	dw AttackUpHit
	dw AllUpHit
	dw FakeOut
	dw BellyDrum
	dw MirrorCoat
	dw Earthquake
	dw FutureSight
	dw Gust
	dw Stomp
	dw Solarbeam
	dw Thunder
	dw Teleport
	dw Fly
	dw DefenseCurl
	dw Psystrike
	dw SpectralThief
	dw Hail
	dw ShellTrap
	dw Venoshock
	dw BugBite
	dw Surf
	dw Whirlpool
	dw Blizzard
	dw DragonTail
