SightSeerSpriteGFX:			INCBIN "gfx/overworld/102.2bpp"
BugBoySpriteGFX:			INCBIN "gfx/overworld/103.2bpp"
PcSlouchGFX:				INCBIN "gfx/overworld/104.2bpp"
JessieSpriteGFX:			INCBIN "gfx/overworld/105.2bpp"
JamesSpriteGFX:				INCBIN "gfx/overworld/106.2bpp"
CatManSpriteGFX:			INCBIN "gfx/overworld/107.2bpp"
RocketMeowthSpriteGFX:		INCBIN "gfx/overworld/108.2bpp"
ChrisDiveSpriteGFX:			INCBIN "gfx/overworld/109.2bpp"
KrisDiveSpriteGFX:			INCBIN "gfx/overworld/110.2bpp"
InvisibleSpriteGFX:			INCBIN "gfx/overworld/111.2bpp"
KarenSpriteGFX:       	    INCBIN "gfx/overworld/026.2bpp" ; c2580
MayorSpriteGFX:				INCBIN "gfx/overworld/112.2bpp"