; Control characters
	charmap "<START>",  $00
	charmap "<DAY>",    $15
	charmap "<WBR>",    $1f
	charmap "<LNBRK>",  $22
	charmap "%",        $25
	charmap "<ENEMY>",  $3f
	charmap "<SHINY>",  $3f
	charmap "<NEXT>",   $4e
	charmap "<LINE>",   $4f

	charmap "@",        $50
	charmap "<PARA>",   $51
	charmap "<PLAYER>", $52
	charmap "#",        $54
	charmap "<CONT>",   $55
	charmap "<DONE>",   $57
	charmap "<PROMPT>", $58
	charmap "<TARGET>", $59
	charmap "<USER>",   $5a
	
	charmap "☎", 		$BC ;this is not the mapping used in vanilla crystal

; battle extras
	charmap "<LV>",     $6e
	charmap "_",        $76

	charmap " ",        $7f

	charmap "A",        $80
	charmap "B",        $81
	charmap "C",        $82
	charmap "D",        $83
	charmap "E",        $84
	charmap "F",        $85
	charmap "G",        $86
	charmap "H",        $87
	charmap "I",        $88
	charmap "J",        $89
	charmap "K",        $8a
	charmap "L",        $8b
	charmap "M",        $8c
	charmap "N",        $8d
	charmap "O",        $8e
	charmap "P",        $8f
	charmap "Q",        $90
	charmap "R",        $91
	charmap "S",        $92
	charmap "T",        $93
	charmap "U",        $94
	charmap "V",        $95
	charmap "W",        $96
	charmap "X",        $97
	charmap "Y",        $98
	charmap "Z",        $99

	charmap "(",        $9a
	charmap ")",        $9b
	charmap ":",        $9c
	charmap ";",        $9d
	charmap "[",        $9e
	charmap "]",        $9f

	charmap "a",        $a0
	charmap "b",        $a1
	charmap "c",        $a2
	charmap "d",        $a3
	charmap "e",        $a4
	charmap "f",        $a5
	charmap "g",        $a6
	charmap "h",        $a7
	charmap "i",        $a8
	charmap "j",        $a9
	charmap "k",        $aa
	charmap "l",        $ab
	charmap "m",        $ac
	charmap "n",        $ad
	charmap "o",        $ae
	charmap "p",        $af
	charmap "q",        $b0
	charmap "r",        $b1
	charmap "s",        $b2
	charmap "t",        $b3
	charmap "u",        $b4
	charmap "v",        $b5
	charmap "w",        $b6
	charmap "x",        $b7
	charmap "y",        $b8
	charmap "z",        $b9

	charmap "′",        $ba
	charmap "″",        $bb

	charmap "'d",       $c0
	charmap "'l",       $c1
	charmap "'m",       $c2
	charmap "'r",       $c3
	charmap "'s",       $c4
	charmap "'t",       $c5
	charmap "'v",       $c6

	charmap "<UPDN>",   $c7
	charmap "<PO>",     $c8
	charmap "<KE>",     $c9
	charmap "<``>",     $ca
	charmap "<''>",     $cb
	charmap "<ID>",     $cc
	charmap "№",        $cd
	charmap "<...>",    $ce
	charmap "←",        $cf
	charmap "'",        $d0
	charmap "<PK>",     $d1
	charmap "<MN>",     $d2
	charmap "-",        $d3
	charmap "◀",        $d4
	charmap "▲",        $d5
	charmap "?",        $d6
	charmap "!",        $d7
	charmap ".",        $d8
	charmap "&",        $d9
	charmap "é",        $da
	charmap "→",        $db
	charmap "▷",        $dc
	charmap "▶",        $dd
	charmap "▼",        $de
	charmap "♂",        $df
	charmap "¥",        $e0
	charmap "×",        $e1
	charmap "·",        $e2
	charmap "/",        $e3
	charmap ",",        $e4
	charmap "♀",        $e5

	charmap "0",        $e6
	charmap "1",        $e7
	charmap "2",        $e8
	charmap "3",        $e9
	charmap "4",        $ea
	charmap "5",        $eb
	charmap "6",        $ec
	charmap "7",        $ed
	charmap "8",        $ee
	charmap "9",        $ef

	charmap "┌",        $fa
	charmap "─",        $fb
	charmap "┐",        $fc
	charmap "│",        $fd
	charmap "└",        $fe
	charmap "┘",        $ff
