IconPointers:
	dw NullIcon
	dw BulbasaurIcon
	dw IvysaurIcon
	dw VenusaurIcon
	dw CharmanderIcon
	dw CharmeleonIcon
	dw CharizardIcon
	dw SquirtleIcon
	dw WartortleIcon
	dw BlastoiseIcon
	dw CaterpieIcon
	dw MetapodIcon
	dw ButterfreeIcon
	dw WeedleIcon
	dw KakunaIcon
	dw BeedrillIcon
	dw PidgeyIcon
	dw PidgeottoIcon
	dw PidgeotIcon
	dw RattataIcon
	dw RaticateIcon
	dw SpearowIcon
	dw FearowIcon
	dw EkansIcon
	dw ArbokIcon
	dw PikachuIcon
	dw RaichuIcon
	dw SandshrewIcon
	dw SandslashIcon
	dw NidoranFIcon
	dw NidorinaIcon
	dw NidoqueenIcon
	dw NidoranMIcon
	dw NidorinoIcon
	dw NidokingIcon
	dw ClefairyIcon
	dw ClefableIcon
	dw VulpixIcon
	dw NinetalesIcon
	dw JigglypuffIcon
	dw WigglytuffIcon
	dw ZubatIcon
	dw GolbatIcon
	dw OddishIcon
	dw GloomIcon
	dw VileplumeIcon
	dw ParasIcon
	dw ParasectIcon
	dw VenonatIcon
	dw VenomothIcon
	dw DiglettIcon
	dw DugtrioIcon
	dw MeowthIcon
	dw PersianIcon
	dw PsyduckIcon
	dw GolduckIcon
	dw MankeyIcon
	dw PrimeapeIcon
	dw GrowlitheIcon
	dw ArcanineIcon
	dw PoliwagIcon
	dw PoliwhirlIcon
	dw PoliwrathIcon
	dw AbraIcon
	dw KadabraIcon
	dw AlakazamIcon
	dw MachopIcon
	dw MachokeIcon
	dw MachampIcon
	dw BellsproutIcon
	dw WeepinbellIcon
	dw VictreebelIcon
	dw TentacoolIcon
	dw TentacruelIcon
	dw GeodudeIcon
	dw GravelerIcon
	dw GolemIcon
	dw PonytaIcon
	dw RapidashIcon
	dw SlowpokeIcon
	dw SlowbroIcon
	dw MagnemiteIcon
	dw MagnetonIcon
	dw FarfetchdIcon
	dw DoduoIcon
	dw DodrioIcon
	dw SeelIcon
	dw DewgongIcon
	dw GrimerIcon
	dw MukIcon
	dw ShellderIcon
	dw CloysterIcon
	dw GastlyIcon
	dw HaunterIcon
	dw GengarIcon
	dw OnixIcon
	dw DrowzeeIcon
	dw HypnoIcon
	dw KrabbyIcon
	dw KinglerIcon
	dw VoltorbIcon
	dw ElectrodeIcon
	dw ExeggcuteIcon
	dw ExeggutorIcon
	dw CuboneIcon
	dw MarowakIcon
	dw HitmonleeIcon
	dw HitmonchanIcon
	dw LickitungIcon
	dw KoffingIcon
	dw WeezingIcon
	dw RhyhornIcon
	dw RhydonIcon
	dw ChanseyIcon
	dw TangelaIcon
	dw KangaskhanIcon
	dw HorseaIcon
	dw SeadraIcon
	dw GoldeenIcon
	dw SeakingIcon
	dw StaryuIcon
	dw StarmieIcon
	dw MrMimeIcon
	dw ScytherIcon
	dw JynxIcon
	dw ElectabuzzIcon
	dw MagmarIcon
	dw PinsirIcon
	dw TaurosIcon
	dw MagikarpIcon
	dw GyaradosIcon
	dw LaprasIcon
	dw DittoIcon
	dw EeveeIcon
	dw VaporeonIcon
	dw JolteonIcon
	dw FlareonIcon
	dw PorygonIcon
	dw OmanyteIcon
	dw OmastarIcon
	dw KabutoIcon
	dw KabutopsIcon
	dw AerodactylIcon
	dw SnorlaxIcon
	dw ArticunoIcon
	dw ZapdosIcon
	dw MoltresIcon
	dw DratiniIcon
	dw DragonairIcon
	dw DragoniteIcon
	dw MewtwoIcon
	dw MewIcon
	dw TropiusIcon
	dw KecleonIcon
	dw ChatotIcon
	dw PikipekIcon
	dw TrumbeakIcon
	dw ToucannonIcon
	dw MunchlaxIcon
	dw RockruffIcon
	dw LycanrocIcon
	dw WingullIcon
	dw PelipperIcon
	dw ChinglingIcon
	dw ChimechoIcon
	dw SalanditIcon
	dw SalazzleIcon
	dw FinneonIcon
	dw LumineonIcon
	dw CrobatIcon
	dw ChinchouIcon
	dw LanturnIcon
	dw PichuIcon
	dw CleffaIcon
	dw IgglybuffIcon
	dw TogepiIcon
	dw TogeticIcon
	dw TogekissIcon
	dw AzurillIcon
	dw MareepIcon
	dw FlaaffyIcon
	dw AmpharosIcon
	dw BellossomIcon
	dw MarillIcon
	dw AzumarillIcon
	dw MimeJrIcon
	dw PolitoedIcon
	dw HoppipIcon
	dw SkiploomIcon
	dw JumpluffIcon
	dw StunfiskIcon
	dw SunkernIcon
	dw SunfloraIcon
	dw LeafeonIcon
	dw GlaceonIcon
	dw SylveonIcon
	dw EspeonIcon
	dw UmbreonIcon
	dw RelicanthIcon
	dw SlowkingIcon
	dw MimikyuIcon
	dw SpindaIcon
	dw SkrelpIcon
	dw DragalgeIcon
	dw TrapinchIcon
	dw VibravaIcon
	dw FlygonIcon
	dw TurtonatorIcon
	dw SteelixIcon
	dw WailmerIcon
	dw WailordIcon
	dw QwilfishIcon
	dw ScizorIcon
	dw ShuckleIcon
	dw MareanieIcon
	dw ToxapexIcon
	dw SandygastIcon
	dw PalossandIcon
	dw SlugmaIcon
	dw MagcargoIcon
	dw CarvanhaIcon
	dw SharpedoIcon
	dw CorsolaIcon
	dw RemoraidIcon
	dw OctilleryIcon
	dw MantykeIcon
	dw MantineIcon
	dw SkarmoryIcon
	dw MagmortarIcon
	dw ElectivireIcon
	dw KingdraIcon
	dw PhanpyIcon
	dw DonphanIcon
	dw Porygon2Icon
	dw PorygonZIcon
	dw LickilickyIcon
	dw TyrogueIcon
	dw HitmontopIcon
	dw SmoochumIcon
	dw ElekidIcon
	dw MagbyIcon
	dw HappinyIcon
	dw BlisseyIcon
	dw CutieflyIcon
	dw RibombeeIcon
	dw TangrowthIcon
	dw RhyperiorIcon
	dw MagnezoneIcon
	dw MarshadowIcon
	dw LugiaIcon
	dw HoOhIcon
	dw CelebiIcon
	dw LatiasIcon
	dw LatiosIcon
	dw EggIcon
