ReadMonMenuIcon: ; 8eab3
	cp EGG
	jr z, .egg
	dec a
	ld hl, MonMenuIcons
	ld e, a
	ld d, 0
	add hl, de
	ld a, [hl]
	ret
.egg
	ld a, ICON_EGG
	ret
; 8eac4

MonMenuIcons: ; 8eac4
	db ICON_BULBASAUR
	db ICON_IVYSAUR
	db ICON_VENUSAUR
	db ICON_CHARMANDER
	db ICON_CHARMELEON
	db ICON_CHARIZARD
	db ICON_SQUIRTLE
	db ICON_WARTORTLE
	db ICON_BLASTOISE
	db ICON_CATERPIE
	db ICON_METAPOD
	db ICON_BUTTERFREE
	db ICON_WEEDLE
	db ICON_KAKUNA
	db ICON_BEEDRILL
	db ICON_PIDGEY
	db ICON_PIDGEOTTO
	db ICON_PIDGEOT
	db ICON_RATTATA
	db ICON_RATICATE
	db ICON_SPEAROW
	db ICON_FEAROW
	db ICON_EKANS
	db ICON_ARBOK
	db ICON_PIKACHU
	db ICON_RAICHU
	db ICON_SANDSHREW
	db ICON_SANDSLASH
	db ICON_NIDORAN_F
	db ICON_NIDORINA
	db ICON_NIDOQUEEN
	db ICON_NIDORAN_M
	db ICON_NIDORINO
	db ICON_NIDOKING
	db ICON_CLEFAIRY
	db ICON_CLEFABLE
	db ICON_VULPIX
	db ICON_NINETALES
	db ICON_JIGGLYPUFF
	db ICON_WIGGLYTUFF
	db ICON_ZUBAT
	db ICON_GOLBAT
	db ICON_ODDISH
	db ICON_GLOOM
	db ICON_VILEPLUME
	db ICON_PARAS
	db ICON_PARASECT
	db ICON_VENONAT
	db ICON_VENOMOTH
	db ICON_DIGLETT
	db ICON_DUGTRIO
	db ICON_MEOWTH
	db ICON_PERSIAN
	db ICON_PSYDUCK
	db ICON_GOLDUCK
	db ICON_MANKEY
	db ICON_PRIMEAPE
	db ICON_GROWLITHE
	db ICON_ARCANINE
	db ICON_POLIWAG
	db ICON_POLIWHIRL
	db ICON_POLIWRATH
	db ICON_ABRA
	db ICON_KADABRA
	db ICON_ALAKAZAM
	db ICON_MACHOP
	db ICON_MACHOKE
	db ICON_MACHAMP
	db ICON_BELLSPROUT
	db ICON_WEEPINBELL
	db ICON_VICTREEBEL
	db ICON_TENTACOOL
	db ICON_TENTACRUEL
	db ICON_GEODUDE
	db ICON_GRAVELER
	db ICON_GOLEM
	db ICON_PONYTA
	db ICON_RAPIDASH
	db ICON_SLOWPOKE
	db ICON_SLOWBRO
	db ICON_MAGNEMITE
	db ICON_MAGNETON
	db ICON_FARFETCH_D
	db ICON_DODUO
	db ICON_DODRIO
	db ICON_SEEL
	db ICON_DEWGONG
	db ICON_GRIMER
	db ICON_MUK
	db ICON_SHELLDER
	db ICON_CLOYSTER
	db ICON_GASTLY
	db ICON_HAUNTER
	db ICON_GENGAR
	db ICON_ONIX
	db ICON_DROWZEE
	db ICON_HYPNO
	db ICON_KRABBY
	db ICON_KINGLER
	db ICON_VOLTORB
	db ICON_ELECTRODE
	db ICON_EXEGGCUTE
	db ICON_EXEGGUTOR
	db ICON_CUBONE
	db ICON_MAROWAK
	db ICON_HITMONLEE
	db ICON_HITMONCHAN
	db ICON_LICKITUNG
	db ICON_KOFFING
	db ICON_WEEZING
	db ICON_RHYHORN
	db ICON_RHYDON
	db ICON_CHANSEY
	db ICON_TANGELA
	db ICON_KANGASKHAN
	db ICON_HORSEA
	db ICON_SEADRA
	db ICON_GOLDEEN
	db ICON_SEAKING
	db ICON_STARYU
	db ICON_STARMIE
	db ICON_MR__MIME
	db ICON_SCYTHER
	db ICON_JYNX
	db ICON_ELECTABUZZ
	db ICON_MAGMAR
	db ICON_PINSIR
	db ICON_TAUROS
	db ICON_MAGIKARP
	db ICON_GYARADOS
	db ICON_LAPRAS
	db ICON_DITTO
	db ICON_EEVEE
	db ICON_VAPOREON
	db ICON_JOLTEON
	db ICON_FLAREON
	db ICON_PORYGON
	db ICON_OMANYTE
	db ICON_OMASTAR
	db ICON_KABUTO
	db ICON_KABUTOPS
	db ICON_AERODACTYL
	db ICON_SNORLAX
	db ICON_ARTICUNO
	db ICON_ZAPDOS
	db ICON_MOLTRES
	db ICON_DRATINI
	db ICON_DRAGONAIR
	db ICON_DRAGONITE
	db ICON_MEWTWO
	db ICON_MEW
	db ICON_TROPIUS
	db ICON_KECLEON
	db ICON_CHATOT
	db ICON_PIKIPEK
	db ICON_TRUMBEAK
	db ICON_TOUCANNON
	db ICON_MUNCHLAX
	db ICON_MINCCINO
	db ICON_CINCCINO
	db ICON_WINGULL
	db ICON_PELIPPER
	db ICON_CHINGLING
	db ICON_CHIMECHO
	db ICON_SALANDIT
	db ICON_SALAZZLE
	db ICON_FINNEON
	db ICON_LUMINEON
	db ICON_CROBAT
	db ICON_CHINCHOU
	db ICON_LANTURN
	db ICON_PICHU
	db ICON_CLEFFA
	db ICON_IGGLYBUFF
	db ICON_TOGEPI
	db ICON_TOGETIC
	db ICON_TOGEKISS
	db ICON_AZURILL
	db ICON_MAREEP
	db ICON_FLAAFFY
	db ICON_AMPHAROS
	db ICON_BELLOSSOM
	db ICON_MARILL
	db ICON_AZUMARILL
	db ICON_MIME_JR
	db ICON_POLITOED
	db ICON_HOPPIP
	db ICON_SKIPLOOM
	db ICON_JUMPLUFF
	db ICON_STUNFISK
	db ICON_SUNKERN
	db ICON_SUNFLORA
	db ICON_LEAFEON
	db ICON_GLACEON
	db ICON_SYLVEON
	db ICON_ESPEON
	db ICON_UMBREON
	db ICON_RELICANTH
	db ICON_SLOWKING
	db ICON_MIMIKYU
	db ICON_SPINDA
	db ICON_SKRELP
	db ICON_DRAGALGE
	db ICON_TRAPINCH
	db ICON_VIBRAVA
	db ICON_FLYGON
	db ICON_TURTONATOR
	db ICON_STEELIX
	db ICON_WAILMER
	db ICON_WAILORD
	db ICON_QWILFISH
	db ICON_SCIZOR
	db ICON_SHUCKLE
	db ICON_MAREANIE
	db ICON_TOXAPEX
	db ICON_SANDYGAST
	db ICON_PALOSSAND
	db ICON_SLUGMA
	db ICON_MAGCARGO
	db ICON_CARVANHA
	db ICON_SHARPEDO
	db ICON_CORSOLA
	db ICON_REMORAID
	db ICON_OCTILLERY
	db ICON_MANTYKE
	db ICON_MANTINE
	db ICON_SKARMORY
	db ICON_MAGMORTAR
	db ICON_ELECTIVIRE
	db ICON_KINGDRA
	db ICON_PHANPY
	db ICON_DONPHAN
	db ICON_PORYGON2
	db ICON_PORYGON_Z
	db ICON_LICKILICKY
	db ICON_TYROGUE
	db ICON_HITMONTOP
	db ICON_SMOOCHUM
	db ICON_ELEKID
	db ICON_MAGBY
	db ICON_HAPPINY
	db ICON_BLISSEY
	db ICON_CUTIEFLY
	db ICON_RIBOMBEE
	db ICON_TANGROWTH
	db ICON_RHYPERIOR
	db ICON_MAGNEZONE
	db ICON_MARSHADOW
	db ICON_LUGIA
	db ICON_HO_OH
	db ICON_CELEBI
	db ICON_LATIAS
	db ICON_LATIOS


IconPointers:
	dw NullIcon
	dw BulbasaurIcon
	dw IvysaurIcon
	dw VenusaurIcon
	dw CharmanderIcon
	dw CharmeleonIcon
	dw CharizardIcon
	dw SquirtleIcon
	dw WartortleIcon
	dw BlastoiseIcon
	dw CaterpieIcon
	dw MetapodIcon
	dw ButterfreeIcon
	dw WeedleIcon
	dw KakunaIcon
	dw BeedrillIcon
	dw PidgeyIcon
	dw PidgeottoIcon
	dw PidgeotIcon
	dw RattataIcon
	dw RaticateIcon
	dw SpearowIcon
	dw FearowIcon
	dw EkansIcon
	dw ArbokIcon
	dw PikachuIcon
	dw RaichuIcon
	dw SandshrewIcon
	dw SandslashIcon
	dw NidoranFIcon
	dw NidorinaIcon
	dw NidoqueenIcon
	dw NidoranMIcon
	dw NidorinoIcon
	dw NidokingIcon
	dw ClefairyIcon
	dw ClefableIcon
	dw VulpixIcon
	dw NinetalesIcon
	dw JigglypuffIcon
	dw WigglytuffIcon
	dw ZubatIcon
	dw GolbatIcon
	dw OddishIcon
	dw GloomIcon
	dw VileplumeIcon
	dw ParasIcon
	dw ParasectIcon
	dw VenonatIcon
	dw VenomothIcon
	dw DiglettIcon
	dw DugtrioIcon
	dw MeowthIcon
	dw PersianIcon
	dw PsyduckIcon
	dw GolduckIcon
	dw MankeyIcon
	dw PrimeapeIcon
	dw GrowlitheIcon
	dw ArcanineIcon
	dw PoliwagIcon
	dw PoliwhirlIcon
	dw PoliwrathIcon
	dw AbraIcon
	dw KadabraIcon
	dw AlakazamIcon
	dw MachopIcon
	dw MachokeIcon
	dw MachampIcon
	dw BellsproutIcon
	dw WeepinbellIcon
	dw VictreebelIcon
	dw TentacoolIcon
	dw TentacruelIcon
	dw GeodudeIcon
	dw GravelerIcon
	dw GolemIcon
	dw PonytaIcon
	dw RapidashIcon
	dw SlowpokeIcon
	dw SlowbroIcon
	dw MagnemiteIcon
	dw MagnetonIcon
	dw FarfetchdIcon
	dw DoduoIcon
	dw DodrioIcon
	dw SeelIcon
	dw DewgongIcon
	dw GrimerIcon
	dw MukIcon
	dw ShellderIcon
	dw CloysterIcon
	dw GastlyIcon
	dw HaunterIcon
	dw GengarIcon
	dw OnixIcon
	dw DrowzeeIcon
	dw HypnoIcon
	dw KrabbyIcon
	dw KinglerIcon
	dw VoltorbIcon
	dw ElectrodeIcon
	dw ExeggcuteIcon
	dw ExeggutorIcon
	dw CuboneIcon
	dw MarowakIcon
	dw HitmonleeIcon
	dw HitmonchanIcon
	dw LickitungIcon
	dw KoffingIcon
	dw WeezingIcon
	dw RhyhornIcon
	dw RhydonIcon
	dw ChanseyIcon
	dw TangelaIcon
	dw KangaskhanIcon
	dw HorseaIcon
	dw SeadraIcon
	dw GoldeenIcon
	dw SeakingIcon
	dw StaryuIcon
	dw StarmieIcon
	dw MrMimeIcon
	dw ScytherIcon
	dw JynxIcon
	dw ElectabuzzIcon
	dw MagmarIcon
	dw PinsirIcon
	dw TaurosIcon
	dw MagikarpIcon
	dw GyaradosIcon
	dw LaprasIcon
	dw DittoIcon
	dw EeveeIcon
	dw VaporeonIcon
	dw JolteonIcon
	dw FlareonIcon
	dw PorygonIcon
	dw OmanyteIcon
	dw OmastarIcon
	dw KabutoIcon
	dw KabutopsIcon
	dw AerodactylIcon
	dw SnorlaxIcon
	dw ArticunoIcon
	dw ZapdosIcon
	dw MoltresIcon
	dw DratiniIcon
	dw DragonairIcon
	dw DragoniteIcon
	dw MewtwoIcon
	dw MewIcon
	dw TropiusIcon
	dw KecleonIcon
	dw ChatotIcon
	dw PikipekIcon
	dw TrumbeakIcon
	dw ToucannonIcon
	dw MunchlaxIcon
	dw MinccinoIcon
	dw CinccinoIcon
	dw WIngullIcon
	dw PelipperIcon
	dw ChinglingIcon
	dw ChimechoIcon
	dw SalanditIcon
	dw SalazzleIcon
	dw FinneonIcon
	dw LumineonIcon
	dw CrobatIcon
	dw ChinchouIcon
	dw LanturnIcon
	dw PichuIcon
	dw CleffaIcon
	dw IgglybuffIcon
	dw TogepiIcon
	dw TogeticIcon
	dw TogekissIcon
	dw AzurillIcon
	dw MareepIcon
	dw FlaaffyIcon
	dw AmpharosIcon
	dw BellossomIcon
	dw MarillIcon
	dw AzumarillIcon
	dw MimeJrIcon
	dw PolitoedIcon
	dw HoppipIcon
	dw SkiploomIcon
	dw JumpluffIcon
	dw StunfiskIcon
	dw SunkernIcon
	dw SunfloraIcon
	dw LeafeonIcon
	dw GlaceonIcon
	dw SylveonIcon
	dw EspeonIcon
	dw UmbreonIcon
	dw RelicanthIcon
	dw SlowkingIcon
	dw MimikyuIcon
	dw SpindaIcon
	dw SkrelpIcon
	dw DragalgeIcon
	dw TrapinchIcon
	dw VibravaIcon
	dw FlygonIcon
	dw TurtonatorIcon
	dw SteelixIcon
	dw WailmerIcon
	dw WailordIcon
	dw QwilfishIcon
	dw ScizorIcon
	dw ShuckleIcon
	dw MareanieIcon
	dw ToxapexIcon
	dw SandygastIcon
	dw PalossandIcon
	dw SlugmaIcon
	dw MagcargoIcon
	dw CarvanhaIcon
	dw SharpedoIcon
	dw CorsolaIcon
	dw RemoraidIcon
	dw OctilleryIcon
	dw MantykeIcon
	dw MantineIcon
	dw SkarmoryIcon
	dw MagmortarIcon
	dw ElectivireIcon
	dw KingdraIcon
	dw PhanpyIcon
	dw DonphanIcon
	dw Porygon2Icon
	dw PorygonZIcon
	dw LickilickyIcon
	dw TyrogueIcon
	dw HitmontopIcon
	dw SmoochumIcon
	dw ElekidIcon
	dw MagbyIcon
	dw HappinyIcon
	dw BlisseyIcon
	dw CutieflyIcon
	dw RibombeeIcon
	dw TangrowthIcon
	dw RhyperiorIcon
	dw MagnezoneIcon
	dw MarshadowIcon
	dw LugiaIcon
	dw HoOhIcon
	dw CelebiIcon
	dw LatiasIcon
	dw LatiosIcon
	dw EggIcon

SECTION "Mon Icons 1", ROMX

INCLUDE "menu/mon_icons_1.asm"

SECTION "Mon Icons 2", ROMX

INCLUDE "menu/mon_icons_2.asm"