	db "LEADER@" ; CISSY
	db "LEADER@" ; DANNY
	db "LEADER@" ; RUDY
	db "LEADER@" ; LUANA
	db "LEADER@" ; DRAKE
	db "<PK><MN> WATCHER@" ; TRACEY
	db "LEADER@" ; BROCK
	db "LEADER@" ; MISTY
	db "LEADER@" ; LT_SURGE
	db "LEADER@" ; ERIKA
	db "LEADER@" ; KOGA
	db "LEADER@" ; SABRINA
	db "LEADER@" ; BLAINE
	db "BOSS@" ; GIOVANNI
	db "ELITE FOUR@" ; LORELEI
	db "ELITE FOUR@" ; BRUNO
	db "ELITE FOUR@" ; AGATHA
	db "ELITE FOUR@" ; LANCE
	db "<PK><MN> TRAINER@" ; RED
	db "<PK><MN> TRAINER@" ; BLUE
	db "<PK><MN> TRAINER@" ; GREEN
	db "<PK><MN> TRAINER@" ; YELLOW
	db "<PK><MN> TRAINER@" ; CAL
	db "ROCKET@" ; BUTCH
	db "ROCKET@" ; CASSIDY
	db "CASSIDY@" ; CASSIDY_BUTCH
	db "ROCKET@" ; JAMES
	db "ROCKET@" ; JESSIE
	db "JESSIE@" ; JESSIE_JAMES
	db "<PK><MN> TRAINER@" ; MOM
	db "#MANIAC@" ; BILL
	db "STRANGER@" ; IMAKUNI
	db "COLLECTOR@" ; LAWRENCE
	db "#MON PROF.@" ; PROF_OAK
	db "#MON PROF.@" ; PROF_IVY
	db "PROF.AIDE@" ; PROF_AIDE
	db "NURSE@" ; NURSE
	db "OFFICER@" ; OFFICER
	db "YOUNGSTER@" ; YOUNGSTER
	db "LASS@" ; LASS
	db "BEAUTY@" ; BEAUTY
	db "BUG CATCHER@" ; BUG_CATCHER
	db "BUG CATCHER♀@" ; BUG_CATCHER_F
	db "SWIMMER♂@" ; SWIMMERM
	db "SWIMMER♀@" ; SWIMMERF
	db "CAMPER@" ; CAMPER
	db "#MANIAC@" ; POKEMANIAC
	db "FISHER@" ; FISHER
	db "HIKER@" ; HIKER
	db "ATHLETE@" ; ATHLETE
	db "SIGHTSEER♂@" ; SIGHTSEERM
	db "SIGHTSEER♀@" ; SIGHTSEERF
	db "WAITRESS@" ; WAITRESS
	db "SCHOOLBOY@" ; SCHOOLBOY
	db "BIRD KEEPER@" ; BIRD_KEEPER
	db "COOLTRAINER♂@" ; COOLTRAINERM
	db "COOLTRAINER♀@" ; COOLTRAINERF
	db "GENTLEMAN@" ; GENTLEMAN
	db "TEACHER@" ; TEACHER
	db "SAILOR@" ; SAILOR
	db "SUPER NERD@" ; SUPER_NERD
	db "GUITARIST@" ; GUITARIST
	db "BIKER@" ; BIKER
	db "FIREBREATHER@" ; FIREBREATHER
	db "JUGGLER@" ; JUGGLER
	db "BLACKBELT@" ; BLACKBELT_T
	db "PSYCHIC@" ; PSYCHIC_T
	db "PICNICKER@" ; PICNICKER
	db "SAGE@" ; SAGE
	db "MEDIUM@" ; MEDIUM
	db "POKEFAN♂@" ; POKEFANM
	db "POKEFAN♀@" ; POKEFANF
